# Generated by Django 6.0.5 on 2026-06-23 12:44

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssociationMembershipType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssociationMembershipTypePrice",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="associations.associationmembershiptype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
