# Generated by Django 6.0.5 on 2026-06-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationmembershiptype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
