# Generated by Django 6.0.5 on 2026-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0002_alter_associationmembershiptype_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="associationmembershiptypeprice",
            constraint=models.UniqueConstraint(
                fields=("type", "valid_from"), name="unique_date"
            ),
        ),
    ]
