# Generated by Django 6.0.5 on 2026-06-24 15:14

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0003_associationmembershiptypeprice_unique_date"),
        ("wirgarten", "0118_memberextraemailupdatedlogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationMembership",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="associations.associationmembershiptype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
