# Generated by Django 6.0.5 on 2026-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0004_associationmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationmembershiptype",
            name="description_in_bestell_wizard",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="associationmembershiptype",
            name="order_in_bestell_wizard",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
