# Generated by Django 6.0.5 on 2026-06-25 16:43

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "associations",
            "0005_associationmembershiptype_description_in_bestell_wizard_and_more",
        ),
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationMembershipCreatedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("values", django.contrib.postgres.fields.hstore.HStoreField()),
                ("type_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="AssociationMembershipDeletedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("type_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
            ],
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="AssociationMembershipUpdatedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("old_values", django.contrib.postgres.fields.hstore.HStoreField()),
                ("new_values", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "abstract": False,
            },
            bases=("log.logentry",),
        ),
    ]
