# Generated by Django 6.0.5 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0006_associationmembershipcreatedlogentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationmembership",
            name="cancellation_ts",
            field=models.DateTimeField(null=True),
        ),
    ]
