# Generated by Django 6.0.5 on 2026-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0007_associationmembership_cancellation_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationmembership",
            name="membership_ended_mail_sent",
            field=models.BooleanField(default=False),
        ),
    ]
