# Generated by Django 6.0.5 on 2026-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0008_associationmembership_membership_ended_mail_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="associationmembership",
            name="membership_ended_mail_sent",
        ),
        migrations.AddField(
            model_name="associationmembership",
            name="membership_ended_mail_sent_on",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
