# Generated by Django 6.0.7 on 2026-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "associations",
            "0009_remove_associationmembership_membership_ended_mail_sent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="associationmembershiptype",
            name="hidden_in_bestell_wizard",
            field=models.BooleanField(default=False),
        ),
    ]
