# Generated by Django 5.2 on 2025-04-10 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noticeperiod",
            old_name="duration_in_months",
            new_name="duration",
        ),
    ]
