# Generated by Django 5.2.1 on 2025-08-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("subscriptions", "0002_rename_duration_in_months_noticeperiod_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionsRevokedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("subscriptions", models.CharField(max_length=10000)),
            ],
            bases=("log.logentry",),
        ),
    ]
