# Generated by Django 5.2.1 on 2026-01-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscriptionchangedlogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticeperiod",
            name="unit",
            field=models.CharField(
                choices=[("months", "Monate"), ("weeks", "Wochen")],
                default="month",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
