# Generated by Django 5.2.1 on 2026-01-20 12:30

from django.db import migrations

from tapir.wirgarten.parameter_keys import ParameterKeys


def set_notice_period_units(apps, schema):
    # Before this migration, NoticePeriod and Subscription objects didn't have an own unit field
    # and were using the values from the config
    # Also, some Subscriptions created before the notice_period_duration field existed
    # still had a null value and were using the values from the product type or from the global config.
    # After this migration, unit fields for both NoticePeriod and Subscription should be set
    # and duration fields for Subscriptions should be set too

    tapir_parameter_class = apps.get_model("configuration", "TapirParameter")
    duration_parameter = tapir_parameter_class.objects.filter(
        key=ParameterKeys.SUBSCRIPTION_DEFAULT_NOTICE_PERIOD
    ).first()
    unit_parameter = tapir_parameter_class.objects.filter(
        key=ParameterKeys.SUBSCRIPTION_DEFAULT_NOTICE_PERIOD_UNIT
    ).first()
    if duration_parameter is None or unit_parameter is None:
        return

    unit = str(unit_parameter.value)
    duration = int(duration_parameter.value)

    notice_period_class = apps.get_model("subscriptions", "NoticePeriod")
    notice_period_class.objects.update(unit=unit)

    subscription_class = apps.get_model("wirgarten", "Subscription")
    subscription_class.objects.update(notice_period_unit=unit)

    subscription_class.objects.filter(notice_period_duration__isnull=True).update(
        notice_period_duration=duration
    )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_noticeperiod_unit"),
        ("configuration", "0006_tapirparameter_debug"),
        ("wirgarten", "0089_subscription_notice_period_unit"),
    ]

    operations = [
        migrations.RunPython(set_notice_period_units),
    ]
