# Generated by Django 6.0.4 on 2026-05-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscriptionpricechangedlogentry"),
        ("wirgarten", "0109_remove_mandatereference_end_ts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpricechangedlogentry",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wirgarten.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpricechangedlogentry",
            name="subscription_formatted",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
