# Generated by Django 6.0.4 on 2026-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0008_subscriptionpricechangedlogentry_subscription_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpricechangedlogentry",
            name="price_after",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpricechangedlogentry",
            name="price_before",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
