# Generated by Django 3.2.15 on 2022-09-23 10:37

import django.db.models.deletion
import localflavor.generic.models
from django.db import migrations, models

import tapir.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrowingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "tapiruser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.tapiruser",
                    ),
                ),
                (
                    "account_owner",
                    models.CharField(max_length=150, verbose_name="Account owner"),
                ),
                (
                    "iban",
                    localflavor.generic.models.IBANField(
                        include_countries=None,
                        max_length=34,
                        use_nordea_extensions=False,
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    localflavor.generic.models.BICField(
                        max_length=11, verbose_name="BIC"
                    ),
                ),
                ("sepa_consent", models.DateTimeField(verbose_name="SEPA Consent")),
                (
                    "withdrawal_consent",
                    models.DateTimeField(verbose_name="Right of withdrawal consent"),
                ),
                (
                    "privacy_consent",
                    models.DateTimeField(verbose_name="Privacy consent"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("accounts.tapiruser", models.Model),
            managers=[
                ("objects", tapir.accounts.models.TapirUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=150, verbose_name="Name")),
                (
                    "coords_lon",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="Coordinates Longitude",
                    ),
                ),
                (
                    "coords_lat",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="Coordinates Latitude",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=150, verbose_name="Street and house number"
                    ),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Extra address line"
                    ),
                ),
                ("postcode", models.CharField(max_length=32, verbose_name="Postcode")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "info",
                    models.CharField(
                        max_length=150,
                        verbose_name="Additional info like opening times",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=6),
                ),
                ("deleted", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="HarvestShareProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wirgarten.product",
                    ),
                ),
                ("min_coop_shares", models.IntegerField()),
            ],
            bases=("wirgarten.product",),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cancellation_ts", models.DateTimeField(null=True)),
                ("solidarity_price", models.FloatField(default=0.0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.member",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.growingperiod",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(null=False)),
                ("share_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("entry_date", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.growingperiod",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.producttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.producttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="pickuplocation",
            constraint=models.UniqueConstraint(
                fields=("name", "coords_lat", "coords_lon"), name="unique_location"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pickup_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
