# Generated by Django 3.2.15 on 2022-09-21 11:04

from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models
import tapir.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=60)),
                ("variant", models.CharField(max_length=16)),
                ("amount", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ChickenShareProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.CharField(max_length=16, null=True)),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HarvestShareProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.CharField(max_length=16, null=True)),
                ("price", models.FloatField()),
                ("min_coop_shares", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "tapiruser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.tapiruser",
                    ),
                ),
                (
                    "solidarity_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Solidarpreis"
                    ),
                ),
                (
                    "account_owner",
                    models.CharField(max_length=150, verbose_name="Account owner"),
                ),
                (
                    "iban",
                    localflavor.generic.models.IBANField(
                        include_countries=None,
                        max_length=34,
                        use_nordea_extensions=False,
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    localflavor.generic.models.BICField(
                        max_length=11, verbose_name="BIC"
                    ),
                ),
                ("sepa_consent", models.DateTimeField(verbose_name="SEPA Consent")),
                (
                    "withdrawal_consent",
                    models.DateTimeField(verbose_name="Right of withdrawal consent"),
                ),
                (
                    "privacy_consent",
                    models.DateTimeField(verbose_name="Privacy consent"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("accounts.tapiruser", models.Model),
            managers=[
                ("objects", tapir.accounts.models.TapirUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=150, verbose_name="Name")),
                (
                    "coords_lon",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="Coordinates Longitude",
                    ),
                ),
                (
                    "coords_lat",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=12,
                        verbose_name="Coordinates Latitude",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=150, verbose_name="Street and house number"
                    ),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Extra address line"
                    ),
                ),
                ("postcode", models.CharField(max_length=32, verbose_name="Postcode")),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "info",
                    models.CharField(
                        max_length=150,
                        verbose_name="Additional info like opening times",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pickuplocation",
            constraint=models.UniqueConstraint(
                fields=("name", "coords_lat", "coords_lon"), name="unique_location"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="pickup_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.AddField(
            model_name="activeproduct",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="wirgarten.member"
            ),
        ),
    ]
