# Generated by Django 3.2.15 on 2022-09-26 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("pdf", "PDF")], max_length=8
                    ),
                ),
                ("file", models.BinaryField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 9, 26, 11, 55, 26, 871123)
                    ),
                ),
            ],
        ),
    ]
