# Generated by Django 3.2.18 on 2023-03-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0002_auto_20230220_1925"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareownership",
            name="cancellation_ts",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="shareownership",
            name="membership_end_date",
            field=models.DateField(null=True),
        ),
    ]
