# Generated by Django 3.2.16 on 2022-10-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0003_auto_20221007_1342"),
    ]

    operations = [
        migrations.CreateModel(
            name="MandateReference",
            fields=[
                (
                    "ref",
                    models.CharField(max_length=35, primary_key=True, serialize=False),
                ),
                ("start_ts", models.DateTimeField()),
                ("end_ts", models.DateTimeField(null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="mandate_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.mandatereference",
            ),
        ),
    ]
