# Generated by Django 3.2.18 on 2023-03-20 13:17

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0003_auto_20230308_1700"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoopShareTransaction",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Zeichnung von Anteilen"),
                            ("cancellation", "Kündigung von Anteilen"),
                            ("transfer_out", "Abgabe von Anteilen"),
                            ("transfer_in", "Empfang von Anteilen"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("share_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("valid_at", models.DateField()),
                (
                    "mandate_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.mandatereference",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ShareOwnership",
        ),
    ]
