# Generated by Django 3.2.16 on 2022-10-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0004_auto_20221019_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="mandate_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.mandatereference",
            ),
        ),
    ]
