# Generated by Django 3.2.18 on 2023-03-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0005_alter_coopsharetransaction_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="coopsharetransaction",
            name="transfer_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="transfer_member",
                to="wirgarten.member",
            ),
        ),
    ]
