# Generated by Django 3.2.18 on 2023-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0006_coopsharetransaction_transfer_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="member_no",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="Mitgliedsnummer"
            ),
        ),
    ]
