# Generated by Django 3.2.16 on 2022-10-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0006_shareownership_mandate_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareownership",
            name="mandate_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.mandatereference",
            ),
        ),
    ]
