# Generated by Django 3.2.18 on 2023-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0007_member_member_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="bic",
        ),
        migrations.AddField(
            model_name="subscription",
            name="withdrawal_consent_ts",
            field=models.DateTimeField(null=True),
        ),
    ]
