# Generated by Django 3.2.18 on 2023-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0007_member_member_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="productcapacity",
            index=models.Index(fields=["period"], name="idx_productcapacity_period"),
        ),
    ]
