# Generated by Django 3.2.16 on 2022-10-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0007_alter_shareownership_mandate_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "mandate_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.mandatereference",
                    ),
                ),
            ],
        ),
    ]
