# Generated by Django 3.2.18 on 2023-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0009_alter_coopsharetransaction_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
