# Generated by Django 3.2.16 on 2022-10-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0010_deliveries"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveries",
            name="pickup_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
