# Generated by Django 3.2.18 on 2023-04-06 19:27

import datetime
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0010_alter_subscription_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coopsharetransaction",
            name="timestamp",
            field=models.DateTimeField(
                default=functools.partial(datetime.datetime.now, *(), **{})
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=functools.partial(datetime.datetime.now, *(), **{})
            ),
        ),
    ]
