# Generated by Django 3.2.18 on 2023-04-08 15:41

from django.db import migrations, models
import django.utils.timezone
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0011_auto_20230406_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coopsharetransaction",
            name="timestamp",
            field=models.DateTimeField(
                default=functools.partial(django.utils.timezone.now, *(), **{})
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(
                default=functools.partial(django.utils.timezone.now, *(), **{})
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=functools.partial(django.utils.timezone.now, *(), **{})
            ),
        ),
    ]
