# Generated by Django 3.2.16 on 2022-10-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0004_auto_20221007_1610"),
        ("wirgarten", "0012_alter_deliveries_pickup_location"),
    ]

    operations = []
