# Generated by Django 3.2.16 on 2022-10-23 15:30

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0013_merge_20221022_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveries",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="exportedfile",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="growingperiod",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="pickup_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="productcapacity",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="shareownership",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
