# Generated by Django 3.2.18 on 2023-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0013_subscriptionchangelogentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionchangelogentry",
            name="subscriptions",
            field=models.CharField(max_length=1024),
        ),
    ]
