# Generated by Django 3.2.16 on 2022-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0014_auto_20221023_1730"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("mandate_ref", "due_date"), name="unique_mandate_ref_date"
            ),
        ),
    ]
