# Generated by Django 3.2.18 on 2023-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0008_auto_20230327_1204"),
        ("wirgarten", "0014_alter_subscriptionchangelogentry_subscriptions"),
    ]

    operations = []
