# Generated by Django 3.2.18 on 2023-04-14 11:05

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0015_merge_20230414_1255"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionaireTrafficSourceOption",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionaireTrafficSourceResponse",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="questionairetrafficsourceresponse",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.member",
            ),
        ),
        migrations.AddField(
            model_name="questionairetrafficsourceresponse",
            name="sources",
            field=models.ManyToManyField(
                to="wirgarten.QuestionaireTrafficSourceOption"
            ),
        ),
    ]
