# Generated by Django 3.2.16 on 2022-10-25 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0015_payment_unique_mandate_ref_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("tax_rate", models.FloatField()),
                (
                    "valid_from",
                    models.DateField(
                        default=functools.partial(datetime.date.today, *(), **{})
                    ),
                ),
                ("valid_to", models.DateField(null=True)),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.producttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
