# Generated by Django 3.2.16 on 2022-10-27 14:50

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0016_taxrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryExceptionPeriod",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("comment", models.CharField(default="", max_length=128)),
                (
                    "product_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.producttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
