# Generated by Django 3.2.16 on 2022-10-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0017_auto_20221031_1541"),
        ("wirgarten", "0017_deliveryexceptionperiod"),
    ]

    operations = []
