# Generated by Django 3.2.18 on 2023-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0017_auto_20230417_1300"),
    ]

    operations = [
        migrations.AddField(
            model_name="coopsharetransaction",
            name="admin_confirmed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="admin_confirmed",
            field=models.DateTimeField(null=True),
        ),
    ]
