# Generated by Django 3.2.18 on 2023-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0017_auto_20230417_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="solidarity_price_absolute",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
