# Generated by Django 3.2.18 on 2023-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0018_auto_20230417_1304"),
        ("wirgarten", "0018_auto_20230417_1646"),
    ]

    operations = []
