# Generated by Django 3.2.18 on 2023-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0019_merge_0018_auto_20230417_1304_0018_auto_20230417_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
