# Generated by Django 3.2.16 on 2022-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0021_alter_editfuturepaymentlogentry_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="pickup_enabled",
        ),
        migrations.AddField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("even_weeks", "2x pro Woche (2. und 4. Woche)"),
                    ("odd_weeks", "2x pro Woche (1. und 3. Woche)"),
                    ("monthly", "1x pro Monat"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Produkt Name"),
        ),
    ]
