# Generated by Django 3.2.18 on 2023-05-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wirgarten", "0021_auto_20230509_1046"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberPickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.pickuplocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "valid_from")},
            },
        ),
    ]
