# Generated by Django 3.2.16 on 2022-11-08 13:24

import datetime
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0022_auto_20221108_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(
                default=functools.partial(datetime.datetime.now, *(), **{})
            ),
        ),
    ]
