# Generated by Django 3.2.18 on 2023-05-15 09:35

from django.db import migrations


def copy_pickup_locations(apps, schema_editor):
    Member = apps.get_model("wirgarten", "Member")
    MemberPickupLocation = apps.get_model("wirgarten", "MemberPickupLocation")

    for member in Member.objects.all():
        if member.pickup_location is not None:
            MemberPickupLocation.objects.create(
                member=member,
                pickup_location=member.pickup_location,
                valid_from=member.created_at.date(),
            )


class Migration(migrations.Migration):
    dependencies = [
        ("wirgarten", "0022_auto_20230515_1134"),
    ]

    operations = [
        migrations.RunPython(copy_pickup_locations),
    ]
