# Generated by Django 3.2.18 on 2023-05-15 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wirgarten", "0023_auto_20230515_1135"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="pickup_location",
        ),
    ]
