# Generated by Django 3.2.16 on 2022-11-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0023_alter_paymenttransaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.exportedfile",
            ),
        ),
    ]
