# Generated by Django 3.2.16 on 2022-11-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0024_paymenttransaction_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.exportedfile",
            ),
        ),
    ]
