# Generated by Django 3.2.18 on 2023-05-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0024_auto_20230515_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocationcapability",
            name="max_capacity",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
