# Generated by Django 3.2.16 on 2022-11-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0022_auto_20221108_1312"),
        ("wirgarten", "0025_alter_paymenttransaction_file"),
    ]

    operations = []
