# Generated by Django 3.2.18 on 2023-05-16 11:23

from django.db import migrations, models
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0025_auto_20230516_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberpickuplocation",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
