# Generated by Django 3.2.18 on 2023-05-24 09:30

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0026_auto_20230516_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocation",
            name="access_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Access Code"
            ),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Name of the contact"
            ),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="messenger_group_link",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Messenger Group Link"
            ),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="photo_link",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Photo Link"
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocation",
            name="info",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Additional info"
            ),
        ),
        migrations.CreateModel(
            name="PickupLocationOpeningTime",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_times",
                        to="wirgarten.pickuplocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
