# Generated by Django 3.2.18 on 2023-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0027_auto_20230524_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickuplocation",
            name="info",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Additional info"
            ),
        ),
    ]
