# Generated by Django 3.2.16 on 2022-11-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0029_alter_productprice_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.UniqueConstraint(
                fields=("product", "valid_from"), name="unique_product_price_date"
            ),
        ),
    ]
