# Generated by Django 3.2.18 on 2023-06-13 13:25

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0029_auto_20230608_1421"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionaireCancellationReasonResponse",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
