# Generated by Django 3.2.18 on 2023-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0030_auto_20230613_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionairecancellationreasonresponse",
            name="custom",
            field=models.BooleanField(default=False),
        ),
    ]
