# Generated by Django 3.2.16 on 2022-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0030_auto_20221121_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "2x pro Monat (ungerade KW)"),
                    ("even_weeks", "2x pro Monat (gerade KW)"),
                    ("monthly", "1x pro Monat"),
                ],
                default=("no_delivery", "Keine Lieferung/Abholung"),
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
        migrations.AddConstraint(
            model_name="producttype",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_product_Type"
            ),
        ),
    ]
