# Generated by Django 3.2.18 on 2023-06-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0031_auto_20230613_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
