# Generated by Django 3.2.16 on 2022-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0031_auto_20221123_1856"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mandatereference",
            index=models.Index(fields=["member"], name="idx_mandatereference_mamber"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["mandate_ref"], name="idx_payment_mandate_ref"),
        ),
        migrations.AddIndex(
            model_name="productprice",
            index=models.Index(fields=["product"], name="idx_productprice_product"),
        ),
        migrations.AddIndex(
            model_name="shareownership",
            index=models.Index(fields=["member"], name="idx_shareownership_member"),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["product_type"], name="idx_tax_rate_product_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.UniqueConstraint(
                fields=("product_type", "valid_from"),
                name="unique_tax_rate_product_type_valid_from",
            ),
        ),
    ]
