# Generated by Django 3.2.16 on 2022-12-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0034_auto_20221201_1139"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedCoopSharesLogEntry",
            fields=[
                (
                    "transfercoopshareslogentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wirgarten.transfercoopshareslogentry",
                    ),
                ),
            ],
            bases=("wirgarten.transfercoopshareslogentry",),
        ),
    ]
