# Generated by Django 3.2.18 on 2023-07-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirgarten', '0034_auto_20230615_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date_override',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
