# Generated by Django 3.2.18 on 2023-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0035_auto_20230707_1307"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="subscription",
            name="wirgarten_s_period__f679c5_idx",
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["due_date"], name="idx_payment_due_date"),
        ),
        migrations.AddIndex(
            model_name="productprice",
            index=models.Index(
                fields=["-valid_from"], name="idx_productprice_valid_from"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["period_id"], name="wirgarten_s_period__601d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["-created_at"], name="wirgarten_s_created_09bef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["start_date"], name="wirgarten_s_start_d_63691a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["end_date"], name="wirgarten_s_end_dat_14a132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["member"], name="wirgarten_s_member__2ed1a9_idx"
            ),
        ),
    ]
