# Generated by Django 3.2.16 on 2022-12-03 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0036_waitinglistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareownership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
