# Generated by Django 3.2.23 on 2023-12-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0038_auto_20230921_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="coopsharetransaction",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment",
                to="wirgarten.payment",
            ),
        ),
    ]
