# Generated by Django 3.2.16 on 2023-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0039_member_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["period_id", "created_at"],
                name="wirgarten_s_period__f679c5_idx",
            ),
        ),
    ]
