# Generated by Django 3.2.25 on 2024-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0040_subscription_price_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="Student"),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "2x pro Monat (ungerade KW)"),
                    ("even_weeks", "2x pro Monat (gerade KW)"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
    ]
