# Generated by Django 3.2.25 on 2024-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0042_alter_member_is_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="size",
            field=models.DecimalField(
                decimal_places=4, default=1, editable=False, max_digits=8
            ),
            preserve_default=False,
        ),
    ]
