# Generated by Django 3.2.25 on 2025-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirgarten', '0045_producttype_is_affected_by_jokers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notice_period_duration_in_months',
            field=models.IntegerField(null=True),
        ),
    ]
