# Generated by Django 3.2.25 on 2025-03-24 14:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0046_subscription_notice_period_duration_in_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingperiod",
            name="weeks_without_delivery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(53),
                ],
            ),
        ),
    ]
