# Generated by Django 3.2.25 on 2025-03-24 15:46

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0047_growingperiod_weeks_without_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growingperiod",
            name="weeks_without_delivery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(1),
                        django.core.validators.MaxValueValidator(53),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
