# Generated by Django 3.2.25 on 2025-04-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0048_alter_growingperiod_weeks_without_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryexceptionperiod",
            name="product_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocationcapability",
            name="pickup_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.AlterField(
            model_name="pickuplocationcapability",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wirgarten.producttype"
            ),
        ),
        migrations.AlterField(
            model_name="productcapacity",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.growingperiod",
            ),
        ),
        migrations.AlterField(
            model_name="productcapacity",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wirgarten.producttype"
            ),
        ),
    ]
