# Generated by Django 3.2.25 on 2025-04-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0049_auto_20250401_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrate",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wirgarten.producttype"
            ),
        ),
    ]
