# Generated by Django 5.2 on 2025-04-10 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wirgarten", "0050_alter_taxrate_product_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="notice_period_duration_in_months",
            new_name="notice_period_duration",
        ),
    ]
