# Generated by Django 5.2 on 2025-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0052_producttype_subscriptions_have_end_dates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="must_be_subscribed_to",
            field=models.BooleanField(
                default=False,
                help_text="Ob es Pflicht ist, ein Abonnement an dieses Produkt zu zu zeichnen.",
                verbose_name="Muss gezeichnet werden",
            ),
        ),
    ]
