# Generated by Django 5.2 on 2025-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0053_producttype_must_be_subscribed_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="is_association_membership",
            field=models.BooleanField(
                default=False, verbose_name="Repräsentiert Vereinsmitgliedschaften"
            ),
        ),
    ]
