# Generated by Django 5.2 on 2025-04-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0054_producttype_is_association_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingperiod",
            name="joker_restrictions",
            field=models.CharField(default="disabled", max_length=1024),
        ),
        migrations.AddField(
            model_name="growingperiod",
            name="max_jokers_per_member",
            field=models.IntegerField(default=4),
        ),
    ]
