# Generated by Django 5.2 on 2025-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0055_growingperiod_joker_restrictions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancellation_admin_confirmed",
            field=models.DateTimeField(null=True),
        ),
    ]
