# Generated by Django 5.2 on 2025-05-06 10:06

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wirgarten",
            "0057_remove_waitinglistentry_type_waitinglistentry_city_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitinglistentry",
            name="product",
        ),
        migrations.CreateModel(
            name="WaitingListProductWishes",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.product",
                    ),
                ),
                (
                    "waiting_list_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wirgarten.waitinglistentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
