# Generated by Django 5.2 on 2025-05-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0058_remove_waitinglistentry_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistpickuplocationwishes",
            name="waiting_list_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pickup_location_wishes",
                to="wirgarten.waitinglistentry",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglistproductwishes",
            name="waiting_list_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_wishes",
                to="wirgarten.waitinglistentry",
            ),
        ),
    ]
