# Generated by Django 5.2 on 2025-05-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wirgarten",
            "0059_alter_waitinglistpickuplocationwishes_waiting_list_entry_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="waitinglistentry",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
