# Generated by Django 5.2 on 2025-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0060_rename_phone_waitinglistentry_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="waitinglistentry",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
