# Generated by Django 5.2 on 2025-05-07 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0061_waitinglistentry_category_waitinglistentry_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistpickuplocationwishes",
            name="waiting_list_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_location_wishes",
                to="wirgarten.waitinglistentry",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglistproductwishes",
            name="waiting_list_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_wishes",
                to="wirgarten.waitinglistentry",
            ),
        ),
    ]
