# Generated by Django 5.2 on 2025-05-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wirgarten",
            "0062_alter_waitinglistpickuplocationwishes_waiting_list_entry_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WaitingListPickupLocationWishes",
            new_name="WaitingListPickupLocationWish",
        ),
        migrations.RenameModel(
            old_name="WaitingListProductWishes",
            new_name="WaitingListProductWish",
        ),
    ]
