# Generated by Django 5.2 on 2025-05-12 14:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wirgarten",
            "0063_rename_waitinglistpickuplocationwishes_waitinglistpickuplocationwish_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "2x pro Monat (ungerade KW)"),
                    ("even_weeks", "2x pro Monat (gerade KW)"),
                    ("every_four_weeks", "Jede 4. Woche (Startpunkt in der Konfig)"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=128, region=None, verbose_name="Phone number"
            ),
            preserve_default=False,
        ),
    ]
