# Generated by Django 5.2 on 2025-05-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0064_alter_producttype_delivery_cycle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="solidarity_price",
            new_name="solidarity_price_percentage",
        ),
    ]
