# Generated by Django 5.2.1 on 2025-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wirgarten",
            "0065_rename_solidarity_price_subscription_solidarity_price_percentage",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="solidarity_price_percentage",
            field=models.FloatField(null=True),
        ),
    ]
