# Generated by Django 5.2.1 on 2025-06-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0066_alter_subscription_solidarity_price_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="description_bestellwizard",
            field=models.TextField(
                default="", verbose_name="Beschreibung im Bestellwizard"
            ),
        ),
    ]
