# Generated by Django 5.2.1 on 2025-11-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0066_alter_subscription_solidarity_price_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "Jede 2. Woche (ungerade KW)"),
                    ("even_weeks", "Jede 2. Woche (gerade KW)"),
                    ("every_four_weeks", "Jede 4. Woche"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
    ]
