# Generated by Django 5.2.1 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0067_alter_producttype_delivery_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="growingperiod",
            name="is_available_as_in_bestell_wizard",
            field=models.BooleanField(default=True),
        ),
    ]
