# Generated by Django 5.2.1 on 2025-11-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0068_growingperiod_is_available_as_in_bestell_wizard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="growingperiod",
            old_name="is_available_as_in_bestell_wizard",
            new_name="is_available_in_bestell_wizard",
        ),
    ]
