# Generated by Django 5.2.1 on 2025-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0068_producttype_order_in_bestellwizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_in_bestellwizard",
            field=models.TextField(default=""),
        ),
    ]
