# Generated by Django 5.2.1 on 2025-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0069_product_description_in_bestellwizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url_of_image_in_bestellwizard",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_in_bestellwizard",
            field=models.TextField(blank=True, default=""),
        ),
    ]
