# Generated by Django 5.2.1 on 2025-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0070_product_url_of_image_in_bestellwizard_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="description_bestellwizard",
        ),
        migrations.AddField(
            model_name="producttype",
            name="description_bestellwizard_long",
            field=models.TextField(
                default="",
                verbose_name="Beschreibung im Bestellwizard bei der Produkt-Spezifische Seite",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="description_bestellwizard_short",
            field=models.TextField(
                default="",
                verbose_name="Beschreibung im Bestellwizard bei der erste Seite (Produkt-Typ Auswahl)",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="order_in_bestellwizard",
            field=models.IntegerField(
                default=1,
                verbose_name="Reihenfolge im BestellWizard (kleiner ist früher)",
            ),
        ),
    ]
