# Generated by Django 5.2.1 on 2025-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0071_remove_producttype_description_bestellwizard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="confirmation_link_key",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "Jede 2. Woche (ungerade KW)"),
                    ("even_weeks", "Jede 2. Woche (gerade KW)"),
                    ("every_four_weeks", "Jede 4. Woche"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
    ]
