# Generated by Django 5.2.1 on 2025-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0072_waitinglistentry_confirmation_link_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="link_sent_date",
            field=models.DateTimeField(null=True),
        ),
    ]
