# Generated by Django 5.2.1 on 2025-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0073_waitinglistentry_link_sent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="capacity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
