# Generated by Django 5.2.1 on 2025-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0074_product_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="coopsharetransaction",
            name="auto_confirmed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_confirmed",
            field=models.DateTimeField(null=True),
        ),
    ]
