# Generated by Django 5.2.1 on 2025-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0075_coopsharetransaction_auto_confirmed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HarvestShareProduct",
        ),
        migrations.AddField(
            model_name="product",
            name="min_coop_shares",
            field=models.IntegerField(default=0),
        ),
    ]
