# Generated by Django 5.2.1 on 2025-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0076_product_min_coop_shares_delete_harvestshareproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxrate",
            name="valid_to",
        ),
        migrations.AddConstraint(
            model_name="productcapacity",
            constraint=models.UniqueConstraint(
                fields=("period", "product_type"), name="unique_period_type"
            ),
        ),
    ]
