# Generated by Django 5.2.1 on 2025-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0077_remove_taxrate_valid_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionchangelogentry",
            name="admin_confirmed",
            field=models.DateTimeField(null=True),
        ),
    ]
