# Generated by Django 5.2.1 on 2025-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0078_subscriptionchangelogentry_admin_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="force_waiting_list",
            field=models.BooleanField(default=False),
        ),
    ]
