# Generated by Django 5.2.1 on 2025-08-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0079_producttype_force_waiting_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="subscription_payment_range_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription_payment_range_start",
            field=models.DateField(null=True),
        ),
    ]
