# Generated by Django 5.2.1 on 2025-08-14 16:41

from django.db import migrations

from tapir.utils.shortcuts import get_last_day_of_month


def set_payment_ranges(apps, schema_editor):
    payment_model = apps.get_model("wirgarten", "Payment")

    payments = list(payment_model.objects.all())
    for payment in payments:
        if payment.type == "Genossenschaftsanteile":
            continue
        payment.subscription_payment_range_start = payment.due_date.replace(day=1)
        payment.subscription_payment_range_end = payment.due_date.replace(
            day=get_last_day_of_month(payment.due_date).day
        )

    payment_model.objects.bulk_update(
        payments, ["subscription_payment_range_start", "subscription_payment_range_end"]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0080_payment_subscription_payment_range_end_and_more"),
    ]

    operations = [
        migrations.RunPython(set_payment_ranges),
    ]
