# Generated by Django 5.2.1 on 2025-11-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0081_auto_20250815_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="title_bestellwizard_product_choice",
            field=models.CharField(default="", max_length=512),
        ),
    ]
