# Generated by Django 5.2.1 on 2025-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0082_producttype_title_bestellwizard_product_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="background_image_in_bestellwizard",
            field=models.CharField(default="", max_length=512),
        ),
    ]
