# Generated by Django 5.2.1 on 2025-12-08 19:33
import datetime
from decimal import Decimal

from django.db import migrations

from tapir.utils.services.tapir_cache import TapirCache
from tapir.utils.shortcuts import get_from_cache_or_compute


def get_product_price(
    product,
    reference_date: datetime.date,
    cache: dict,
):
    cache_for_this_product = get_from_cache_or_compute(cache, product, lambda: {})
    price_by_date_cache = get_from_cache_or_compute(
        cache_for_this_product, "price_by_date", lambda: {}
    )

    def get_price():
        prices = list(TapirCache.get_product_prices_by_product_id(cache, product.id))
        if len(prices) == 0:
            return None

        prices.sort(key=lambda p: p.valid_from, reverse=False)
        oldest_price = prices[0]
        if oldest_price.valid_from > reference_date:
            # If no price is defined at the subscription start date, get the closest available price
            return oldest_price

        prices.sort(key=lambda p: p.valid_from, reverse=True)
        for price in prices:
            if price.valid_from <= reference_date:
                return price
        return None

    return get_from_cache_or_compute(price_by_date_cache, reference_date, get_price)


def migrate_solidarity_percentage_to_absolute(apps, schema):
    Subscription = apps.get_model("wirgarten", "Subscription")
    cache = {}
    subscriptions = list(
        Subscription.objects.filter(
            solidarity_price_percentage__isnull=False
        ).select_related("product")
    )
    for subscription in subscriptions:
        price = get_product_price(
            product=subscription.product,
            reference_date=subscription.start_date,
            cache=cache,
        ).price
        subscription_price_without_solidarity = subscription.quantity * price
        old_absolute = subscription.solidarity_price_absolute or Decimal(0)
        new_absolute = old_absolute + Decimal(
            float(subscription_price_without_solidarity)
            * subscription.solidarity_price_percentage
        )
        subscription.solidarity_price_absolute = new_absolute
        subscription.solidarity_price_percentage = 0

    Subscription.objects.bulk_update(
        subscriptions, ["solidarity_price_absolute", "solidarity_price_percentage"]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0084_growingperiod_is_available_in_bestell_wizard"),
    ]

    operations = [
        migrations.RunPython(migrate_solidarity_percentage_to_absolute),
    ]
