# Generated by Django 5.2.1 on 2025-12-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0085_auto_20251208_2033"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="solidarity_price_percentage",
        ),
    ]
