# Generated by Django 5.2.1 on 2025-12-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0086_remove_subscription_solidarity_price_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="solidarity_price_absolute",
        ),
    ]
