# Generated by Django 5.2.1 on 2025-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0087_remove_subscription_solidarity_price_absolute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
