# Generated by Django 5.2.1 on 2026-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0089_subscription_notice_period_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="notice_period_duration",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
