# Generated by Django 6.0.1 on 2026-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0090_alter_subscription_notice_period_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="title_bestellwizard_intro",
            field=models.CharField(default="", max_length=512),
        ),
    ]
