# Generated by Django 6.0.1 on 2026-01-28 11:49

from django.db import migrations


def set_product_type_bestellwizard_intro_title(apps, schema):
    product_type_class = apps.get_model("wirgarten", "ProductType")
    product_types = product_type_class.objects.all()
    for product_type in product_types:
        product_type.title_bestellwizard_intro = "Unser " + product_type.name
    product_type_class.objects.bulk_update(product_types, ["title_bestellwizard_intro"])


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0091_producttype_title_bestellwizard_intro"),
    ]

    operations = [
        migrations.RunPython(set_product_type_bestellwizard_intro_title),
    ]
