# Generated by Django 6.0.1 on 2026-02-03 13:52

import django.db.models.deletion
import functools
import tapir.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("wirgarten", "0092_auto_20260128_1249"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberExtraEmailCreatedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("email", models.EmailField(max_length=1024)),
            ],
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="MemberExtraEmail",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("confirmed_on", models.DateTimeField(null=True)),
                ("secret", models.UUIDField(default=uuid.uuid4)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "email"), name="unique_extra_email"
                    )
                ],
            },
        ),
    ]
