# Generated by Django 6.0.1 on 2026-02-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("wirgarten", "0093_memberextraemailcreatedlogentry_memberextraemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberExtraEmailConfirmedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("email", models.EmailField(max_length=1024)),
            ],
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="MemberExtraEmailDeletedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("email", models.EmailField(max_length=1024)),
            ],
            bases=("log.logentry",),
        ),
    ]
