# Generated by Django 6.0.1 on 2026-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0094_memberextraemailconfirmedlogentry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(default="unknown", max_length=64),
            preserve_default=False,
        ),
    ]
