# Generated by Django 6.0.1 on 2026-02-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0095_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="wirgarten.exportedfile"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="type",
            field=models.CharField(default="unknown", max_length=32),
            preserve_default=False,
        ),
    ]
