# Generated by Django 6.0.1 on 2026-02-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0096_alter_paymenttransaction_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
