# Generated by Django 6.0.1 on 2026-02-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0097_alter_paymenttransaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
