# Generated by Django 6.0.1 on 2026-02-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0098_alter_paymenttransaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="pseudonym",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Pseudonym"
            ),
        ),
    ]
