# Generated by Django 6.0.1 on 2026-03-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0099_coopsharetransaction_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_mandate_ref_date",
        ),
    ]
