# Generated by Django 6.0.1 on 2026-09-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="is_bread",
            field=models.BooleanField(
                default=False, verbose_name="Brotanteil (Bäckerei)"
            ),
        ),
    ]
