# Generated by Django 6.0.1 on 2026-03-24 09:08

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0100_remove_payment_unique_mandate_ref_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="delivery_weeks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(1),
                        django.core.validators.MaxValueValidator(53),
                    ]
                ),
                blank=True,
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "Jede 2. Woche (ungerade KW)"),
                    ("even_weeks", "Jede 2. Woche (gerade KW)"),
                    ("every_four_weeks", "Jede 4. Woche"),
                    ("custom", "Freigelegte Lieferwochen"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
    ]
