# Generated by Django 6.0.1 on 2026-03-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0101_producttype_delivery_weeks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="delivery_weeks",
        ),
    ]
