# Generated by Django 6.0.1 on 2026-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0102_remove_producttype_delivery_weeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="delivery_cycle",
            field=models.CharField(
                choices=[
                    ("no_delivery", "Keine Lieferung/Abholung"),
                    ("weekly", "1x pro Woche"),
                    ("odd_weeks", "Jede 2. Woche (ungerade KW)"),
                    ("even_weeks", "Jede 2. Woche (gerade KW)"),
                    ("every_four_weeks", "Jede 4. Woche"),
                    ("custom", "Benutzerdefinierte Lieferwochen"),
                ],
                default="no_delivery",
                max_length=16,
                verbose_name="Lieferzyklus",
            ),
        ),
    ]
