# Generated by Django 6.0.1 on 2026-04-07 09:33

from django.db import migrations
from tapir_mail.models import ReleaseStatus


def update_token_name_messenger_group(apps, schema):
    # The dynamic token "Verteilstation - Signal-Gruppe" is now called "Verteilstation - Messenger-Gruppe"

    email_configuration_version_class = apps.get_model(
        "tapir_mail", "EmailConfigurationVersion"
    )

    for email_configuration_version in email_configuration_version_class.objects.filter(
        status__in=[ReleaseStatus.RELEASED, ReleaseStatus.DRAFT]
    ):
        content = email_configuration_version.content
        content = content.replace(
            "Verteilstation - Signal-Gruppe", "Verteilstation - Messenger-Gruppe"
        )
        email_configuration_version.content = content
        email_configuration_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0103_alter_producttype_delivery_cycle"),
    ]

    operations = [
        migrations.RunPython(update_token_name_messenger_group),
    ]
