# Generated by Django 6.0.1 on 2026-04-08 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0104_auto_20260407_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="month",
            field=models.DateField(default=datetime.date(2026, 4, 8)),
            preserve_default=False,
        ),
    ]
