# Generated by Django 6.0.1 on 2026-04-08 13:27

from django.db import migrations


def set_payment_transaction_months(apps, schema):
    payment_transaction_class = apps.get_model("wirgarten", "PaymentTransaction")
    payment_class = apps.get_model("wirgarten", "Payment")

    for transaction in payment_transaction_class.objects.all():
        payment = payment_class.objects.filter(transaction=transaction).first()
        if payment is None:
            transaction.month = transaction.created_at.date()
        else:
            transaction.month = payment.due_date.replace(day=1)
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0105_paymenttransaction_month"),
    ]

    operations = [
        migrations.RunPython(set_payment_transaction_months),
    ]
