# Generated by Django 6.0.1 on 2026-04-09 11:46

import functools
import tapir.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0107_orderfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderfeedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="orderfeedback",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AddField(
            model_name="orderfeedback",
            name="waiting_list_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.waitinglistentry",
            ),
        ),
        migrations.AlterField(
            model_name="orderfeedback",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.member",
            ),
        ),
    ]
