# Generated by Django 6.0.4 on 2026-04-27 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0108_orderfeedback_updated_at_alter_orderfeedback_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mandatereference",
            name="end_ts",
        ),
        migrations.AddField(
            model_name="mandatereference",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mandatereference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
