# Generated by Django 6.0.4 on 2026-05-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0109_remove_mandatereference_end_ts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberpickuplocation",
            name="pickup_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
