# Generated by Django 6.0.5 on 2026-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0110_alter_memberpickuplocation_pickup_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionairecancellationreasonresponse",
            name="reason",
            field=models.CharField(max_length=1000),
        ),
    ]
