# Generated by Django 6.0.5 on 2026-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0111_alter_questionairecancellationreasonresponse_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportedfile",
            name="type",
            field=models.CharField(
                choices=[("csv", "CSV"), ("pdf", "PDF"), ("xml", "XML")], max_length=8
            ),
        ),
    ]
