# Generated by Django 6.0.5 on 2026-06-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0112_alter_exportedfile_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenttransaction",
            old_name="file",
            new_name="csv_file",
        ),
    ]
