# Generated by Django 6.0.5 on 2026-06-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0113_rename_file_paymenttransaction_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="xml_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction_xml",
                to="wirgarten.exportedfile",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="csv_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction_csv",
                to="wirgarten.exportedfile",
            ),
        ),
    ]
