# Generated by Django 6.0.5 on 2026-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0114_paymenttransaction_xml_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberextraemail",
            name="first_name",
            field=models.CharField(default="changed_on_next_migration", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberextraemail",
            name="last_name",
            field=models.CharField(default="changed_on_next_migration", max_length=100),
            preserve_default=False,
        ),
    ]
