# Generated by Django 6.0.5 on 2026-06-11 15:05

from django.db import migrations


def set_default_name_for_member_extra_emails(apps, schema):
    member_extra_email_class = apps.get_model("wirgarten", "MemberExtraEmail")

    for extra_email in member_extra_email_class.objects.all():
        extra_email.first_name = extra_email.member.first_name
        extra_email.last_name = extra_email.member.last_name
        extra_email.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0115_memberextraemail_first_name_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_name_for_member_extra_emails),
    ]
