# Generated by Django 6.0.5 on 2026-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0116_auto_20260611_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberextraemailcreatedlogentry",
            name="first_name",
            field=models.CharField(default="unbekannt", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberextraemailcreatedlogentry",
            name="last_name",
            field=models.CharField(default="unbekannt", max_length=100),
            preserve_default=False,
        ),
    ]
