# Generated by Django 6.0.5 on 2026-07-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0118_memberextraemailupdatedlogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="has_received_membership_started_mail",
            field=models.BooleanField(default=False),
        ),
    ]
