# Generated by Django 6.0.5 on 2026-07-08 10:21

from django.db import migrations


def set_default_has_received_membership_started_mail(apps, schema_editor):
    member_model = apps.get_model("wirgarten", "Member")

    member_model.objects.update(has_received_membership_started_mail=True)


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0119_member_has_received_membership_started_mail"),
    ]

    operations = [
        migrations.RunPython(set_default_has_received_membership_started_mail)
    ]
