# Generated by Django 6.0.5 on 2026-07-03 09:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0120_auto_20260708_1221"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="is_association_membership",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 7, 3, 9, 56, 30, 332082, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
