# Generated by Django 6.0.5 on 2026-07-08 18:51

from django.db import migrations
from tapir_mail.models import ReleaseStatus


def update_mail_token_coop_entry_date(apps, schema):
    email_configuration_version_class = apps.get_model(
        "tapir_mail", "EmailConfigurationVersion"
    )

    for email_configuration_version in email_configuration_version_class.objects.filter(
        status__in=[ReleaseStatus.RELEASED, ReleaseStatus.DRAFT]
    ):
        content = email_configuration_version.content
        if "{{Empfänger.Beitrittsdatum}}" not in content:
            continue

        content = content.replace(
            "{{Empfänger.Beitrittsdatum}}",
            "{{Empfänger (extra).Mitglied - Beitrittsdatum}}",
        )
        email_configuration_version.content = content
        email_configuration_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0121_remove_waitinglistentry_association_membership_type"),
    ]

    operations = [
        migrations.RunPython(update_mail_token_coop_entry_date),
    ]
