# Generated by Django 6.0.5 on 2026-07-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0007_associationmembership_cancellation_ts"),
        ("wirgarten", "0121_remove_producttype_is_association_membership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="association_membership_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="associations.associationmembershiptype",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wirgarten.member",
            ),
        ),
    ]
