# Generated by Django 6.0.5 on 2026-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0122_waitinglistentry_association_membership_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitinglistentry",
            name="association_membership_type",
        ),
    ]
