# Generated by Django 6.0.5 on 2026-07-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0124_auto_20260708_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pickup_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
