# Generated by Django 6.0.5 on 2026-07-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0125_locationroute_pickuplocation_location_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocation",
            name="route_info",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Driver/Route info"
            ),
        ),
    ]
