# Generated by Django 6.0.5 on 2026-07-23 11:41

from django.db import migrations


def migrate_additional_product_restriction(apps, schema_editor):
    tapir_parameter_model = apps.get_model("configuration", "TapirParameter")

    additional_products_parameter = tapir_parameter_model.objects.filter(
        key="wirgarten.subscriptions.additional_product_allowed_without_base_product"
    ).first()
    if (
        additional_products_parameter is None
        or additional_products_parameter.value == "True"
    ):
        return

    base_product_parameter = tapir_parameter_model.objects.filter(
        key="wirgarten.coop.base_product_type"
    ).first()
    if base_product_parameter is None:
        return

    product_type_model = apps.get_model("wirgarten", "ProductType")
    product_type = product_type_model.objects.filter(
        id=base_product_parameter.value
    ).first()
    if product_type is None or product_type.must_be_subscribed_to:
        return

    product_type.must_be_subscribed_to = True
    product_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0126_pickuplocation_route_info"),
    ]

    operations = [
        migrations.RunPython(migrate_additional_product_restriction),
    ]
