# Generated by Django 6.0.7 on 2026-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0128_payment_pickup_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hidden_in_bestell_wizard",
            field=models.BooleanField(default=False),
        ),
    ]
