# Generated by Django 6.0.7 on 2026-08-31 16:51

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0129_product_hidden_in_bestell_wizard"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupLocationGrowingPeriod",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "growing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_location_links",
                        to="wirgarten.growingperiod",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growing_period_links",
                        to="wirgarten.pickuplocation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pickup_location", "growing_period"),
                        name="unique_pickup_location_growing_period",
                    )
                ],
            },
        ),
    ]
