# Generated by Django 6.0.7 on 2026-08-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0129_product_hidden_in_bestell_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocation",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Available from"
            ),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Available until"
            ),
        ),
    ]
