# Generated by Django 6.0.7 on 2026-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0129_product_hidden_in_bestell_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocation",
            name="show_details_in_basket_totals_export",
            field=models.BooleanField(
                default=False,
                verbose_name="Im Gesamtkistenanzahls-Zettel Details anzeigen",
            ),
        ),
    ]
