# Generated by Django 6.0.7 on 2026-09-15 21:13

from django.db import migrations
from tapir_mail.models import ReleaseStatus


def rename_trial_cancellation_merge_tag(apps, schema):
    # The transactional trigger "Kündigung im Probemonat" was renamed to "Kündigung in der Probezeit"

    email_configuration_version_class = apps.get_model(
        "tapir_mail", "EmailConfigurationVersion"
    )

    for email_configuration_version in email_configuration_version_class.objects.filter(
        status__in=[ReleaseStatus.RELEASED, ReleaseStatus.DRAFT]
    ):
        content = email_configuration_version.content
        content = content.replace(
            "Kündigung im Probemonat.", "Kündigung in der Probezeit."
        )
        email_configuration_version.content = content
        email_configuration_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tapir_mail", "0047_auto_20260410_1331"),
        ("wirgarten", "0130_pickuplocation_show_details_in_basket_totals_export"),
    ]

    operations = [
        migrations.RunPython(rename_trial_cancellation_merge_tag),
    ]
