# Generated by Django 6.0.7 on 2026-09-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0100_producttype_is_bread"),
        ("wirgarten", "0130_pickuplocation_show_details_in_basket_totals_export"),
    ]

    operations = []
