# Generated by Django 6.0.7 on 2026-09-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0131_merge_20260911_1618"),
        ("wirgarten", "0134_alter_pickuplocation_info_route_info"),
    ]

    operations = []
