# Generated by Django 6.0.7 on 2026-09-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0134_rename_order_revoked_trigger_merge_tag"),
        ("wirgarten", "0135_merge_20260925_1310"),
    ]

    operations = []
