# Generated by Django 6.0.7 on 2026-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0134_rename_order_revoked_trigger_merge_tag"),
        ("wirgarten", "0135_merge_20260925_1310"),
        ("wirgarten", "0136_merge_20260929_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocation",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Leer = ab sofort verfügbar. Neuanlagen nur an einem Montag möglich.",
                null=True,
                verbose_name="Available from",
            ),
        ),
        migrations.AddField(
            model_name="pickuplocation",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Leer = dauerhaft verfügbar. Schließen nur an einem Sonntag möglich.",
                null=True,
                verbose_name="Available until",
            ),
        ),
    ]
