# Generated by Django 5.2.1 on 2025-10-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0001_initial"),
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoopSharesPurchasedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("coop_share_transaction", models.CharField(max_length=1024)),
            ],
            bases=("log.logentry",),
        ),
    ]
