# Generated by Django 6.0.1 on 2026-04-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0003_coopsharescancelledlogentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coopsharescancelledlogentry",
            old_name="shares_valid_at",
            new_name="cancellation_valid_at",
        ),
    ]
