/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbhollisteEntry
 */
export interface AbhollisteEntry {
    /**
     * 
     * @type {string}
     * @memberof AbhollisteEntry
     */
    memberId: string;
    /**
     * 
     * @type {string}
     * @memberof AbhollisteEntry
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof AbhollisteEntry
     */
    totalBreads: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof AbhollisteEntry
     */
    breadCounts: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof AbhollisteEntry
     */
    breadPreferred: { [key: string]: boolean; };
    /**
     * 
     * @type {Array<{ [key: string]: string | null; }>}
     * @memberof AbhollisteEntry
     */
    breads: Array<{ [key: string]: string | null; }>;
}

/**
 * Check if a given object implements the AbhollisteEntry interface.
 */
export function instanceOfAbhollisteEntry(value: object): value is AbhollisteEntry {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('totalBreads' in value) || value['totalBreads'] === undefined) return false;
    if (!('breadCounts' in value) || value['breadCounts'] === undefined) return false;
    if (!('breadPreferred' in value) || value['breadPreferred'] === undefined) return false;
    if (!('breads' in value) || value['breads'] === undefined) return false;
    return true;
}

export function AbhollisteEntryFromJSON(json: any): AbhollisteEntry {
    return AbhollisteEntryFromJSONTyped(json, false);
}

export function AbhollisteEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbhollisteEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'],
        'displayName': json['display_name'],
        'totalBreads': json['total_breads'],
        'breadCounts': json['bread_counts'],
        'breadPreferred': json['bread_preferred'],
        'breads': json['breads'],
    };
}

  export function AbhollisteEntryToJSON(json: any): AbhollisteEntry {
      return AbhollisteEntryToJSONTyped(json, false);
  }

  export function AbhollisteEntryToJSONTyped(value?: AbhollisteEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
        'display_name': value['displayName'],
        'total_breads': value['totalBreads'],
        'bread_counts': value['breadCounts'],
        'bread_preferred': value['breadPreferred'],
        'breads': value['breads'],
    };
}

