/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `directly_chosen` - directly_chosen
 * * `no_favorites` - no_favorites
 * * `got_favorite` - got_favorite
 * * `no_match` - no_match
 * @export
 */
export const AssignmentLogEntryStatusEnum = {
    DirectlyChosen: 'directly_chosen',
    NoFavorites: 'no_favorites',
    GotFavorite: 'got_favorite',
    NoMatch: 'no_match'
} as const;
export type AssignmentLogEntryStatusEnum = typeof AssignmentLogEntryStatusEnum[keyof typeof AssignmentLogEntryStatusEnum];


export function instanceOfAssignmentLogEntryStatusEnum(value: any): boolean {
    for (const key in AssignmentLogEntryStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(AssignmentLogEntryStatusEnum, key)) {
            if (AssignmentLogEntryStatusEnum[key as keyof typeof AssignmentLogEntryStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssignmentLogEntryStatusEnumFromJSON(json: any): AssignmentLogEntryStatusEnum {
    return AssignmentLogEntryStatusEnumFromJSONTyped(json, false);
}

export function AssignmentLogEntryStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentLogEntryStatusEnum {
    return json as AssignmentLogEntryStatusEnum;
}

export function AssignmentLogEntryStatusEnumToJSON(value?: AssignmentLogEntryStatusEnum | null): any {
    return value as any;
}

export function AssignmentLogEntryStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AssignmentLogEntryStatusEnum {
    return value as AssignmentLogEntryStatusEnum;
}

