/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssociationMembershipTypeRequest
 */
export interface AssociationMembershipTypeRequest {
  /**
   *
   * @type {string}
   * @memberof AssociationMembershipTypeRequest
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof AssociationMembershipTypeRequest
   */
  name: string;
  /**
   *
   * @type {boolean}
   * @memberof AssociationMembershipTypeRequest
   */
  deleted?: boolean;
}

/**
 * Check if a given object implements the AssociationMembershipTypeRequest interface.
 */
export function instanceOfAssociationMembershipTypeRequest(
  value: object,
): value is AssociationMembershipTypeRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function AssociationMembershipTypeRequestFromJSON(
  json: any,
): AssociationMembershipTypeRequest {
  return AssociationMembershipTypeRequestFromJSONTyped(json, false);
}

export function AssociationMembershipTypeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssociationMembershipTypeRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"],
    deleted: json["deleted"] == null ? undefined : json["deleted"],
  };
}

export function AssociationMembershipTypeRequestToJSON(
  json: any,
): AssociationMembershipTypeRequest {
  return AssociationMembershipTypeRequestToJSONTyped(json, false);
}

export function AssociationMembershipTypeRequestToJSONTyped(
  value?: AssociationMembershipTypeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    deleted: value["deleted"],
  };
}
