/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BreadList } from './BreadList';
import {
    BreadListFromJSON,
    BreadListFromJSONTyped,
    BreadListToJSON,
    BreadListToJSONTyped,
} from './BreadList';

/**
 * 
 * @export
 * @interface AvailableBreadsForDeliveryListResponse
 */
export interface AvailableBreadsForDeliveryListResponse {
    /**
     * 
     * @type {number}
     * @memberof AvailableBreadsForDeliveryListResponse
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof AvailableBreadsForDeliveryListResponse
     */
    deliveryWeek: number;
    /**
     * 
     * @type {number}
     * @memberof AvailableBreadsForDeliveryListResponse
     */
    deliveryDay: number;
    /**
     * 
     * @type {Array<BreadList>}
     * @memberof AvailableBreadsForDeliveryListResponse
     */
    breads: Array<BreadList>;
}

/**
 * Check if a given object implements the AvailableBreadsForDeliveryListResponse interface.
 */
export function instanceOfAvailableBreadsForDeliveryListResponse(value: object): value is AvailableBreadsForDeliveryListResponse {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('deliveryWeek' in value) || value['deliveryWeek'] === undefined) return false;
    if (!('deliveryDay' in value) || value['deliveryDay'] === undefined) return false;
    if (!('breads' in value) || value['breads'] === undefined) return false;
    return true;
}

export function AvailableBreadsForDeliveryListResponseFromJSON(json: any): AvailableBreadsForDeliveryListResponse {
    return AvailableBreadsForDeliveryListResponseFromJSONTyped(json, false);
}

export function AvailableBreadsForDeliveryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableBreadsForDeliveryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'deliveryWeek': json['delivery_week'],
        'deliveryDay': json['delivery_day'],
        'breads': ((json['breads'] as Array<any>).map(BreadListFromJSON)),
    };
}

  export function AvailableBreadsForDeliveryListResponseToJSON(json: any): AvailableBreadsForDeliveryListResponse {
      return AvailableBreadsForDeliveryListResponseToJSONTyped(json, false);
  }

  export function AvailableBreadsForDeliveryListResponseToJSONTyped(value?: AvailableBreadsForDeliveryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'delivery_week': value['deliveryWeek'],
        'delivery_day': value['deliveryDay'],
        'breads': ((value['breads'] as Array<any>).map(BreadListToJSON)),
    };
}

