/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner } from './BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner';
import {
    BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerFromJSON,
    BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerFromJSONTyped,
    BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerToJSON,
    BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerToJSONTyped,
} from './BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner';

/**
 * 
 * @export
 * @interface BakeryBreadCapacityPickupStationBulkUpdateCreateRequest
 */
export interface BakeryBreadCapacityPickupStationBulkUpdateCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof BakeryBreadCapacityPickupStationBulkUpdateCreateRequest
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof BakeryBreadCapacityPickupStationBulkUpdateCreateRequest
     */
    week: number;
    /**
     * 
     * @type {Array<BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner>}
     * @memberof BakeryBreadCapacityPickupStationBulkUpdateCreateRequest
     */
    updates: Array<BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner>;
}

/**
 * Check if a given object implements the BakeryBreadCapacityPickupStationBulkUpdateCreateRequest interface.
 */
export function instanceOfBakeryBreadCapacityPickupStationBulkUpdateCreateRequest(value: object): value is BakeryBreadCapacityPickupStationBulkUpdateCreateRequest {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('week' in value) || value['week'] === undefined) return false;
    if (!('updates' in value) || value['updates'] === undefined) return false;
    return true;
}

export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestFromJSON(json: any): BakeryBreadCapacityPickupStationBulkUpdateCreateRequest {
    return BakeryBreadCapacityPickupStationBulkUpdateCreateRequestFromJSONTyped(json, false);
}

export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BakeryBreadCapacityPickupStationBulkUpdateCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'week': json['week'],
        'updates': ((json['updates'] as Array<any>).map(BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerFromJSON)),
    };
}

  export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestToJSON(json: any): BakeryBreadCapacityPickupStationBulkUpdateCreateRequest {
      return BakeryBreadCapacityPickupStationBulkUpdateCreateRequestToJSONTyped(json, false);
  }

  export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestToJSONTyped(value?: BakeryBreadCapacityPickupStationBulkUpdateCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'week': value['week'],
        'updates': ((value['updates'] as Array<any>).map(BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerToJSON)),
    };
}

