/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner
 */
export interface BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner {
    /**
     * 
     * @type {number}
     * @memberof BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner
     */
    pickupStationDay?: number;
    /**
     * 
     * @type {string}
     * @memberof BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner
     */
    bread?: string;
    /**
     * 
     * @type {number}
     * @memberof BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner
     */
    capacity?: number | null;
}

/**
 * Check if a given object implements the BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner interface.
 */
export function instanceOfBakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner(value: object): value is BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner {
    return true;
}

export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerFromJSON(json: any): BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner {
    return BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerFromJSONTyped(json, false);
}

export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'pickupStationDay': json['pickup_station_day'] == null ? undefined : json['pickup_station_day'],
        'bread': json['bread'] == null ? undefined : json['bread'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
    };
}

  export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerToJSON(json: any): BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner {
      return BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerToJSONTyped(json, false);
  }

  export function BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInnerToJSONTyped(value?: BakeryBreadCapacityPickupStationBulkUpdateCreateRequestUpdatesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pickup_station_day': value['pickupStationDay'],
        'bread': value['bread'],
        'capacity': value['capacity'],
    };
}

