/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInner } from './BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInner';
import {
    BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInnerFromJSON,
    BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInnerFromJSONTyped,
    BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInnerToJSON,
    BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInnerToJSONTyped,
} from './BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInner';

/**
 * 
 * @export
 * @interface BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest
 */
export interface BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest
     */
    week: number;
    /**
     * 
     * @type {Array<BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInner>}
     * @memberof BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest
     */
    updates: Array<BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInner>;
}

/**
 * Check if a given object implements the BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest interface.
 */
export function instanceOfBakeryBreadCapacityPickupLocationBulkUpdateCreateRequest(value: object): value is BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('week' in value) || value['week'] === undefined) return false;
    if (!('updates' in value) || value['updates'] === undefined) return false;
    return true;
}

export function BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestFromJSON(json: any): BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest {
    return BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestFromJSONTyped(json, false);
}

export function BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'week': json['week'],
        'updates': ((json['updates'] as Array<any>).map(BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInnerFromJSON)),
    };
}

  export function BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestToJSON(json: any): BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest {
      return BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestToJSONTyped(json, false);
  }

  export function BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestToJSONTyped(value?: BakeryBreadCapacityPickupLocationBulkUpdateCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'week': value['week'],
        'updates': ((value['updates'] as Array<any>).map(BakeryBreadCapacityPickupLocationBulkUpdateCreateRequestUpdatesInnerToJSON)),
    };
}

