/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BestellWizardStrings
 */
export interface BestellWizardStrings {
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1aTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1aText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1bTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1bText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step2Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step2Text: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step3Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step3Text: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step4dTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step4dText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step5aTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step5aText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6aTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6aText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6bTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6bText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6cCheckboxStatute: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6cTextStatute: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step6cCheckboxCommitment: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step8Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step9Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step9PaymentRhythmModalText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step10Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step11Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step12Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step13Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step13Text: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step14Title: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step14Text: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    privacyPolicyUrl: string;
}

/**
 * Check if a given object implements the BestellWizardStrings interface.
 */
export function instanceOfBestellWizardStrings(value: object): value is BestellWizardStrings {
    if (!('step1aTitle' in value) || value['step1aTitle'] === undefined) return false;
    if (!('step1aText' in value) || value['step1aText'] === undefined) return false;
    if (!('step1bTitle' in value) || value['step1bTitle'] === undefined) return false;
    if (!('step1bText' in value) || value['step1bText'] === undefined) return false;
    if (!('step2Title' in value) || value['step2Title'] === undefined) return false;
    if (!('step2Text' in value) || value['step2Text'] === undefined) return false;
    if (!('step3Title' in value) || value['step3Title'] === undefined) return false;
    if (!('step3Text' in value) || value['step3Text'] === undefined) return false;
    if (!('step4dTitle' in value) || value['step4dTitle'] === undefined) return false;
    if (!('step4dText' in value) || value['step4dText'] === undefined) return false;
    if (!('step5aTitle' in value) || value['step5aTitle'] === undefined) return false;
    if (!('step5aText' in value) || value['step5aText'] === undefined) return false;
    if (!('step6aTitle' in value) || value['step6aTitle'] === undefined) return false;
    if (!('step6aText' in value) || value['step6aText'] === undefined) return false;
    if (!('step6bTitle' in value) || value['step6bTitle'] === undefined) return false;
    if (!('step6bText' in value) || value['step6bText'] === undefined) return false;
    if (!('step6cCheckboxStatute' in value) || value['step6cCheckboxStatute'] === undefined) return false;
    if (!('step6cTextStatute' in value) || value['step6cTextStatute'] === undefined) return false;
    if (!('step6cCheckboxCommitment' in value) || value['step6cCheckboxCommitment'] === undefined) return false;
    if (!('step8Title' in value) || value['step8Title'] === undefined) return false;
    if (!('step9Title' in value) || value['step9Title'] === undefined) return false;
    if (!('step9PaymentRhythmModalText' in value) || value['step9PaymentRhythmModalText'] === undefined) return false;
    if (!('step10Title' in value) || value['step10Title'] === undefined) return false;
    if (!('step11Title' in value) || value['step11Title'] === undefined) return false;
    if (!('step12Title' in value) || value['step12Title'] === undefined) return false;
    if (!('step13Title' in value) || value['step13Title'] === undefined) return false;
    if (!('step13Text' in value) || value['step13Text'] === undefined) return false;
    if (!('step14Title' in value) || value['step14Title'] === undefined) return false;
    if (!('step14Text' in value) || value['step14Text'] === undefined) return false;
    if (!('privacyPolicyUrl' in value) || value['privacyPolicyUrl'] === undefined) return false;
    return true;
}

export function BestellWizardStringsFromJSON(json: any): BestellWizardStrings {
    return BestellWizardStringsFromJSONTyped(json, false);
}

export function BestellWizardStringsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestellWizardStrings {
    if (json == null) {
        return json;
    }
    return {
        
        'step1aTitle': json['step1a_title'],
        'step1aText': json['step1a_text'],
        'step1bTitle': json['step1b_title'],
        'step1bText': json['step1b_text'],
        'step2Title': json['step2_title'],
        'step2Text': json['step2_text'],
        'step3Title': json['step3_title'],
        'step3Text': json['step3_text'],
        'step4dTitle': json['step4d_title'],
        'step4dText': json['step4d_text'],
        'step5aTitle': json['step5a_title'],
        'step5aText': json['step5a_text'],
        'step6aTitle': json['step6a_title'],
        'step6aText': json['step6a_text'],
        'step6bTitle': json['step6b_title'],
        'step6bText': json['step6b_text'],
        'step6cCheckboxStatute': json['step6c_checkbox_statute'],
        'step6cTextStatute': json['step6c_text_statute'],
        'step6cCheckboxCommitment': json['step6c_checkbox_commitment'],
        'step8Title': json['step8_title'],
        'step9Title': json['step9_title'],
        'step9PaymentRhythmModalText': json['step9_payment_rhythm_modal_text'],
        'step10Title': json['step10_title'],
        'step11Title': json['step11_title'],
        'step12Title': json['step12_title'],
        'step13Title': json['step13_title'],
        'step13Text': json['step13_text'],
        'step14Title': json['step14_title'],
        'step14Text': json['step14_text'],
        'privacyPolicyUrl': json['privacy_policy_url'],
    };
}

  export function BestellWizardStringsToJSON(json: any): BestellWizardStrings {
      return BestellWizardStringsToJSONTyped(json, false);
  }

  export function BestellWizardStringsToJSONTyped(value?: BestellWizardStrings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step1a_title': value['step1aTitle'],
        'step1a_text': value['step1aText'],
        'step1b_title': value['step1bTitle'],
        'step1b_text': value['step1bText'],
        'step2_title': value['step2Title'],
        'step2_text': value['step2Text'],
        'step3_title': value['step3Title'],
        'step3_text': value['step3Text'],
        'step4d_title': value['step4dTitle'],
        'step4d_text': value['step4dText'],
        'step5a_title': value['step5aTitle'],
        'step5a_text': value['step5aText'],
        'step6a_title': value['step6aTitle'],
        'step6a_text': value['step6aText'],
        'step6b_title': value['step6bTitle'],
        'step6b_text': value['step6bText'],
        'step6c_checkbox_statute': value['step6cCheckboxStatute'],
        'step6c_text_statute': value['step6cTextStatute'],
        'step6c_checkbox_commitment': value['step6cCheckboxCommitment'],
        'step8_title': value['step8Title'],
        'step9_title': value['step9Title'],
        'step9_payment_rhythm_modal_text': value['step9PaymentRhythmModalText'],
        'step10_title': value['step10Title'],
        'step11_title': value['step11Title'],
        'step12_title': value['step12Title'],
        'step13_title': value['step13Title'],
        'step13_text': value['step13Text'],
        'step14_title': value['step14Title'],
        'step14_text': value['step14Text'],
        'privacy_policy_url': value['privacyPolicyUrl'],
    };
}

