/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BestellWizardCapacityCheckResponse
 */
export interface BestellWizardCapacityCheckResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof BestellWizardCapacityCheckResponse
     */
    idsOfProductsOverCapacity: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BestellWizardCapacityCheckResponse
     */
    idsOfProductTypesOverCapacity: Array<string>;
}

/**
 * Check if a given object implements the BestellWizardCapacityCheckResponse interface.
 */
export function instanceOfBestellWizardCapacityCheckResponse(value: object): value is BestellWizardCapacityCheckResponse {
    if (!('idsOfProductsOverCapacity' in value) || value['idsOfProductsOverCapacity'] === undefined) return false;
    if (!('idsOfProductTypesOverCapacity' in value) || value['idsOfProductTypesOverCapacity'] === undefined) return false;
    return true;
}

export function BestellWizardCapacityCheckResponseFromJSON(json: any): BestellWizardCapacityCheckResponse {
    return BestellWizardCapacityCheckResponseFromJSONTyped(json, false);
}

export function BestellWizardCapacityCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestellWizardCapacityCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'idsOfProductsOverCapacity': json['ids_of_products_over_capacity'],
        'idsOfProductTypesOverCapacity': json['ids_of_product_types_over_capacity'],
    };
}

  export function BestellWizardCapacityCheckResponseToJSON(json: any): BestellWizardCapacityCheckResponse {
      return BestellWizardCapacityCheckResponseToJSONTyped(json, false);
  }

  export function BestellWizardCapacityCheckResponseToJSONTyped(value?: BestellWizardCapacityCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids_of_products_over_capacity': value['idsOfProductsOverCapacity'],
        'ids_of_product_types_over_capacity': value['idsOfProductTypesOverCapacity'],
    };
}

