/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonalDataRequest } from './PersonalDataRequest';
import {
    PersonalDataRequestFromJSON,
    PersonalDataRequestFromJSONTyped,
    PersonalDataRequestToJSON,
    PersonalDataRequestToJSONTyped,
} from './PersonalDataRequest';

/**
 * 
 * @export
 * @interface BestellWizardConfirmOrderRequestRequest
 */
export interface BestellWizardConfirmOrderRequestRequest {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    shoppingCartOrder: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    shoppingCartWaitingList: { [key: string]: number; };
    /**
     * 
     * @type {PersonalDataRequest}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    personalData: PersonalDataRequest;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    sepaAllowed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    contractAccepted: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    statuteAccepted: boolean;
    /**
     * 
     * @type {number}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    numberOfCoopShares: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    pickupLocationIds: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    studentStatusEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    paymentRhythm: string;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    becomeMemberNow: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    privacyPolicyRead: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    cancellationPolicyRead: boolean;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    growingPeriodId: string;
    /**
     * 
     * @type {number}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    solidarityContribution: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BestellWizardConfirmOrderRequestRequest
     */
    distributionChannels: Array<string>;
}

/**
 * Check if a given object implements the BestellWizardConfirmOrderRequestRequest interface.
 */
export function instanceOfBestellWizardConfirmOrderRequestRequest(value: object): value is BestellWizardConfirmOrderRequestRequest {
    if (!('shoppingCartOrder' in value) || value['shoppingCartOrder'] === undefined) return false;
    if (!('shoppingCartWaitingList' in value) || value['shoppingCartWaitingList'] === undefined) return false;
    if (!('personalData' in value) || value['personalData'] === undefined) return false;
    if (!('sepaAllowed' in value) || value['sepaAllowed'] === undefined) return false;
    if (!('contractAccepted' in value) || value['contractAccepted'] === undefined) return false;
    if (!('statuteAccepted' in value) || value['statuteAccepted'] === undefined) return false;
    if (!('numberOfCoopShares' in value) || value['numberOfCoopShares'] === undefined) return false;
    if (!('pickupLocationIds' in value) || value['pickupLocationIds'] === undefined) return false;
    if (!('studentStatusEnabled' in value) || value['studentStatusEnabled'] === undefined) return false;
    if (!('paymentRhythm' in value) || value['paymentRhythm'] === undefined) return false;
    if (!('becomeMemberNow' in value) || value['becomeMemberNow'] === undefined) return false;
    if (!('privacyPolicyRead' in value) || value['privacyPolicyRead'] === undefined) return false;
    if (!('cancellationPolicyRead' in value) || value['cancellationPolicyRead'] === undefined) return false;
    if (!('growingPeriodId' in value) || value['growingPeriodId'] === undefined) return false;
    if (!('solidarityContribution' in value) || value['solidarityContribution'] === undefined) return false;
    if (!('distributionChannels' in value) || value['distributionChannels'] === undefined) return false;
    return true;
}

export function BestellWizardConfirmOrderRequestRequestFromJSON(json: any): BestellWizardConfirmOrderRequestRequest {
    return BestellWizardConfirmOrderRequestRequestFromJSONTyped(json, false);
}

export function BestellWizardConfirmOrderRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestellWizardConfirmOrderRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'shoppingCartOrder': json['shopping_cart_order'],
        'shoppingCartWaitingList': json['shopping_cart_waiting_list'],
        'personalData': PersonalDataRequestFromJSON(json['personal_data']),
        'sepaAllowed': json['sepa_allowed'],
        'contractAccepted': json['contract_accepted'],
        'statuteAccepted': json['statute_accepted'],
        'numberOfCoopShares': json['number_of_coop_shares'],
        'pickupLocationIds': json['pickup_location_ids'],
        'studentStatusEnabled': json['student_status_enabled'],
        'paymentRhythm': json['payment_rhythm'],
        'becomeMemberNow': json['become_member_now'],
        'privacyPolicyRead': json['privacy_policy_read'],
        'cancellationPolicyRead': json['cancellation_policy_read'],
        'growingPeriodId': json['growing_period_id'],
        'solidarityContribution': json['solidarity_contribution'],
        'distributionChannels': json['distribution_channels'],
    };
}

  export function BestellWizardConfirmOrderRequestRequestToJSON(json: any): BestellWizardConfirmOrderRequestRequest {
      return BestellWizardConfirmOrderRequestRequestToJSONTyped(json, false);
  }

  export function BestellWizardConfirmOrderRequestRequestToJSONTyped(value?: BestellWizardConfirmOrderRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shopping_cart_order': value['shoppingCartOrder'],
        'shopping_cart_waiting_list': value['shoppingCartWaitingList'],
        'personal_data': PersonalDataRequestToJSON(value['personalData']),
        'sepa_allowed': value['sepaAllowed'],
        'contract_accepted': value['contractAccepted'],
        'statute_accepted': value['statuteAccepted'],
        'number_of_coop_shares': value['numberOfCoopShares'],
        'pickup_location_ids': value['pickupLocationIds'],
        'student_status_enabled': value['studentStatusEnabled'],
        'payment_rhythm': value['paymentRhythm'],
        'become_member_now': value['becomeMemberNow'],
        'privacy_policy_read': value['privacyPolicyRead'],
        'cancellation_policy_read': value['cancellationPolicyRead'],
        'growing_period_id': value['growingPeriodId'],
        'solidarity_contribution': value['solidarityContribution'],
        'distribution_channels': value['distributionChannels'],
    };
}

