/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BestellWizardStrings
 */
export interface BestellWizardStrings {
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1aTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1aText: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1bTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BestellWizardStrings
     */
    step1bText: string;
}

/**
 * Check if a given object implements the BestellWizardStrings interface.
 */
export function instanceOfBestellWizardStrings(value: object): value is BestellWizardStrings {
    if (!('step1aTitle' in value) || value['step1aTitle'] === undefined) return false;
    if (!('step1aText' in value) || value['step1aText'] === undefined) return false;
    if (!('step1bTitle' in value) || value['step1bTitle'] === undefined) return false;
    if (!('step1bText' in value) || value['step1bText'] === undefined) return false;
    return true;
}

export function BestellWizardStringsFromJSON(json: any): BestellWizardStrings {
    return BestellWizardStringsFromJSONTyped(json, false);
}

export function BestellWizardStringsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestellWizardStrings {
    if (json == null) {
        return json;
    }
    return {
        
        'step1aTitle': json['step1a_title'],
        'step1aText': json['step1a_text'],
        'step1bTitle': json['step1b_title'],
        'step1bText': json['step1b_text'],
    };
}

  export function BestellWizardStringsToJSON(json: any): BestellWizardStrings {
      return BestellWizardStringsToJSONTyped(json, false);
  }

  export function BestellWizardStringsToJSONTyped(value?: BestellWizardStrings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step1a_title': value['step1aTitle'],
        'step1a_text': value['step1aText'],
        'step1b_title': value['step1bTitle'],
        'step1b_text': value['step1bText'],
    };
}

