/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BestellWizardDeliveryDatesForOrderResponse
 */
export interface BestellWizardDeliveryDatesForOrderResponse {
  /**
   *
   * @type {{ [key: string]: { [key: string]: Date; }; }}
   * @memberof BestellWizardDeliveryDatesForOrderResponse
   */
  deliveryDateByPickupLocationIdAndProductTypeId: {
    [key: string]: { [key: string]: Date };
  };
}

/**
 * Check if a given object implements the BestellWizardDeliveryDatesForOrderResponse interface.
 */
export function instanceOfBestellWizardDeliveryDatesForOrderResponse(
  value: object,
): value is BestellWizardDeliveryDatesForOrderResponse {
  if (
    !("deliveryDateByPickupLocationIdAndProductTypeId" in value) ||
    value["deliveryDateByPickupLocationIdAndProductTypeId"] === undefined
  )
    return false;
  return true;
}

export function BestellWizardDeliveryDatesForOrderResponseFromJSON(
  json: any,
): BestellWizardDeliveryDatesForOrderResponse {
  return BestellWizardDeliveryDatesForOrderResponseFromJSONTyped(json, false);
}

export function BestellWizardDeliveryDatesForOrderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BestellWizardDeliveryDatesForOrderResponse {
  if (json == null) {
    return json;
  }
  return {
    deliveryDateByPickupLocationIdAndProductTypeId:
      json["delivery_date_by_pickup_location_id_and_product_type_id"],
  };
}

export function BestellWizardDeliveryDatesForOrderResponseToJSON(
  json: any,
): BestellWizardDeliveryDatesForOrderResponse {
  return BestellWizardDeliveryDatesForOrderResponseToJSONTyped(json, false);
}

export function BestellWizardDeliveryDatesForOrderResponseToJSONTyped(
  value?: BestellWizardDeliveryDatesForOrderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    delivery_date_by_pickup_location_id_and_product_type_id:
      value["deliveryDateByPickupLocationIdAndProductTypeId"],
  };
}
