/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BreadDelivery
 */
export interface BreadDelivery {
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly id: string;
  /**
   *
   * @type {number}
   * @memberof BreadDelivery
   */
  readonly year: number;
  /**
   *
   * @type {number}
   * @memberof BreadDelivery
   */
  readonly deliveryWeek: number;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly subscription: string;
  /**
   *
   * @type {number}
   * @memberof BreadDelivery
   */
  readonly slotNumber: number;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly pickupLocation: string | null;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  bread?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof BreadDelivery
   */
  readonly jokerTaken: boolean;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly breadName: string;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly pickupLocationName: string | null;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly pickupLocationStreet: string | null;
  /**
   *
   * @type {string}
   * @memberof BreadDelivery
   */
  readonly pickupLocationCity: string | null;
  /**
   *
   * @type {number}
   * @memberof BreadDelivery
   */
  readonly deliveryDay: number | null;
  /**
   *
   * @type {Date}
   * @memberof BreadDelivery
   */
  readonly choosingDeadline: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof BreadDelivery
   */
  readonly canStillChoose: boolean;
}

/**
 * Check if a given object implements the BreadDelivery interface.
 */
export function instanceOfBreadDelivery(value: object): value is BreadDelivery {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("year" in value) || value["year"] === undefined) return false;
  if (!("deliveryWeek" in value) || value["deliveryWeek"] === undefined)
    return false;
  if (!("subscription" in value) || value["subscription"] === undefined)
    return false;
  if (!("slotNumber" in value) || value["slotNumber"] === undefined)
    return false;
  if (!("pickupLocation" in value) || value["pickupLocation"] === undefined)
    return false;
  if (!("jokerTaken" in value) || value["jokerTaken"] === undefined)
    return false;
  if (!("breadName" in value) || value["breadName"] === undefined) return false;
  if (
    !("pickupLocationName" in value) ||
    value["pickupLocationName"] === undefined
  )
    return false;
  if (
    !("pickupLocationStreet" in value) ||
    value["pickupLocationStreet"] === undefined
  )
    return false;
  if (
    !("pickupLocationCity" in value) ||
    value["pickupLocationCity"] === undefined
  )
    return false;
  if (!("deliveryDay" in value) || value["deliveryDay"] === undefined)
    return false;
  if (!("choosingDeadline" in value) || value["choosingDeadline"] === undefined)
    return false;
  if (!("canStillChoose" in value) || value["canStillChoose"] === undefined)
    return false;
  return true;
}

export function BreadDeliveryFromJSON(json: any): BreadDelivery {
  return BreadDeliveryFromJSONTyped(json, false);
}

export function BreadDeliveryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BreadDelivery {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    year: json["year"],
    deliveryWeek: json["delivery_week"],
    subscription: json["subscription"],
    slotNumber: json["slot_number"],
    pickupLocation: json["pickup_location"],
    bread: json["bread"] == null ? undefined : json["bread"],
    jokerTaken: json["joker_taken"],
    breadName: json["bread_name"],
    pickupLocationName: json["pickup_location_name"],
    pickupLocationStreet: json["pickup_location_street"],
    pickupLocationCity: json["pickup_location_city"],
    deliveryDay: json["delivery_day"],
    choosingDeadline:
      json["choosing_deadline"] == null
        ? null
        : new Date(json["choosing_deadline"]),
    canStillChoose: json["can_still_choose"],
  };
}

export function BreadDeliveryToJSON(json: any): BreadDelivery {
  return BreadDeliveryToJSONTyped(json, false);
}

export function BreadDeliveryToJSONTyped(
  value?: Omit<
    BreadDelivery,
    | "id"
    | "year"
    | "delivery_week"
    | "subscription"
    | "slot_number"
    | "pickup_location"
    | "joker_taken"
    | "bread_name"
    | "pickup_location_name"
    | "pickup_location_street"
    | "pickup_location_city"
    | "delivery_day"
    | "choosing_deadline"
    | "can_still_choose"
  > | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    bread: value["bread"],
  };
}
