/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BreadCapacityPickupLocation
 */
export interface BreadCapacityPickupLocation {
    /**
     * 
     * @type {string}
     * @memberof BreadCapacityPickupLocation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BreadCapacityPickupLocation
     */
    readonly pickupLocationName: string;
    /**
     * 
     * @type {number}
     * @memberof BreadCapacityPickupLocation
     */
    readonly deliveryDay: number;
    /**
     * 
     * @type {string}
     * @memberof BreadCapacityPickupLocation
     */
    readonly breadName: string;
    /**
     * Year for which this capacity applies
     * @type {number}
     * @memberof BreadCapacityPickupLocation
     */
    year: number;
    /**
     * Delivery week number (1-53)
     * @type {number}
     * @memberof BreadCapacityPickupLocation
     */
    deliveryWeek: number;
    /**
     * Maximum number of breads of this label that can be delivered to this pickup location on this delivery day
     * @type {number}
     * @memberof BreadCapacityPickupLocation
     */
    capacity: number;
    /**
     * The pickup location this capacity applies to (redundant but useful for queries)
     * @type {string}
     * @memberof BreadCapacityPickupLocation
     */
    pickupLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BreadCapacityPickupLocation
     */
    bread: string;
}

/**
 * Check if a given object implements the BreadCapacityPickupLocation interface.
 */
export function instanceOfBreadCapacityPickupLocation(value: object): value is BreadCapacityPickupLocation {
    if (!('pickupLocationName' in value) || value['pickupLocationName'] === undefined) return false;
    if (!('deliveryDay' in value) || value['deliveryDay'] === undefined) return false;
    if (!('breadName' in value) || value['breadName'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('deliveryWeek' in value) || value['deliveryWeek'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    if (!('bread' in value) || value['bread'] === undefined) return false;
    return true;
}

export function BreadCapacityPickupLocationFromJSON(json: any): BreadCapacityPickupLocation {
    return BreadCapacityPickupLocationFromJSONTyped(json, false);
}

export function BreadCapacityPickupLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BreadCapacityPickupLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'pickupLocationName': json['pickup_location_name'],
        'deliveryDay': json['delivery_day'],
        'breadName': json['bread_name'],
        'year': json['year'],
        'deliveryWeek': json['delivery_week'],
        'capacity': json['capacity'],
        'pickupLocation': json['pickup_location'] == null ? undefined : json['pickup_location'],
        'bread': json['bread'],
    };
}

  export function BreadCapacityPickupLocationToJSON(json: any): BreadCapacityPickupLocation {
      return BreadCapacityPickupLocationToJSONTyped(json, false);
  }

  export function BreadCapacityPickupLocationToJSONTyped(value?: Omit<BreadCapacityPickupLocation, 'pickup_location_name'|'delivery_day'|'bread_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'delivery_week': value['deliveryWeek'],
        'capacity': value['capacity'],
        'pickup_location': value['pickupLocation'],
        'bread': value['bread'],
    };
}

