/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BreadDeliveryRequest
 */
export interface BreadDeliveryRequest {
    /**
     * 
     * @type {string}
     * @memberof BreadDeliveryRequest
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BreadDeliveryRequest
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof BreadDeliveryRequest
     */
    deliveryWeek: number;
    /**
     * 
     * @type {number}
     * @memberof BreadDeliveryRequest
     */
    slotNumber?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BreadDeliveryRequest
     */
    jokerTaken?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BreadDeliveryRequest
     */
    subscription: string;
    /**
     * 
     * @type {string}
     * @memberof BreadDeliveryRequest
     */
    pickupLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BreadDeliveryRequest
     */
    bread?: string | null;
}

/**
 * Check if a given object implements the BreadDeliveryRequest interface.
 */
export function instanceOfBreadDeliveryRequest(value: object): value is BreadDeliveryRequest {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('deliveryWeek' in value) || value['deliveryWeek'] === undefined) return false;
    if (!('subscription' in value) || value['subscription'] === undefined) return false;
    return true;
}

export function BreadDeliveryRequestFromJSON(json: any): BreadDeliveryRequest {
    return BreadDeliveryRequestFromJSONTyped(json, false);
}

export function BreadDeliveryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BreadDeliveryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'year': json['year'],
        'deliveryWeek': json['delivery_week'],
        'slotNumber': json['slot_number'] == null ? undefined : json['slot_number'],
        'jokerTaken': json['joker_taken'] == null ? undefined : json['joker_taken'],
        'subscription': json['subscription'],
        'pickupLocation': json['pickup_location'] == null ? undefined : json['pickup_location'],
        'bread': json['bread'] == null ? undefined : json['bread'],
    };
}

  export function BreadDeliveryRequestToJSON(json: any): BreadDeliveryRequest {
      return BreadDeliveryRequestToJSONTyped(json, false);
  }

  export function BreadDeliveryRequestToJSONTyped(value?: BreadDeliveryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'delivery_week': value['deliveryWeek'],
        'slot_number': value['slotNumber'],
        'joker_taken': value['jokerTaken'],
        'subscription': value['subscription'],
        'pickup_location': value['pickupLocation'],
        'bread': value['bread'],
    };
}

