/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PickupLocationDeliveryDay } from "./PickupLocationDeliveryDay";
import {
  PickupLocationDeliveryDayFromJSON,
  PickupLocationDeliveryDayToJSON,
} from "./PickupLocationDeliveryDay";

/**
 *
 * @export
 * @interface BreadCapacityAllocationResponse
 */
export interface BreadCapacityAllocationResponse {
  /**
   *
   * @type {Array<PickupLocationDeliveryDay>}
   * @memberof BreadCapacityAllocationResponse
   */
  pickupLocations: Array<PickupLocationDeliveryDay>;
  /**
   *
   * @type {{ [key: string]: { [key: string]: number | null; }; }}
   * @memberof BreadCapacityAllocationResponse
   */
  allocations: { [key: string]: { [key: string]: number | null } };
}

/**
 * Check if a given object implements the BreadCapacityAllocationResponse interface.
 */
export function instanceOfBreadCapacityAllocationResponse(
  value: object,
): value is BreadCapacityAllocationResponse {
  if (!("pickupLocations" in value) || value["pickupLocations"] === undefined)
    return false;
  if (!("allocations" in value) || value["allocations"] === undefined)
    return false;
  return true;
}

export function BreadCapacityAllocationResponseFromJSON(
  json: any,
): BreadCapacityAllocationResponse {
  return BreadCapacityAllocationResponseFromJSONTyped(json, false);
}

export function BreadCapacityAllocationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BreadCapacityAllocationResponse {
  if (json == null) {
    return json;
  }
  return {
    pickupLocations: (json["pickup_locations"] as Array<any>).map(
      PickupLocationDeliveryDayFromJSON,
    ),
    allocations: json["allocations"],
  };
}

export function BreadCapacityAllocationResponseToJSON(
  json: any,
): BreadCapacityAllocationResponse {
  return BreadCapacityAllocationResponseToJSONTyped(json, false);
}

export function BreadCapacityAllocationResponseToJSONTyped(
  value?: BreadCapacityAllocationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    pickup_locations: (value["pickupLocations"] as Array<any>).map(
      PickupLocationDeliveryDayToJSON,
    ),
    allocations: value["allocations"],
  };
}
