/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BreadSpecificsPerDeliveryDay
 */
export interface BreadSpecificsPerDeliveryDay {
    /**
     * 
     * @type {string}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    readonly breadName: string;
    /**
     * 
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    deliveryWeek: number;
    /**
     * 
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    deliveryDay: number;
    /**
     * Minimum number of pieces that should be baked for this bread on this delivery day (e.g., to ensure that there are enough pieces for walk-in customers)
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    minPieces?: number | null;
    /**
     * Maximum number of pieces that should be baked for this bread on this delivery day (e.g., to limit the amount of bread that can be ordered for this bread)
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    maxPieces?: number | null;
    /**
     * Minimum amount of breads that should remain available for this bread on this delivery day (e.g., for walk-in customers)
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    minRemainingPieces?: number | null;
    /**
     * If set, exactly this number of pieces should be baked for this bread on this delivery day (overrides min/max)
     * @type {number}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    fixedPieces?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BreadSpecificsPerDeliveryDay
     */
    bread: string;
}

/**
 * Check if a given object implements the BreadSpecificsPerDeliveryDay interface.
 */
export function instanceOfBreadSpecificsPerDeliveryDay(value: object): value is BreadSpecificsPerDeliveryDay {
    if (!('breadName' in value) || value['breadName'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('deliveryWeek' in value) || value['deliveryWeek'] === undefined) return false;
    if (!('deliveryDay' in value) || value['deliveryDay'] === undefined) return false;
    if (!('bread' in value) || value['bread'] === undefined) return false;
    return true;
}

export function BreadSpecificsPerDeliveryDayFromJSON(json: any): BreadSpecificsPerDeliveryDay {
    return BreadSpecificsPerDeliveryDayFromJSONTyped(json, false);
}

export function BreadSpecificsPerDeliveryDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): BreadSpecificsPerDeliveryDay {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'breadName': json['bread_name'],
        'year': json['year'],
        'deliveryWeek': json['delivery_week'],
        'deliveryDay': json['delivery_day'],
        'minPieces': json['min_pieces'] == null ? undefined : json['min_pieces'],
        'maxPieces': json['max_pieces'] == null ? undefined : json['max_pieces'],
        'minRemainingPieces': json['min_remaining_pieces'] == null ? undefined : json['min_remaining_pieces'],
        'fixedPieces': json['fixed_pieces'] == null ? undefined : json['fixed_pieces'],
        'bread': json['bread'],
    };
}

  export function BreadSpecificsPerDeliveryDayToJSON(json: any): BreadSpecificsPerDeliveryDay {
      return BreadSpecificsPerDeliveryDayToJSONTyped(json, false);
  }

  export function BreadSpecificsPerDeliveryDayToJSONTyped(value?: Omit<BreadSpecificsPerDeliveryDay, 'bread_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'delivery_week': value['deliveryWeek'],
        'delivery_day': value['deliveryDay'],
        'min_pieces': value['minPieces'],
        'max_pieces': value['maxPieces'],
        'min_remaining_pieces': value['minRemainingPieces'],
        'fixed_pieces': value['fixedPieces'],
        'bread': value['bread'],
    };
}

