/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuildExportResponse
 */
export interface BuildExportResponse {
    /**
     * 
     * @type {string}
     * @memberof BuildExportResponse
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof BuildExportResponse
     */
    fileAsString: string;
}

/**
 * Check if a given object implements the BuildExportResponse interface.
 */
export function instanceOfBuildExportResponse(value: object): value is BuildExportResponse {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileAsString' in value) || value['fileAsString'] === undefined) return false;
    return true;
}

export function BuildExportResponseFromJSON(json: any): BuildExportResponse {
    return BuildExportResponseFromJSONTyped(json, false);
}

export function BuildExportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildExportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['file_name'],
        'fileAsString': json['file_as_string'],
    };
}

  export function BuildExportResponseToJSON(json: any): BuildExportResponse {
      return BuildExportResponseToJSONTyped(json, false);
  }

  export function BuildExportResponseToJSONTyped(value?: BuildExportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_name': value['fileName'],
        'file_as_string': value['fileAsString'],
    };
}

