/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PickupLocation } from './PickupLocation';
import {
    PickupLocationFromJSON,
    PickupLocationFromJSONTyped,
    PickupLocationToJSON,
    PickupLocationToJSONTyped,
} from './PickupLocation';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * 
 * @export
 * @interface CancelledSubscription
 */
export interface CancelledSubscription {
    /**
     * 
     * @type {Subscription}
     * @memberof CancelledSubscription
     */
    subscription: Subscription;
    /**
     * 
     * @type {Member}
     * @memberof CancelledSubscription
     */
    member: Member;
    /**
     * 
     * @type {PickupLocation}
     * @memberof CancelledSubscription
     */
    pickupLocation: PickupLocation;
}

/**
 * Check if a given object implements the CancelledSubscription interface.
 */
export function instanceOfCancelledSubscription(value: object): value is CancelledSubscription {
    if (!('subscription' in value) || value['subscription'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    if (!('pickupLocation' in value) || value['pickupLocation'] === undefined) return false;
    return true;
}

export function CancelledSubscriptionFromJSON(json: any): CancelledSubscription {
    return CancelledSubscriptionFromJSONTyped(json, false);
}

export function CancelledSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelledSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription': SubscriptionFromJSON(json['subscription']),
        'member': MemberFromJSON(json['member']),
        'pickupLocation': PickupLocationFromJSON(json['pickup_location']),
    };
}

  export function CancelledSubscriptionToJSON(json: any): CancelledSubscription {
      return CancelledSubscriptionToJSONTyped(json, false);
  }

  export function CancelledSubscriptionToJSONTyped(value?: CancelledSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription': SubscriptionToJSON(value['subscription']),
        'member': MemberToJSON(value['member']),
        'pickup_location': PickupLocationToJSON(value['pickupLocation']),
    };
}

