/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancellationData
 */
export interface CancellationData {
    /**
     * 
     * @type {boolean}
     * @memberof CancellationData
     */
    isInTrial: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CancellationData
     */
    subscriptionEndDate?: Date;
}

/**
 * Check if a given object implements the CancellationData interface.
 */
export function instanceOfCancellationData(value: object): value is CancellationData {
    if (!('isInTrial' in value) || value['isInTrial'] === undefined) return false;
    return true;
}

export function CancellationDataFromJSON(json: any): CancellationData {
    return CancellationDataFromJSONTyped(json, false);
}

export function CancellationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancellationData {
    if (json == null) {
        return json;
    }
    return {
        
        'isInTrial': json['is_in_trial'],
        'subscriptionEndDate': json['subscription_end_date'] == null ? undefined : (new Date(json['subscription_end_date'])),
    };
}

  export function CancellationDataToJSON(json: any): CancellationData {
      return CancellationDataToJSONTyped(json, false);
  }

  export function CancellationDataToJSONTyped(value?: CancellationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_in_trial': value['isInTrial'],
        'subscription_end_date': value['subscriptionEndDate'] == null ? undefined : ((value['subscriptionEndDate']).toISOString().substring(0,10)),
    };
}

