/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Counts
 */
export interface Counts {
    /**
     * 
     * @type {number}
     * @memberof Counts
     */
    all: number;
    /**
     * 
     * @type {number}
     * @memberof Counts
     */
    newMembers: number;
    /**
     * 
     * @type {number}
     * @memberof Counts
     */
    existingMembers: number;
}

/**
 * Check if a given object implements the Counts interface.
 */
export function instanceOfCounts(value: object): value is Counts {
    if (!('all' in value) || value['all'] === undefined) return false;
    if (!('newMembers' in value) || value['newMembers'] === undefined) return false;
    if (!('existingMembers' in value) || value['existingMembers'] === undefined) return false;
    return true;
}

export function CountsFromJSON(json: any): Counts {
    return CountsFromJSONTyped(json, false);
}

export function CountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Counts {
    if (json == null) {
        return json;
    }
    return {
        
        'all': json['all'],
        'newMembers': json['new_members'],
        'existingMembers': json['existing_members'],
    };
}

  export function CountsToJSON(json: any): Counts {
      return CountsToJSONTyped(json, false);
  }

  export function CountsToJSONTyped(value?: Counts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'all': value['all'],
        'new_members': value['newMembers'],
        'existing_members': value['existingMembers'],
    };
}

