/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExportSegmentColumnRequest } from './ExportSegmentColumnRequest';
import {
    ExportSegmentColumnRequestFromJSON,
    ExportSegmentColumnRequestFromJSONTyped,
    ExportSegmentColumnRequestToJSON,
    ExportSegmentColumnRequestToJSONTyped,
} from './ExportSegmentColumnRequest';

/**
 * 
 * @export
 * @interface CsvExportRequest
 */
export interface CsvExportRequest {
    /**
     * 
     * @type {number}
     * @memberof CsvExportRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CsvExportRequest
     */
    exportSegmentId: string;
    /**
     * 
     * @type {string}
     * @memberof CsvExportRequest
     */
    exportSegmentName: string;
    /**
     * 
     * @type {string}
     * @memberof CsvExportRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CsvExportRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CsvExportRequest
     */
    separator: string;
    /**
     * 
     * @type {string}
     * @memberof CsvExportRequest
     */
    fileName: string;
    /**
     * 
     * @type {Array<ExportSegmentColumnRequest>}
     * @memberof CsvExportRequest
     */
    columns: Array<ExportSegmentColumnRequest>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CsvExportRequest
     */
    emailRecipients: Array<string>;
}

/**
 * Check if a given object implements the CsvExportRequest interface.
 */
export function instanceOfCsvExportRequest(value: object): value is CsvExportRequest {
    if (!('exportSegmentId' in value) || value['exportSegmentId'] === undefined) return false;
    if (!('exportSegmentName' in value) || value['exportSegmentName'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('separator' in value) || value['separator'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('emailRecipients' in value) || value['emailRecipients'] === undefined) return false;
    return true;
}

export function CsvExportRequestFromJSON(json: any): CsvExportRequest {
    return CsvExportRequestFromJSONTyped(json, false);
}

export function CsvExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsvExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'exportSegmentId': json['export_segment_id'],
        'exportSegmentName': json['export_segment_name'],
        'name': json['name'],
        'description': json['description'],
        'separator': json['separator'],
        'fileName': json['file_name'],
        'columns': ((json['columns'] as Array<any>).map(ExportSegmentColumnRequestFromJSON)),
        'emailRecipients': json['email_recipients'],
    };
}

  export function CsvExportRequestToJSON(json: any): CsvExportRequest {
      return CsvExportRequestToJSONTyped(json, false);
  }

  export function CsvExportRequestToJSONTyped(value?: CsvExportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'export_segment_id': value['exportSegmentId'],
        'export_segment_name': value['exportSegmentName'],
        'name': value['name'],
        'description': value['description'],
        'separator': value['separator'],
        'file_name': value['fileName'],
        'columns': ((value['columns'] as Array<any>).map(ExportSegmentColumnRequestToJSON)),
        'email_recipients': value['emailRecipients'],
    };
}

