/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeliveryDayAdjustmentRequest
 */
export interface DeliveryDayAdjustmentRequest {
  /**
   *
   * @type {number}
   * @memberof DeliveryDayAdjustmentRequest
   */
  calendarWeek: number;
  /**
   *
   * @type {number}
   * @memberof DeliveryDayAdjustmentRequest
   */
  adjustedWeekday: number;
}

/**
 * Check if a given object implements the DeliveryDayAdjustmentRequest interface.
 */
export function instanceOfDeliveryDayAdjustmentRequest(
  value: object,
): value is DeliveryDayAdjustmentRequest {
  if (!("calendarWeek" in value) || value["calendarWeek"] === undefined)
    return false;
  if (!("adjustedWeekday" in value) || value["adjustedWeekday"] === undefined)
    return false;
  return true;
}

export function DeliveryDayAdjustmentRequestFromJSON(
  json: any,
): DeliveryDayAdjustmentRequest {
  return DeliveryDayAdjustmentRequestFromJSONTyped(json, false);
}

export function DeliveryDayAdjustmentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeliveryDayAdjustmentRequest {
  if (json == null) {
    return json;
  }
  return {
    calendarWeek: json["calendar_week"],
    adjustedWeekday: json["adjusted_weekday"],
  };
}

export function DeliveryDayAdjustmentRequestToJSON(
  json: any,
): DeliveryDayAdjustmentRequest {
  return DeliveryDayAdjustmentRequestToJSONTyped(json, false);
}

export function DeliveryDayAdjustmentRequestToJSONTyped(
  value?: DeliveryDayAdjustmentRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    calendar_week: value["calendarWeek"],
    adjusted_weekday: value["adjustedWeekday"],
  };
}
