/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExportSegmentColumn
 */
export interface ExportSegmentColumn {
  /**
   *
   * @type {string}
   * @memberof ExportSegmentColumn
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ExportSegmentColumn
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof ExportSegmentColumn
   */
  description: string;
}

/**
 * Check if a given object implements the ExportSegmentColumn interface.
 */
export function instanceOfExportSegmentColumn(
  value: object,
): value is ExportSegmentColumn {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  return true;
}

export function ExportSegmentColumnFromJSON(json: any): ExportSegmentColumn {
  return ExportSegmentColumnFromJSONTyped(json, false);
}

export function ExportSegmentColumnFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExportSegmentColumn {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    displayName: json["display_name"],
    description: json["description"],
  };
}

export function ExportSegmentColumnToJSON(json: any): ExportSegmentColumn {
  return ExportSegmentColumnToJSONTyped(json, false);
}

export function ExportSegmentColumnToJSONTyped(
  value?: ExportSegmentColumn | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    display_name: value["displayName"],
    description: value["description"],
  };
}
