/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetDatesFromCustomCycleDeliveryWeeksResponse
 */
export interface GetDatesFromCustomCycleDeliveryWeeksResponse {
  /**
   *
   * @type {{ [key: string]: { [key: string]: Date; }; }}
   * @memberof GetDatesFromCustomCycleDeliveryWeeksResponse
   */
  customCycleDeliveryWeeksDates: { [key: string]: { [key: string]: Date } };
  /**
   *
   * @type {string}
   * @memberof GetDatesFromCustomCycleDeliveryWeeksResponse
   */
  error: string;
}

/**
 * Check if a given object implements the GetDatesFromCustomCycleDeliveryWeeksResponse interface.
 */
export function instanceOfGetDatesFromCustomCycleDeliveryWeeksResponse(
  value: object,
): value is GetDatesFromCustomCycleDeliveryWeeksResponse {
  if (
    !("customCycleDeliveryWeeksDates" in value) ||
    value["customCycleDeliveryWeeksDates"] === undefined
  )
    return false;
  if (!("error" in value) || value["error"] === undefined) return false;
  return true;
}

export function GetDatesFromCustomCycleDeliveryWeeksResponseFromJSON(
  json: any,
): GetDatesFromCustomCycleDeliveryWeeksResponse {
  return GetDatesFromCustomCycleDeliveryWeeksResponseFromJSONTyped(json, false);
}

export function GetDatesFromCustomCycleDeliveryWeeksResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDatesFromCustomCycleDeliveryWeeksResponse {
  if (json == null) {
    return json;
  }
  return {
    customCycleDeliveryWeeksDates: json["custom_cycle_delivery_weeks_dates"],
    error: json["error"],
  };
}

export function GetDatesFromCustomCycleDeliveryWeeksResponseToJSON(
  json: any,
): GetDatesFromCustomCycleDeliveryWeeksResponse {
  return GetDatesFromCustomCycleDeliveryWeeksResponseToJSONTyped(json, false);
}

export function GetDatesFromCustomCycleDeliveryWeeksResponseToJSONTyped(
  value?: GetDatesFromCustomCycleDeliveryWeeksResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    custom_cycle_delivery_weeks_dates: value["customCycleDeliveryWeeksDates"],
    error: value["error"],
  };
}
