/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GraphDataset
 */
export interface GraphDataset {
  /**
   *
   * @type {string}
   * @memberof GraphDataset
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof GraphDataset
   */
  color: string;
  /**
   *
   * @type {Array<number>}
   * @memberof GraphDataset
   */
  values: Array<number>;
}

/**
 * Check if a given object implements the GraphDataset interface.
 */
export function instanceOfGraphDataset(value: object): value is GraphDataset {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("color" in value) || value["color"] === undefined) return false;
  if (!("values" in value) || value["values"] === undefined) return false;
  return true;
}

export function GraphDatasetFromJSON(json: any): GraphDataset {
  return GraphDatasetFromJSONTyped(json, false);
}

export function GraphDatasetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphDataset {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    color: json["color"],
    values: json["values"],
  };
}

export function GraphDatasetToJSON(json: any): GraphDataset {
  return GraphDatasetToJSONTyped(json, false);
}

export function GraphDatasetToJSONTyped(
  value?: GraphDataset | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    color: value["color"],
    values: value["values"],
  };
}
