/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Member } from "./Member";
import { MemberFromJSON, MemberToJSON } from "./Member";

/**
 *
 * @export
 * @interface JokerCreditIntendedUsePreviewResponse
 */
export interface JokerCreditIntendedUsePreviewResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof JokerCreditIntendedUsePreviewResponse
   */
  previewsNew: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof JokerCreditIntendedUsePreviewResponse
   */
  previewsOld: Array<string>;
  /**
   *
   * @type {string}
   * @memberof JokerCreditIntendedUsePreviewResponse
   */
  error: string;
  /**
   *
   * @type {Array<string>}
   * @memberof JokerCreditIntendedUsePreviewResponse
   */
  tokens: Array<string>;
  /**
   *
   * @type {Array<number>}
   * @memberof JokerCreditIntendedUsePreviewResponse
   */
  credits: Array<number>;
  /**
   *
   * @type {Array<Member>}
   * @memberof JokerCreditIntendedUsePreviewResponse
   */
  members: Array<Member>;
}

/**
 * Check if a given object implements the JokerCreditIntendedUsePreviewResponse interface.
 */
export function instanceOfJokerCreditIntendedUsePreviewResponse(
  value: object,
): value is JokerCreditIntendedUsePreviewResponse {
  if (!("previewsNew" in value) || value["previewsNew"] === undefined)
    return false;
  if (!("previewsOld" in value) || value["previewsOld"] === undefined)
    return false;
  if (!("error" in value) || value["error"] === undefined) return false;
  if (!("tokens" in value) || value["tokens"] === undefined) return false;
  if (!("credits" in value) || value["credits"] === undefined) return false;
  if (!("members" in value) || value["members"] === undefined) return false;
  return true;
}

export function JokerCreditIntendedUsePreviewResponseFromJSON(
  json: any,
): JokerCreditIntendedUsePreviewResponse {
  return JokerCreditIntendedUsePreviewResponseFromJSONTyped(json, false);
}

export function JokerCreditIntendedUsePreviewResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JokerCreditIntendedUsePreviewResponse {
  if (json == null) {
    return json;
  }
  return {
    previewsNew: json["previews_new"],
    previewsOld: json["previews_old"],
    error: json["error"],
    tokens: json["tokens"],
    credits: json["credits"],
    members: (json["members"] as Array<any>).map(MemberFromJSON),
  };
}

export function JokerCreditIntendedUsePreviewResponseToJSON(
  json: any,
): JokerCreditIntendedUsePreviewResponse {
  return JokerCreditIntendedUsePreviewResponseToJSONTyped(json, false);
}

export function JokerCreditIntendedUsePreviewResponseToJSONTyped(
  value?: JokerCreditIntendedUsePreviewResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    previews_new: value["previewsNew"],
    previews_old: value["previewsOld"],
    error: value["error"],
    tokens: value["tokens"],
    credits: value["credits"],
    members: (value["members"] as Array<any>).map(MemberToJSON),
  };
}
