/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `association` - Verein
 * * `coop` - Genossenschaft
 * * `company` - Einzelunternehmen
 * @export
 */
export const LegalStatusEnum = {
    Association: 'association',
    Coop: 'coop',
    Company: 'company'
} as const;
export type LegalStatusEnum = typeof LegalStatusEnum[keyof typeof LegalStatusEnum];


export function instanceOfLegalStatusEnum(value: any): boolean {
    for (const key in LegalStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(LegalStatusEnum, key)) {
            if (LegalStatusEnum[key as keyof typeof LegalStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LegalStatusEnumFromJSON(json: any): LegalStatusEnum {
    return LegalStatusEnumFromJSONTyped(json, false);
}

export function LegalStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalStatusEnum {
    return json as LegalStatusEnum;
}

export function LegalStatusEnumToJSON(value?: LegalStatusEnum | null): any {
    return value as any;
}

export function LegalStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): LegalStatusEnum {
    return value as LegalStatusEnum;
}

