/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LocationRouteRequest
 */
export interface LocationRouteRequest {
  /**
   *
   * @type {string}
   * @memberof LocationRouteRequest
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof LocationRouteRequest
   */
  name: string;
}

/**
 * Check if a given object implements the LocationRouteRequest interface.
 */
export function instanceOfLocationRouteRequest(
  value: object,
): value is LocationRouteRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function LocationRouteRequestFromJSON(json: any): LocationRouteRequest {
  return LocationRouteRequestFromJSONTyped(json, false);
}

export function LocationRouteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LocationRouteRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"],
  };
}

export function LocationRouteRequestToJSON(json: any): LocationRouteRequest {
  return LocationRouteRequestToJSONTyped(json, false);
}

export function LocationRouteRequestToJSONTyped(
  value?: LocationRouteRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
  };
}
