/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MemberCredit
 */
export interface MemberCredit {
  /**
   *
   * @type {string}
   * @memberof MemberCredit
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof MemberCredit
   */
  member: string;
  /**
   *
   * @type {number}
   * @memberof MemberCredit
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof MemberCredit
   */
  purpose: string;
  /**
   *
   * @type {string}
   * @memberof MemberCredit
   */
  comment: string;
  /**
   *
   * @type {Date}
   * @memberof MemberCredit
   */
  dueDate: Date;
  /**
   *
   * @type {Date}
   * @memberof MemberCredit
   */
  settledOn?: Date | null;
}

/**
 * Check if a given object implements the MemberCredit interface.
 */
export function instanceOfMemberCredit(value: object): value is MemberCredit {
  if (!("member" in value) || value["member"] === undefined) return false;
  if (!("amount" in value) || value["amount"] === undefined) return false;
  if (!("purpose" in value) || value["purpose"] === undefined) return false;
  if (!("comment" in value) || value["comment"] === undefined) return false;
  if (!("dueDate" in value) || value["dueDate"] === undefined) return false;
  return true;
}

export function MemberCreditFromJSON(json: any): MemberCredit {
  return MemberCreditFromJSONTyped(json, false);
}

export function MemberCreditFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MemberCredit {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    member: json["member"],
    amount: json["amount"],
    purpose: json["purpose"],
    comment: json["comment"],
    dueDate: new Date(json["due_date"]),
    settledOn:
      json["settled_on"] == null ? undefined : new Date(json["settled_on"]),
  };
}

export function MemberCreditToJSON(json: any): MemberCredit {
  return MemberCreditToJSONTyped(json, false);
}

export function MemberCreditToJSONTyped(
  value?: MemberCredit | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    member: value["member"],
    amount: value["amount"],
    purpose: value["purpose"],
    comment: value["comment"],
    due_date: value["dueDate"].toISOString().substring(0, 10),
    settled_on:
      value["settledOn"] == null
        ? undefined
        : (value["settledOn"] as any).toISOString(),
  };
}
