/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberCredit
 */
export interface MemberCredit {
    /**
     * 
     * @type {string}
     * @memberof MemberCredit
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof MemberCredit
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof MemberCredit
     */
    dueDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof MemberCredit
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof MemberCredit
     */
    purpose: string;
    /**
     * 
     * @type {string}
     * @memberof MemberCredit
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof MemberCredit
     */
    member: string;
}

/**
 * Check if a given object implements the MemberCredit interface.
 */
export function instanceOfMemberCredit(value: object): value is MemberCredit {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function MemberCreditFromJSON(json: any): MemberCredit {
    return MemberCreditFromJSONTyped(json, false);
}

export function MemberCreditFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberCredit {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'amount': json['amount'],
        'dueDate': (new Date(json['due_date'])),
        'createdAt': (new Date(json['created_at'])),
        'purpose': json['purpose'],
        'comment': json['comment'],
        'member': json['member'],
    };
}

  export function MemberCreditToJSON(json: any): MemberCredit {
      return MemberCreditToJSONTyped(json, false);
  }

  export function MemberCreditToJSONTyped(value?: Omit<MemberCredit, 'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'due_date': ((value['dueDate']).toISOString().substring(0,10)),
        'purpose': value['purpose'],
        'comment': value['comment'],
        'member': value['member'],
    };
}

