/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolidarityContribution } from './SolidarityContribution';
import {
    SolidarityContributionFromJSON,
    SolidarityContributionFromJSONTyped,
    SolidarityContributionToJSON,
    SolidarityContributionToJSONTyped,
} from './SolidarityContribution';

/**
 * 
 * @export
 * @interface MemberSolidarityContributionsResponse
 */
export interface MemberSolidarityContributionsResponse {
    /**
     * 
     * @type {Array<SolidarityContribution>}
     * @memberof MemberSolidarityContributionsResponse
     */
    contributions: Array<SolidarityContribution>;
    /**
     * 
     * @type {Date}
     * @memberof MemberSolidarityContributionsResponse
     */
    changeValidFrom: Date;
    /**
     * 
     * @type {boolean}
     * @memberof MemberSolidarityContributionsResponse
     */
    userCanSetLowerValue: boolean;
}

/**
 * Check if a given object implements the MemberSolidarityContributionsResponse interface.
 */
export function instanceOfMemberSolidarityContributionsResponse(value: object): value is MemberSolidarityContributionsResponse {
    if (!('contributions' in value) || value['contributions'] === undefined) return false;
    if (!('changeValidFrom' in value) || value['changeValidFrom'] === undefined) return false;
    if (!('userCanSetLowerValue' in value) || value['userCanSetLowerValue'] === undefined) return false;
    return true;
}

export function MemberSolidarityContributionsResponseFromJSON(json: any): MemberSolidarityContributionsResponse {
    return MemberSolidarityContributionsResponseFromJSONTyped(json, false);
}

export function MemberSolidarityContributionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberSolidarityContributionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'contributions': ((json['contributions'] as Array<any>).map(SolidarityContributionFromJSON)),
        'changeValidFrom': (new Date(json['change_valid_from'])),
        'userCanSetLowerValue': json['user_can_set_lower_value'],
    };
}

  export function MemberSolidarityContributionsResponseToJSON(json: any): MemberSolidarityContributionsResponse {
      return MemberSolidarityContributionsResponseToJSONTyped(json, false);
  }

  export function MemberSolidarityContributionsResponseToJSONTyped(value?: MemberSolidarityContributionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contributions': ((value['contributions'] as Array<any>).map(SolidarityContributionToJSON)),
        'change_valid_from': ((value['changeValidFrom']).toISOString().substring(0,10)),
        'user_can_set_lower_value': value['userCanSetLowerValue'],
    };
}

