/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PublicProductType } from "./PublicProductType";
import {
  PublicProductTypeFromJSON,
  PublicProductTypeToJSON,
} from "./PublicProductType";
import type { PublicSubscription } from "./PublicSubscription";
import {
  PublicSubscriptionFromJSON,
  PublicSubscriptionToJSON,
} from "./PublicSubscription";

/**
 *
 * @export
 * @interface MemberSubscriptionData
 */
export interface MemberSubscriptionData {
  /**
   *
   * @type {Array<PublicProductType>}
   * @memberof MemberSubscriptionData
   */
  productTypes: Array<PublicProductType>;
  /**
   *
   * @type {Array<PublicSubscription>}
   * @memberof MemberSubscriptionData
   */
  subscriptions: Array<PublicSubscription>;
  /**
   *
   * @type {string}
   * @memberof MemberSubscriptionData
   */
  bestellWizardUrlTemplate: string;
}

/**
 * Check if a given object implements the MemberSubscriptionData interface.
 */
export function instanceOfMemberSubscriptionData(
  value: object,
): value is MemberSubscriptionData {
  if (!("productTypes" in value) || value["productTypes"] === undefined)
    return false;
  if (!("subscriptions" in value) || value["subscriptions"] === undefined)
    return false;
  if (
    !("bestellWizardUrlTemplate" in value) ||
    value["bestellWizardUrlTemplate"] === undefined
  )
    return false;
  return true;
}

export function MemberSubscriptionDataFromJSON(
  json: any,
): MemberSubscriptionData {
  return MemberSubscriptionDataFromJSONTyped(json, false);
}

export function MemberSubscriptionDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MemberSubscriptionData {
  if (json == null) {
    return json;
  }
  return {
    productTypes: (json["product_types"] as Array<any>).map(
      PublicProductTypeFromJSON,
    ),
    subscriptions: (json["subscriptions"] as Array<any>).map(
      PublicSubscriptionFromJSON,
    ),
    bestellWizardUrlTemplate: json["bestell_wizard_url_template"],
  };
}

export function MemberSubscriptionDataToJSON(
  json: any,
): MemberSubscriptionData {
  return MemberSubscriptionDataToJSONTyped(json, false);
}

export function MemberSubscriptionDataToJSONTyped(
  value?: MemberSubscriptionData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    product_types: (value["productTypes"] as Array<any>).map(
      PublicProductTypeToJSON,
    ),
    subscriptions: (value["subscriptions"] as Array<any>).map(
      PublicSubscriptionToJSON,
    ),
    bestell_wizard_url_template: value["bestellWizardUrlTemplate"],
  };
}
