/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MemberCreditSettleRequest
 */
export interface MemberCreditSettleRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof MemberCreditSettleRequest
   */
  creditIds: Array<string>;
}

/**
 * Check if a given object implements the MemberCreditSettleRequest interface.
 */
export function instanceOfMemberCreditSettleRequest(
  value: object,
): value is MemberCreditSettleRequest {
  if (!("creditIds" in value) || value["creditIds"] === undefined) return false;
  return true;
}

export function MemberCreditSettleRequestFromJSON(
  json: any,
): MemberCreditSettleRequest {
  return MemberCreditSettleRequestFromJSONTyped(json, false);
}

export function MemberCreditSettleRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MemberCreditSettleRequest {
  if (json == null) {
    return json;
  }
  return {
    creditIds: json["credit_ids"],
  };
}

export function MemberCreditSettleRequestToJSON(
  json: any,
): MemberCreditSettleRequest {
  return MemberCreditSettleRequestToJSONTyped(json, false);
}

export function MemberCreditSettleRequestToJSONTyped(
  value?: MemberCreditSettleRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    credit_ids: value["creditIds"],
  };
}
