/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EmailConfigurationDispatch } from "./EmailConfigurationDispatch";
import {
  EmailConfigurationDispatchFromJSON,
  EmailConfigurationDispatchToJSON,
} from "./EmailConfigurationDispatch";

/**
 *
 * @export
 * @interface PaginatedEmailConfigurationDispatchList
 */
export interface PaginatedEmailConfigurationDispatchList {
  /**
   *
   * @type {number}
   * @memberof PaginatedEmailConfigurationDispatchList
   */
  count: number;
  /**
   *
   * @type {string}
   * @memberof PaginatedEmailConfigurationDispatchList
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof PaginatedEmailConfigurationDispatchList
   */
  previous?: string | null;
  /**
   *
   * @type {Array<EmailConfigurationDispatch>}
   * @memberof PaginatedEmailConfigurationDispatchList
   */
  results: Array<EmailConfigurationDispatch>;
}

/**
 * Check if a given object implements the PaginatedEmailConfigurationDispatchList interface.
 */
export function instanceOfPaginatedEmailConfigurationDispatchList(
  value: object,
): value is PaginatedEmailConfigurationDispatchList {
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function PaginatedEmailConfigurationDispatchListFromJSON(
  json: any,
): PaginatedEmailConfigurationDispatchList {
  return PaginatedEmailConfigurationDispatchListFromJSONTyped(json, false);
}

export function PaginatedEmailConfigurationDispatchListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginatedEmailConfigurationDispatchList {
  if (json == null) {
    return json;
  }
  return {
    count: json["count"],
    next: json["next"] == null ? undefined : json["next"],
    previous: json["previous"] == null ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(
      EmailConfigurationDispatchFromJSON,
    ),
  };
}

export function PaginatedEmailConfigurationDispatchListToJSON(
  json: any,
): PaginatedEmailConfigurationDispatchList {
  return PaginatedEmailConfigurationDispatchListToJSONTyped(json, false);
}

export function PaginatedEmailConfigurationDispatchListToJSONTyped(
  value?: PaginatedEmailConfigurationDispatchList | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
    next: value["next"],
    previous: value["previous"],
    results: (value["results"] as Array<any>).map(
      EmailConfigurationDispatchToJSON,
    ),
  };
}
