/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BundledEmailConfiguration } from "./BundledEmailConfiguration";
import {
  BundledEmailConfigurationFromJSON,
  BundledEmailConfigurationToJSON,
} from "./BundledEmailConfiguration";

/**
 *
 * @export
 * @interface PaginatedBundledEmailConfigurationList
 */
export interface PaginatedBundledEmailConfigurationList {
  /**
   *
   * @type {number}
   * @memberof PaginatedBundledEmailConfigurationList
   */
  count: number;
  /**
   *
   * @type {string}
   * @memberof PaginatedBundledEmailConfigurationList
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof PaginatedBundledEmailConfigurationList
   */
  previous?: string | null;
  /**
   *
   * @type {Array<BundledEmailConfiguration>}
   * @memberof PaginatedBundledEmailConfigurationList
   */
  results: Array<BundledEmailConfiguration>;
}

/**
 * Check if a given object implements the PaginatedBundledEmailConfigurationList interface.
 */
export function instanceOfPaginatedBundledEmailConfigurationList(
  value: object,
): value is PaginatedBundledEmailConfigurationList {
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function PaginatedBundledEmailConfigurationListFromJSON(
  json: any,
): PaginatedBundledEmailConfigurationList {
  return PaginatedBundledEmailConfigurationListFromJSONTyped(json, false);
}

export function PaginatedBundledEmailConfigurationListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginatedBundledEmailConfigurationList {
  if (json == null) {
    return json;
  }
  return {
    count: json["count"],
    next: json["next"] == null ? undefined : json["next"],
    previous: json["previous"] == null ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(
      BundledEmailConfigurationFromJSON,
    ),
  };
}

export function PaginatedBundledEmailConfigurationListToJSON(
  json: any,
): PaginatedBundledEmailConfigurationList {
  return PaginatedBundledEmailConfigurationListToJSONTyped(json, false);
}

export function PaginatedBundledEmailConfigurationListToJSONTyped(
  value?: PaginatedBundledEmailConfigurationList | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
    next: value["next"],
    previous: value["previous"],
    results: (value["results"] as Array<any>).map(
      BundledEmailConfigurationToJSON,
    ),
  };
}
