/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CsvExportModel } from "./CsvExportModel";
import { CsvExportModelFromJSON, CsvExportModelToJSON } from "./CsvExportModel";

/**
 *
 * @export
 * @interface PaginatedCsvExportModelList
 */
export interface PaginatedCsvExportModelList {
  /**
   *
   * @type {number}
   * @memberof PaginatedCsvExportModelList
   */
  count: number;
  /**
   *
   * @type {string}
   * @memberof PaginatedCsvExportModelList
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof PaginatedCsvExportModelList
   */
  previous?: string | null;
  /**
   *
   * @type {Array<CsvExportModel>}
   * @memberof PaginatedCsvExportModelList
   */
  results: Array<CsvExportModel>;
}

/**
 * Check if a given object implements the PaginatedCsvExportModelList interface.
 */
export function instanceOfPaginatedCsvExportModelList(
  value: object,
): value is PaginatedCsvExportModelList {
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("results" in value) || value["results"] === undefined) return false;
  return true;
}

export function PaginatedCsvExportModelListFromJSON(
  json: any,
): PaginatedCsvExportModelList {
  return PaginatedCsvExportModelListFromJSONTyped(json, false);
}

export function PaginatedCsvExportModelListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginatedCsvExportModelList {
  if (json == null) {
    return json;
  }
  return {
    count: json["count"],
    next: json["next"] == null ? undefined : json["next"],
    previous: json["previous"] == null ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(CsvExportModelFromJSON),
  };
}

export function PaginatedCsvExportModelListToJSON(
  json: any,
): PaginatedCsvExportModelList {
  return PaginatedCsvExportModelListToJSONTyped(json, false);
}

export function PaginatedCsvExportModelListToJSONTyped(
  value?: PaginatedCsvExportModelList | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
    next: value["next"],
    previous: value["previous"],
    results: (value["results"] as Array<any>).map(CsvExportModelToJSON),
  };
}
