/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';

/**
 * 
 * @export
 * @interface PaginatedSubscriptionList
 */
export interface PaginatedSubscriptionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSubscriptionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSubscriptionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSubscriptionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Subscription>}
     * @memberof PaginatedSubscriptionList
     */
    results: Array<Subscription>;
}

/**
 * Check if a given object implements the PaginatedSubscriptionList interface.
 */
export function instanceOfPaginatedSubscriptionList(value: object): value is PaginatedSubscriptionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSubscriptionListFromJSON(json: any): PaginatedSubscriptionList {
    return PaginatedSubscriptionListFromJSONTyped(json, false);
}

export function PaginatedSubscriptionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSubscriptionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SubscriptionFromJSON)),
    };
}

  export function PaginatedSubscriptionListToJSON(json: any): PaginatedSubscriptionList {
      return PaginatedSubscriptionListToJSONTyped(json, false);
  }

  export function PaginatedSubscriptionListToJSONTyped(value?: PaginatedSubscriptionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SubscriptionToJSON)),
    };
}

