/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PatchedMemberProfilePersonalDataRequest
 */
export interface PatchedMemberProfilePersonalDataRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  memberId?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  phoneNumber?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  street?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  street2?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  postcode?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  city?: string;
  /**
   *
   * @type {boolean}
   * @memberof PatchedMemberProfilePersonalDataRequest
   */
  isStudent?: boolean;
}

/**
 * Check if a given object implements the PatchedMemberProfilePersonalDataRequest interface.
 */
export function instanceOfPatchedMemberProfilePersonalDataRequest(
  value: object,
): value is PatchedMemberProfilePersonalDataRequest {
  return true;
}

export function PatchedMemberProfilePersonalDataRequestFromJSON(
  json: any,
): PatchedMemberProfilePersonalDataRequest {
  return PatchedMemberProfilePersonalDataRequestFromJSONTyped(json, false);
}

export function PatchedMemberProfilePersonalDataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PatchedMemberProfilePersonalDataRequest {
  if (json == null) {
    return json;
  }
  return {
    memberId: json["member_id"] == null ? undefined : json["member_id"],
    firstName: json["first_name"] == null ? undefined : json["first_name"],
    lastName: json["last_name"] == null ? undefined : json["last_name"],
    email: json["email"] == null ? undefined : json["email"],
    phoneNumber:
      json["phone_number"] == null ? undefined : json["phone_number"],
    street: json["street"] == null ? undefined : json["street"],
    street2: json["street_2"] == null ? undefined : json["street_2"],
    postcode: json["postcode"] == null ? undefined : json["postcode"],
    city: json["city"] == null ? undefined : json["city"],
    isStudent: json["is_student"] == null ? undefined : json["is_student"],
  };
}

export function PatchedMemberProfilePersonalDataRequestToJSON(
  json: any,
): PatchedMemberProfilePersonalDataRequest {
  return PatchedMemberProfilePersonalDataRequestToJSONTyped(json, false);
}

export function PatchedMemberProfilePersonalDataRequestToJSONTyped(
  value?: PatchedMemberProfilePersonalDataRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    member_id: value["memberId"],
    first_name: value["firstName"],
    last_name: value["lastName"],
    email: value["email"],
    phone_number: value["phoneNumber"],
    street: value["street"],
    street_2: value["street2"],
    postcode: value["postcode"],
    city: value["city"],
    is_student: value["isStudent"],
  };
}
