/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPreferredBreadRequest
 */
export interface PatchedPreferredBreadRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedPreferredBreadRequest
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedPreferredBreadRequest
     */
    breads?: Array<string>;
}

/**
 * Check if a given object implements the PatchedPreferredBreadRequest interface.
 */
export function instanceOfPatchedPreferredBreadRequest(value: object): value is PatchedPreferredBreadRequest {
    return true;
}

export function PatchedPreferredBreadRequestFromJSON(json: any): PatchedPreferredBreadRequest {
    return PatchedPreferredBreadRequestFromJSONTyped(json, false);
}

export function PatchedPreferredBreadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPreferredBreadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'breads': json['breads'] == null ? undefined : json['breads'],
    };
}

  export function PatchedPreferredBreadRequestToJSON(json: any): PatchedPreferredBreadRequest {
      return PatchedPreferredBreadRequestToJSONTyped(json, false);
  }

  export function PatchedPreferredBreadRequestToJSONTyped(value?: PatchedPreferredBreadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'breads': value['breads'],
    };
}

