/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedBreadCapacityPickupLocationRequest
 */
export interface PatchedBreadCapacityPickupLocationRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedBreadCapacityPickupLocationRequest
     */
    id?: string;
    /**
     * Year for which this capacity applies
     * @type {number}
     * @memberof PatchedBreadCapacityPickupLocationRequest
     */
    year?: number;
    /**
     * Delivery week number (1-53)
     * @type {number}
     * @memberof PatchedBreadCapacityPickupLocationRequest
     */
    deliveryWeek?: number;
    /**
     * Maximum number of breads of this type that can be delivered to this pickup location on this delivery day
     * @type {number}
     * @memberof PatchedBreadCapacityPickupLocationRequest
     */
    capacity?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedBreadCapacityPickupLocationRequest
     */
    pickupLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedBreadCapacityPickupLocationRequest
     */
    bread?: string;
}

/**
 * Check if a given object implements the PatchedBreadCapacityPickupLocationRequest interface.
 */
export function instanceOfPatchedBreadCapacityPickupLocationRequest(value: object): value is PatchedBreadCapacityPickupLocationRequest {
    return true;
}

export function PatchedBreadCapacityPickupLocationRequestFromJSON(json: any): PatchedBreadCapacityPickupLocationRequest {
    return PatchedBreadCapacityPickupLocationRequestFromJSONTyped(json, false);
}

export function PatchedBreadCapacityPickupLocationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBreadCapacityPickupLocationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'year': json['year'] == null ? undefined : json['year'],
        'deliveryWeek': json['delivery_week'] == null ? undefined : json['delivery_week'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'pickupLocation': json['pickup_location'] == null ? undefined : json['pickup_location'],
        'bread': json['bread'] == null ? undefined : json['bread'],
    };
}

  export function PatchedBreadCapacityPickupLocationRequestToJSON(json: any): PatchedBreadCapacityPickupLocationRequest {
      return PatchedBreadCapacityPickupLocationRequestToJSONTyped(json, false);
  }

  export function PatchedBreadCapacityPickupLocationRequestToJSONTyped(value?: PatchedBreadCapacityPickupLocationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'delivery_week': value['deliveryWeek'],
        'capacity': value['capacity'],
        'pickup_location': value['pickupLocation'],
        'bread': value['bread'],
    };
}

