/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProductBasketSizeEquivalenceRequest } from "./ProductBasketSizeEquivalenceRequest";
import {
  ProductBasketSizeEquivalenceRequestFromJSON,
  ProductBasketSizeEquivalenceRequestToJSON,
} from "./ProductBasketSizeEquivalenceRequest";

/**
 *
 * @export
 * @interface PatchedExtendedProductRequest
 */
export interface PatchedExtendedProductRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedExtendedProductRequest
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedExtendedProductRequest
   */
  name?: string;
  /**
   *
   * @type {boolean}
   * @memberof PatchedExtendedProductRequest
   */
  deleted?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PatchedExtendedProductRequest
   */
  base?: boolean;
  /**
   *
   * @type {number}
   * @memberof PatchedExtendedProductRequest
   */
  price?: number;
  /**
   *
   * @type {number}
   * @memberof PatchedExtendedProductRequest
   */
  size?: number;
  /**
   *
   * @type {Array<ProductBasketSizeEquivalenceRequest>}
   * @memberof PatchedExtendedProductRequest
   */
  basketSizeEquivalences?: Array<ProductBasketSizeEquivalenceRequest>;
  /**
   *
   * @type {string}
   * @memberof PatchedExtendedProductRequest
   */
  growingPeriodId?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedExtendedProductRequest
   */
  descriptionInBestellwizard?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedExtendedProductRequest
   */
  urlOfImageInBestellwizard?: string;
}

/**
 * Check if a given object implements the PatchedExtendedProductRequest interface.
 */
export function instanceOfPatchedExtendedProductRequest(
  value: object,
): value is PatchedExtendedProductRequest {
  return true;
}

export function PatchedExtendedProductRequestFromJSON(
  json: any,
): PatchedExtendedProductRequest {
  return PatchedExtendedProductRequestFromJSONTyped(json, false);
}

export function PatchedExtendedProductRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PatchedExtendedProductRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    deleted: json["deleted"] == null ? undefined : json["deleted"],
    base: json["base"] == null ? undefined : json["base"],
    price: json["price"] == null ? undefined : json["price"],
    size: json["size"] == null ? undefined : json["size"],
    basketSizeEquivalences:
      json["basket_size_equivalences"] == null
        ? undefined
        : (json["basket_size_equivalences"] as Array<any>).map(
            ProductBasketSizeEquivalenceRequestFromJSON,
          ),
    growingPeriodId:
      json["growing_period_id"] == null ? undefined : json["growing_period_id"],
    descriptionInBestellwizard:
      json["description_in_bestellwizard"] == null
        ? undefined
        : json["description_in_bestellwizard"],
    urlOfImageInBestellwizard:
      json["url_of_image_in_bestellwizard"] == null
        ? undefined
        : json["url_of_image_in_bestellwizard"],
  };
}

export function PatchedExtendedProductRequestToJSON(
  json: any,
): PatchedExtendedProductRequest {
  return PatchedExtendedProductRequestToJSONTyped(json, false);
}

export function PatchedExtendedProductRequestToJSONTyped(
  value?: PatchedExtendedProductRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    deleted: value["deleted"],
    base: value["base"],
    price: value["price"],
    size: value["size"],
    basket_size_equivalences:
      value["basketSizeEquivalences"] == null
        ? undefined
        : (value["basketSizeEquivalences"] as Array<any>).map(
            ProductBasketSizeEquivalenceRequestToJSON,
          ),
    growing_period_id: value["growingPeriodId"],
    description_in_bestellwizard: value["descriptionInBestellwizard"],
    url_of_image_in_bestellwizard: value["urlOfImageInBestellwizard"],
  };
}
