/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUpdateMemberBankDataRequestRequest
 */
export interface PatchedUpdateMemberBankDataRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedUpdateMemberBankDataRequestRequest
     */
    memberId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUpdateMemberBankDataRequestRequest
     */
    iban?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUpdateMemberBankDataRequestRequest
     */
    accountOwner?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUpdateMemberBankDataRequestRequest
     */
    sepaConsent?: boolean;
}

/**
 * Check if a given object implements the PatchedUpdateMemberBankDataRequestRequest interface.
 */
export function instanceOfPatchedUpdateMemberBankDataRequestRequest(value: object): value is PatchedUpdateMemberBankDataRequestRequest {
    return true;
}

export function PatchedUpdateMemberBankDataRequestRequestFromJSON(json: any): PatchedUpdateMemberBankDataRequestRequest {
    return PatchedUpdateMemberBankDataRequestRequestFromJSONTyped(json, false);
}

export function PatchedUpdateMemberBankDataRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUpdateMemberBankDataRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'] == null ? undefined : json['member_id'],
        'iban': json['iban'] == null ? undefined : json['iban'],
        'accountOwner': json['account_owner'] == null ? undefined : json['account_owner'],
        'sepaConsent': json['sepa_consent'] == null ? undefined : json['sepa_consent'],
    };
}

  export function PatchedUpdateMemberBankDataRequestRequestToJSON(json: any): PatchedUpdateMemberBankDataRequestRequest {
      return PatchedUpdateMemberBankDataRequestRequestToJSONTyped(json, false);
  }

  export function PatchedUpdateMemberBankDataRequestRequestToJSONTyped(value?: PatchedUpdateMemberBankDataRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
        'iban': value['iban'],
        'account_owner': value['accountOwner'],
        'sepa_consent': value['sepaConsent'],
    };
}

