/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedBreadListRequest
 */
export interface PatchedBreadListRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedBreadListRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedBreadListRequest
     */
    name?: string;
    /**
     * Image from media library with link
     * @type {Blob}
     * @memberof PatchedBreadListRequest
     */
    picture?: Blob | null;
    /**
     * Description text for the bread
     * @type {string}
     * @memberof PatchedBreadListRequest
     */
    description?: string;
    /**
     * Weight in grams
     * @type {number}
     * @memberof PatchedBreadListRequest
     */
    weight?: number;
    /**
     * List of possible pieces per stove layer (e.g., [10, 11, 12] or [22, 24])
     * @type {any}
     * @memberof PatchedBreadListRequest
     */
    piecesPerStoveLayer?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedBreadListRequest
     */
    oneBatchCanBeBakedInMoreThanOneStove?: boolean;
    /**
     * Minimum number of pieces that should be baked for this bread on a baking day (e.g., to ensure that there are enough pieces for walk-in customers)
     * @type {number}
     * @memberof PatchedBreadListRequest
     */
    minPieces?: number | null;
    /**
     * Maximum number of pieces that should be baked for this bread on a baking day (e.g., to limit the amount of bread that can be ordered for this bread)
     * @type {number}
     * @memberof PatchedBreadListRequest
     */
    maxPieces?: number | null;
    /**
     * Minimum amount of breads that should remain available for this bread on a baking day (e.g., for walk-in customers)
     * @type {number}
     * @memberof PatchedBreadListRequest
     */
    minRemainingPieces?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedBreadListRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedBreadListRequest
     */
    labels?: Array<string>;
}

/**
 * Check if a given object implements the PatchedBreadListRequest interface.
 */
export function instanceOfPatchedBreadListRequest(value: object): value is PatchedBreadListRequest {
    return true;
}

export function PatchedBreadListRequestFromJSON(json: any): PatchedBreadListRequest {
    return PatchedBreadListRequestFromJSONTyped(json, false);
}

export function PatchedBreadListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBreadListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'description': json['description'] == null ? undefined : json['description'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'piecesPerStoveLayer': json['pieces_per_stove_layer'] == null ? undefined : json['pieces_per_stove_layer'],
        'oneBatchCanBeBakedInMoreThanOneStove': json['one_batch_can_be_baked_in_more_than_one_stove'] == null ? undefined : json['one_batch_can_be_baked_in_more_than_one_stove'],
        'minPieces': json['min_pieces'] == null ? undefined : json['min_pieces'],
        'maxPieces': json['max_pieces'] == null ? undefined : json['max_pieces'],
        'minRemainingPieces': json['min_remaining_pieces'] == null ? undefined : json['min_remaining_pieces'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'labels': json['labels'] == null ? undefined : json['labels'],
    };
}

  export function PatchedBreadListRequestToJSON(json: any): PatchedBreadListRequest {
      return PatchedBreadListRequestToJSONTyped(json, false);
  }

  export function PatchedBreadListRequestToJSONTyped(value?: PatchedBreadListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'picture': value['picture'],
        'description': value['description'],
        'weight': value['weight'],
        'pieces_per_stove_layer': value['piecesPerStoveLayer'],
        'one_batch_can_be_baked_in_more_than_one_stove': value['oneBatchCanBeBakedInMoreThanOneStove'],
        'min_pieces': value['minPieces'],
        'max_pieces': value['maxPieces'],
        'min_remaining_pieces': value['minRemainingPieces'],
        'is_active': value['isActive'],
        'labels': value['labels'],
    };
}

