/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailConfigurationVersionRequest } from './EmailConfigurationVersionRequest';
import {
    EmailConfigurationVersionRequestFromJSON,
    EmailConfigurationVersionRequestFromJSONTyped,
    EmailConfigurationVersionRequestToJSON,
    EmailConfigurationVersionRequestToJSONTyped,
} from './EmailConfigurationVersionRequest';

/**
 * 
 * @export
 * @interface PatchedEmailConfigurationDispatchRequest
 */
export interface PatchedEmailConfigurationDispatchRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedEmailConfigurationDispatchRequest
     */
    id?: string;
    /**
     * 
     * @type {EmailConfigurationVersionRequest}
     * @memberof PatchedEmailConfigurationDispatchRequest
     */
    emailConfigurationVersion?: EmailConfigurationVersionRequest;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEmailConfigurationDispatchRequest
     */
    scheduledTime?: Date;
    /**
     * 
     * @type {any}
     * @memberof PatchedEmailConfigurationDispatchRequest
     */
    overrideRecipients?: any | null;
}

/**
 * Check if a given object implements the PatchedEmailConfigurationDispatchRequest interface.
 */
export function instanceOfPatchedEmailConfigurationDispatchRequest(value: object): value is PatchedEmailConfigurationDispatchRequest {
    return true;
}

export function PatchedEmailConfigurationDispatchRequestFromJSON(json: any): PatchedEmailConfigurationDispatchRequest {
    return PatchedEmailConfigurationDispatchRequestFromJSONTyped(json, false);
}

export function PatchedEmailConfigurationDispatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEmailConfigurationDispatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'emailConfigurationVersion': json['email_configuration_version'] == null ? undefined : EmailConfigurationVersionRequestFromJSON(json['email_configuration_version']),
        'scheduledTime': json['scheduled_time'] == null ? undefined : (new Date(json['scheduled_time'])),
        'overrideRecipients': json['override_recipients'] == null ? undefined : json['override_recipients'],
    };
}

  export function PatchedEmailConfigurationDispatchRequestToJSON(json: any): PatchedEmailConfigurationDispatchRequest {
      return PatchedEmailConfigurationDispatchRequestToJSONTyped(json, false);
  }

  export function PatchedEmailConfigurationDispatchRequestToJSONTyped(value?: PatchedEmailConfigurationDispatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email_configuration_version': EmailConfigurationVersionRequestToJSON(value['emailConfigurationVersion']),
        'scheduled_time': value['scheduledTime'] == null ? undefined : ((value['scheduledTime']).toISOString()),
        'override_recipients': value['overrideRecipients'],
    };
}

