/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PaymentTransaction
 */
export interface PaymentTransaction {
  /**
   *
   * @type {string}
   * @memberof PaymentTransaction
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof PaymentTransaction
   */
  readonly paymentsCount: number;
  /**
   *
   * @type {number}
   * @memberof PaymentTransaction
   */
  readonly paymentsSum: number;
  /**
   *
   * @type {string}
   * @memberof PaymentTransaction
   */
  readonly csvDownloadUrl: string;
  /**
   *
   * @type {Date}
   * @memberof PaymentTransaction
   */
  readonly createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof PaymentTransaction
   */
  readonly updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof PaymentTransaction
   */
  type: string;
  /**
   *
   * @type {Date}
   * @memberof PaymentTransaction
   */
  month: Date;
  /**
   *
   * @type {string}
   * @memberof PaymentTransaction
   */
  file: string;
}

/**
 * Check if a given object implements the PaymentTransaction interface.
 */
export function instanceOfPaymentTransaction(
  value: object,
): value is PaymentTransaction {
  if (!("paymentsCount" in value) || value["paymentsCount"] === undefined)
    return false;
  if (!("paymentsSum" in value) || value["paymentsSum"] === undefined)
    return false;
  if (!("csvDownloadUrl" in value) || value["csvDownloadUrl"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("month" in value) || value["month"] === undefined) return false;
  if (!("file" in value) || value["file"] === undefined) return false;
  return true;
}

export function PaymentTransactionFromJSON(json: any): PaymentTransaction {
  return PaymentTransactionFromJSONTyped(json, false);
}

export function PaymentTransactionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaymentTransaction {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    paymentsCount: json["payments_count"],
    paymentsSum: json["payments_sum"],
    csvDownloadUrl: json["csv_download_url"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
    type: json["type"],
    month: new Date(json["month"]),
    file: json["file"],
  };
}

export function PaymentTransactionToJSON(json: any): PaymentTransaction {
  return PaymentTransactionToJSONTyped(json, false);
}

export function PaymentTransactionToJSONTyped(
  value?: Omit<
    PaymentTransaction,
    | "payments_count"
    | "payments_sum"
    | "csv_download_url"
    | "created_at"
    | "updated_at"
  > | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    type: value["type"],
    month: value["month"].toISOString().substring(0, 10),
    file: value["file"],
  };
}
