/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Payment } from "./Payment";

/**
 * 
 * @export
 * @interface PaymentsByDueDate
 */
export interface PaymentsByDueDate {
    /**
     * 
     * @type {{ [key: string]: Array<Payment>; }}
     * @memberof PaymentsByDueDate
     */
    paymentsByDueDate: { [key: string]: Array<Payment>; };
}

/**
 * Check if a given object implements the PaymentsByDueDate interface.
 */
export function instanceOfPaymentsByDueDate(value: object): value is PaymentsByDueDate {
    if (!('paymentsByDueDate' in value) || value['paymentsByDueDate'] === undefined) return false;
    return true;
}

export function PaymentsByDueDateFromJSON(json: any): PaymentsByDueDate {
    return PaymentsByDueDateFromJSONTyped(json, false);
}

export function PaymentsByDueDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsByDueDate {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentsByDueDate': json['payments_by_due_date'],
    };
}

  export function PaymentsByDueDateToJSON(json: any): PaymentsByDueDate {
      return PaymentsByDueDateToJSONTyped(json, false);
  }

  export function PaymentsByDueDateToJSONTyped(value?: PaymentsByDueDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payments_by_due_date': value['paymentsByDueDate'],
    };
}

