/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupListEntry
 */
export interface PickupListEntry {
    /**
     * 
     * @type {string}
     * @memberof PickupListEntry
     */
    memberId: string;
    /**
     * 
     * @type {string}
     * @memberof PickupListEntry
     */
    memberName: string;
    /**
     * 
     * @type {number}
     * @memberof PickupListEntry
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PickupListEntry
     */
    totalAssigned: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof PickupListEntry
     */
    breadCounts: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof PickupListEntry
     */
    breadPreferred: { [key: string]: boolean; };
    /**
     * 
     * @type {Array<{ [key: string]: string | null; }>}
     * @memberof PickupListEntry
     */
    breads: Array<{ [key: string]: string | null; }>;
}

/**
 * Check if a given object implements the PickupListEntry interface.
 */
export function instanceOfPickupListEntry(value: object): value is PickupListEntry {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalAssigned' in value) || value['totalAssigned'] === undefined) return false;
    if (!('breadCounts' in value) || value['breadCounts'] === undefined) return false;
    if (!('breadPreferred' in value) || value['breadPreferred'] === undefined) return false;
    if (!('breads' in value) || value['breads'] === undefined) return false;
    return true;
}

export function PickupListEntryFromJSON(json: any): PickupListEntry {
    return PickupListEntryFromJSONTyped(json, false);
}

export function PickupListEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupListEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'],
        'memberName': json['member_name'],
        'total': json['total'],
        'totalAssigned': json['total_assigned'],
        'breadCounts': json['bread_counts'],
        'breadPreferred': json['bread_preferred'],
        'breads': json['breads'],
    };
}

  export function PickupListEntryToJSON(json: any): PickupListEntry {
      return PickupListEntryToJSONTyped(json, false);
  }

  export function PickupListEntryToJSONTyped(value?: PickupListEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
        'member_name': value['memberName'],
        'total': value['total'],
        'total_assigned': value['totalAssigned'],
        'bread_counts': value['breadCounts'],
        'bread_preferred': value['breadPreferred'],
        'breads': value['breads'],
    };
}

