/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupLocationCapacityChangePoint
 */
export interface PickupLocationCapacityChangePoint {
    /**
     * 
     * @type {Date}
     * @memberof PickupLocationCapacityChangePoint
     */
    date: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof PickupLocationCapacityChangePoint
     */
    values: Array<string>;
}

/**
 * Check if a given object implements the PickupLocationCapacityChangePoint interface.
 */
export function instanceOfPickupLocationCapacityChangePoint(value: object): value is PickupLocationCapacityChangePoint {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function PickupLocationCapacityChangePointFromJSON(json: any): PickupLocationCapacityChangePoint {
    return PickupLocationCapacityChangePointFromJSONTyped(json, false);
}

export function PickupLocationCapacityChangePointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupLocationCapacityChangePoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'values': json['values'],
    };
}

  export function PickupLocationCapacityChangePointToJSON(json: any): PickupLocationCapacityChangePoint {
      return PickupLocationCapacityChangePointToJSONTyped(json, false);
  }

  export function PickupLocationCapacityChangePointToJSONTyped(value?: PickupLocationCapacityChangePoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString().substring(0,10)),
        'values': value['values'],
    };
}

