/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PickupStationDeliveryDay } from './PickupStationDeliveryDay';
import {
    PickupStationDeliveryDayFromJSON,
    PickupStationDeliveryDayFromJSONTyped,
    PickupStationDeliveryDayToJSON,
    PickupStationDeliveryDayToJSONTyped,
} from './PickupStationDeliveryDay';

/**
 * 
 * @export
 * @interface PickupStationsByDeliveryDayResponse
 */
export interface PickupStationsByDeliveryDayResponse {
    /**
     * 
     * @type {Array<PickupStationDeliveryDay>}
     * @memberof PickupStationsByDeliveryDayResponse
     */
    pickupStations: Array<PickupStationDeliveryDay>;
}

/**
 * Check if a given object implements the PickupStationsByDeliveryDayResponse interface.
 */
export function instanceOfPickupStationsByDeliveryDayResponse(value: object): value is PickupStationsByDeliveryDayResponse {
    if (!('pickupStations' in value) || value['pickupStations'] === undefined) return false;
    return true;
}

export function PickupStationsByDeliveryDayResponseFromJSON(json: any): PickupStationsByDeliveryDayResponse {
    return PickupStationsByDeliveryDayResponseFromJSONTyped(json, false);
}

export function PickupStationsByDeliveryDayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupStationsByDeliveryDayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pickupStations': ((json['pickup_stations'] as Array<any>).map(PickupStationDeliveryDayFromJSON)),
    };
}

  export function PickupStationsByDeliveryDayResponseToJSON(json: any): PickupStationsByDeliveryDayResponse {
      return PickupStationsByDeliveryDayResponseToJSONTyped(json, false);
  }

  export function PickupStationsByDeliveryDayResponseToJSONTyped(value?: PickupStationsByDeliveryDayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pickup_stations': ((value['pickupStations'] as Array<any>).map(PickupStationDeliveryDayToJSON)),
    };
}

