/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PickupLocationDeliveryDay } from './PickupLocationDeliveryDay';
import {
    PickupLocationDeliveryDayFromJSON,
    PickupLocationDeliveryDayFromJSONTyped,
    PickupLocationDeliveryDayToJSON,
    PickupLocationDeliveryDayToJSONTyped,
} from './PickupLocationDeliveryDay';

/**
 * 
 * @export
 * @interface PickupLocationsByDeliveryDayResponse
 */
export interface PickupLocationsByDeliveryDayResponse {
    /**
     * 
     * @type {Array<PickupLocationDeliveryDay>}
     * @memberof PickupLocationsByDeliveryDayResponse
     */
    pickupLocations: Array<PickupLocationDeliveryDay>;
}

/**
 * Check if a given object implements the PickupLocationsByDeliveryDayResponse interface.
 */
export function instanceOfPickupLocationsByDeliveryDayResponse(value: object): value is PickupLocationsByDeliveryDayResponse {
    if (!('pickupLocations' in value) || value['pickupLocations'] === undefined) return false;
    return true;
}

export function PickupLocationsByDeliveryDayResponseFromJSON(json: any): PickupLocationsByDeliveryDayResponse {
    return PickupLocationsByDeliveryDayResponseFromJSONTyped(json, false);
}

export function PickupLocationsByDeliveryDayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupLocationsByDeliveryDayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pickupLocations': ((json['pickup_locations'] as Array<any>).map(PickupLocationDeliveryDayFromJSON)),
    };
}

  export function PickupLocationsByDeliveryDayResponseToJSON(json: any): PickupLocationsByDeliveryDayResponse {
      return PickupLocationsByDeliveryDayResponseToJSONTyped(json, false);
  }

  export function PickupLocationsByDeliveryDayResponseToJSONTyped(value?: PickupLocationsByDeliveryDayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pickup_locations': ((value['pickupLocations'] as Array<any>).map(PickupLocationDeliveryDayToJSON)),
    };
}

