/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreferredLabelBulkUpdateRequest
 */
export interface PreferredLabelBulkUpdateRequest {
    /**
     * List of BreadLabel IDs to set as preferred for the member.
     * @type {Array<string>}
     * @memberof PreferredLabelBulkUpdateRequest
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the PreferredLabelBulkUpdateRequest interface.
 */
export function instanceOfPreferredLabelBulkUpdateRequest(value: object): value is PreferredLabelBulkUpdateRequest {
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function PreferredLabelBulkUpdateRequestFromJSON(json: any): PreferredLabelBulkUpdateRequest {
    return PreferredLabelBulkUpdateRequestFromJSONTyped(json, false);
}

export function PreferredLabelBulkUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferredLabelBulkUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': json['labels'],
    };
}

  export function PreferredLabelBulkUpdateRequestToJSON(json: any): PreferredLabelBulkUpdateRequest {
      return PreferredLabelBulkUpdateRequestToJSONTyped(json, false);
  }

  export function PreferredLabelBulkUpdateRequestToJSONTyped(value?: PreferredLabelBulkUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labels': value['labels'],
    };
}

