/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreferredBreadsBulkUpdate
 */
export interface PreferredBreadsBulkUpdate {
    /**
     * List of Bread IDs to set as preferred for the member.
     * @type {Array<string>}
     * @memberof PreferredBreadsBulkUpdate
     */
    breads: Array<string>;
}

/**
 * Check if a given object implements the PreferredBreadsBulkUpdate interface.
 */
export function instanceOfPreferredBreadsBulkUpdate(value: object): value is PreferredBreadsBulkUpdate {
    if (!('breads' in value) || value['breads'] === undefined) return false;
    return true;
}

export function PreferredBreadsBulkUpdateFromJSON(json: any): PreferredBreadsBulkUpdate {
    return PreferredBreadsBulkUpdateFromJSONTyped(json, false);
}

export function PreferredBreadsBulkUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferredBreadsBulkUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'breads': json['breads'],
    };
}

  export function PreferredBreadsBulkUpdateToJSON(json: any): PreferredBreadsBulkUpdate {
      return PreferredBreadsBulkUpdateToJSONTyped(json, false);
  }

  export function PreferredBreadsBulkUpdateToJSONTyped(value?: PreferredBreadsBulkUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'breads': value['breads'],
    };
}

