/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreferredLabel
 */
export interface PreferredLabel {
    /**
     * 
     * @type {string}
     * @memberof PreferredLabel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PreferredLabel
     */
    readonly memberId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PreferredLabel
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the PreferredLabel interface.
 */
export function instanceOfPreferredLabel(value: object): value is PreferredLabel {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function PreferredLabelFromJSON(json: any): PreferredLabel {
    return PreferredLabelFromJSONTyped(json, false);
}

export function PreferredLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferredLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'memberId': json['member_id'],
        'labels': json['labels'],
    };
}

  export function PreferredLabelToJSON(json: any): PreferredLabel {
      return PreferredLabelToJSONTyped(json, false);
  }

  export function PreferredLabelToJSONTyped(value?: Omit<PreferredLabel, 'member_id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'labels': value['labels'],
    };
}

