/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PreferredBread
 */
export interface PreferredBread {
  /**
   *
   * @type {string}
   * @memberof PreferredBread
   */
  readonly id: string;
  /**
   *
   * @type {string}
   * @memberof PreferredBread
   */
  readonly memberId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PreferredBread
   */
  breads: Array<string>;
}

/**
 * Check if a given object implements the PreferredBread interface.
 */
export function instanceOfPreferredBread(
  value: object,
): value is PreferredBread {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("memberId" in value) || value["memberId"] === undefined) return false;
  if (!("breads" in value) || value["breads"] === undefined) return false;
  return true;
}

export function PreferredBreadFromJSON(json: any): PreferredBread {
  return PreferredBreadFromJSONTyped(json, false);
}

export function PreferredBreadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreferredBread {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    memberId: json["member_id"],
    breads: json["breads"],
  };
}

export function PreferredBreadToJSON(json: any): PreferredBread {
  return PreferredBreadToJSONTyped(json, false);
}

export function PreferredBreadToJSONTyped(
  value?: Omit<PreferredBread, "id" | "member_id"> | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    breads: value["breads"],
  };
}
