/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreferredLabelRequest
 */
export interface PreferredLabelRequest {
    /**
     * 
     * @type {string}
     * @memberof PreferredLabelRequest
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PreferredLabelRequest
     */
    labels: Array<string>;
}

/**
 * Check if a given object implements the PreferredLabelRequest interface.
 */
export function instanceOfPreferredLabelRequest(value: object): value is PreferredLabelRequest {
    if (!('labels' in value) || value['labels'] === undefined) return false;
    return true;
}

export function PreferredLabelRequestFromJSON(json: any): PreferredLabelRequest {
    return PreferredLabelRequestFromJSONTyped(json, false);
}

export function PreferredLabelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferredLabelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'labels': json['labels'],
    };
}

  export function PreferredLabelRequestToJSON(json: any): PreferredLabelRequest {
      return PreferredLabelRequestToJSONTyped(json, false);
  }

  export function PreferredLabelRequestToJSONTyped(value?: PreferredLabelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'labels': value['labels'],
    };
}

