/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DeliveryCycleEnum } from "./DeliveryCycleEnum";
import {
  DeliveryCycleEnumFromJSON,
  DeliveryCycleEnumFromJSONTyped,
  DeliveryCycleEnumToJSON,
  DeliveryCycleEnumToJSONTyped,
} from "./DeliveryCycleEnum";

/**
 *
 * @export
 * @interface ProductType
 */
export interface ProductType {
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof ProductType
   */
  readonly createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ProductType
   */
  readonly updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  name: string;
  /**
   *
   * @type {DeliveryCycleEnum}
   * @memberof ProductType
   */
  deliveryCycle?: DeliveryCycleEnum;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  contractLink?: string | null;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  iconLink?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof ProductType
   */
  singleSubscriptionOnly?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ProductType
   */
  isAffectedByJokers?: boolean;
  /**
   * Bestimmte Produkte wie Vereinsmitgliedschaften laufen permanent bis sie gekündigt werden und haben nicht zwangsläufig ein End-Datum. Solche Produkte sind nicht mit Vertragsperiode verbunden.
   * @type {boolean}
   * @memberof ProductType
   */
  subscriptionsHaveEndDates?: boolean;
  /**
   * Ob es Pflicht ist, ein Abonnement an dieses Produkt zu zu zeichnen.
   * @type {boolean}
   * @memberof ProductType
   */
  mustBeSubscribedTo?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ProductType
   */
  isAssociationMembership?: boolean;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  descriptionBestellwizardShort?: string;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  descriptionBestellwizardLong?: string;
  /**
   *
   * @type {number}
   * @memberof ProductType
   */
  orderInBestellwizard?: number;
  /**
   *
   * @type {boolean}
   * @memberof ProductType
   */
  forceWaitingList?: boolean;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  titleBestellwizardIntro?: string;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  titleBestellwizardProductChoice?: string;
  /**
   *
   * @type {string}
   * @memberof ProductType
   */
  backgroundImageInBestellwizard?: string;
}

/**
 * Check if a given object implements the ProductType interface.
 */
export function instanceOfProductType(value: object): value is ProductType {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function ProductTypeFromJSON(json: any): ProductType {
  return ProductTypeFromJSONTyped(json, false);
}

export function ProductTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProductType {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
    name: json["name"],
    deliveryCycle:
      json["delivery_cycle"] == null
        ? undefined
        : DeliveryCycleEnumFromJSON(json["delivery_cycle"]),
    contractLink:
      json["contract_link"] == null ? undefined : json["contract_link"],
    iconLink: json["icon_link"] == null ? undefined : json["icon_link"],
    singleSubscriptionOnly:
      json["single_subscription_only"] == null
        ? undefined
        : json["single_subscription_only"],
    isAffectedByJokers:
      json["is_affected_by_jokers"] == null
        ? undefined
        : json["is_affected_by_jokers"],
    subscriptionsHaveEndDates:
      json["subscriptions_have_end_dates"] == null
        ? undefined
        : json["subscriptions_have_end_dates"],
    mustBeSubscribedTo:
      json["must_be_subscribed_to"] == null
        ? undefined
        : json["must_be_subscribed_to"],
    isAssociationMembership:
      json["is_association_membership"] == null
        ? undefined
        : json["is_association_membership"],
    descriptionBestellwizardShort:
      json["description_bestellwizard_short"] == null
        ? undefined
        : json["description_bestellwizard_short"],
    descriptionBestellwizardLong:
      json["description_bestellwizard_long"] == null
        ? undefined
        : json["description_bestellwizard_long"],
    orderInBestellwizard:
      json["order_in_bestellwizard"] == null
        ? undefined
        : json["order_in_bestellwizard"],
    forceWaitingList:
      json["force_waiting_list"] == null
        ? undefined
        : json["force_waiting_list"],
    titleBestellwizardIntro:
      json["title_bestellwizard_intro"] == null
        ? undefined
        : json["title_bestellwizard_intro"],
    titleBestellwizardProductChoice:
      json["title_bestellwizard_product_choice"] == null
        ? undefined
        : json["title_bestellwizard_product_choice"],
    backgroundImageInBestellwizard:
      json["background_image_in_bestellwizard"] == null
        ? undefined
        : json["background_image_in_bestellwizard"],
  };
}

export function ProductTypeToJSON(json: any): ProductType {
  return ProductTypeToJSONTyped(json, false);
}

export function ProductTypeToJSONTyped(
  value?: Omit<ProductType, "created_at" | "updated_at"> | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    delivery_cycle: DeliveryCycleEnumToJSON(value["deliveryCycle"]),
    contract_link: value["contractLink"],
    icon_link: value["iconLink"],
    single_subscription_only: value["singleSubscriptionOnly"],
    is_affected_by_jokers: value["isAffectedByJokers"],
    subscriptions_have_end_dates: value["subscriptionsHaveEndDates"],
    must_be_subscribed_to: value["mustBeSubscribedTo"],
    is_association_membership: value["isAssociationMembership"],
    description_bestellwizard_short: value["descriptionBestellwizardShort"],
    description_bestellwizard_long: value["descriptionBestellwizardLong"],
    order_in_bestellwizard: value["orderInBestellwizard"],
    force_waiting_list: value["forceWaitingList"],
    title_bestellwizard_intro: value["titleBestellwizardIntro"],
    title_bestellwizard_product_choice:
      value["titleBestellwizardProductChoice"],
    background_image_in_bestellwizard: value["backgroundImageInBestellwizard"],
  };
}
