/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProductType } from "./ProductType";
import { ProductTypeFromJSON, ProductTypeToJSON } from "./ProductType";

/**
 * 
 * @export
 * @interface ProductTypesAndConfig
 */
export interface ProductTypesAndConfig {
    /**
     * 
     * @type {Array<ProductType>}
     * @memberof ProductTypesAndConfig
     */
    productTypesWithoutCapacity: Array<ProductType>;
    /**
     * 
     * @type {boolean}
     * @memberof ProductTypesAndConfig
     */
    showNoticePeriod: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductTypesAndConfig
     */
    showJokers: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductTypesAndConfig
     */
    showAssociationMembership: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProductTypesAndConfig
     */
    deliveryCycleOptions: { [key: string]: any; };
}

/**
 * Check if a given object implements the ProductTypesAndConfig interface.
 */
export function instanceOfProductTypesAndConfig(value: object): value is ProductTypesAndConfig {
    if (!('productTypesWithoutCapacity' in value) || value['productTypesWithoutCapacity'] === undefined) return false;
    if (!('showNoticePeriod' in value) || value['showNoticePeriod'] === undefined) return false;
    if (!('showJokers' in value) || value['showJokers'] === undefined) return false;
    if (!('showAssociationMembership' in value) || value['showAssociationMembership'] === undefined) return false;
    if (!('deliveryCycleOptions' in value) || value['deliveryCycleOptions'] === undefined) return false;
    return true;
}

export function ProductTypesAndConfigFromJSON(json: any): ProductTypesAndConfig {
    return ProductTypesAndConfigFromJSONTyped(json, false);
}

export function ProductTypesAndConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTypesAndConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'productTypesWithoutCapacity': ((json['product_types_without_capacity'] as Array<any>).map(ProductTypeFromJSON)),
        'showNoticePeriod': json['show_notice_period'],
        'showJokers': json['show_jokers'],
        'showAssociationMembership': json['show_association_membership'],
        'deliveryCycleOptions': json['delivery_cycle_options'],
    };
}

  export function ProductTypesAndConfigToJSON(json: any): ProductTypesAndConfig {
      return ProductTypesAndConfigToJSONTyped(json, false);
  }

  export function ProductTypesAndConfigToJSONTyped(value?: ProductTypesAndConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_types_without_capacity': ((value['productTypesWithoutCapacity'] as Array<any>).map(ProductTypeToJSON)),
        'show_notice_period': value['showNoticePeriod'],
        'show_jokers': value['showJokers'],
        'show_association_membership': value['showAssociationMembership'],
        'delivery_cycle_options': value['deliveryCycleOptions'],
    };
}

