/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SolidarityContributionCancellationData
 */
export interface SolidarityContributionCancellationData {
  /**
   *
   * @type {boolean}
   * @memberof SolidarityContributionCancellationData
   */
  _exists: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SolidarityContributionCancellationData
   */
  isInTrial: boolean;
  /**
   *
   * @type {Date}
   * @memberof SolidarityContributionCancellationData
   */
  cancellationDate: Date;
}

/**
 * Check if a given object implements the SolidarityContributionCancellationData interface.
 */
export function instanceOfSolidarityContributionCancellationData(
  value: object,
): value is SolidarityContributionCancellationData {
  if (!("_exists" in value) || value["_exists"] === undefined) return false;
  if (!("isInTrial" in value) || value["isInTrial"] === undefined) return false;
  if (!("cancellationDate" in value) || value["cancellationDate"] === undefined)
    return false;
  return true;
}

export function SolidarityContributionCancellationDataFromJSON(
  json: any,
): SolidarityContributionCancellationData {
  return SolidarityContributionCancellationDataFromJSONTyped(json, false);
}

export function SolidarityContributionCancellationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SolidarityContributionCancellationData {
  if (json == null) {
    return json;
  }
  return {
    _exists: json["exists"],
    isInTrial: json["is_in_trial"],
    cancellationDate: new Date(json["cancellation_date"]),
  };
}

export function SolidarityContributionCancellationDataToJSON(
  json: any,
): SolidarityContributionCancellationData {
  return SolidarityContributionCancellationDataToJSONTyped(json, false);
}

export function SolidarityContributionCancellationDataToJSONTyped(
  value?: SolidarityContributionCancellationData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    exists: value["_exists"],
    is_in_trial: value["isInTrial"],
    cancellation_date: value["cancellationDate"].toISOString().substring(0, 10),
  };
}
