/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolverPreviewSolutionSummary } from './SolverPreviewSolutionSummary';
import {
    SolverPreviewSolutionSummaryFromJSON,
    SolverPreviewSolutionSummaryFromJSONTyped,
    SolverPreviewSolutionSummaryToJSON,
    SolverPreviewSolutionSummaryToJSONTyped,
} from './SolverPreviewSolutionSummary';

/**
 * 
 * @export
 * @interface SolverPreviewResponse
 */
export interface SolverPreviewResponse {
    /**
     * 
     * @type {number}
     * @memberof SolverPreviewResponse
     */
    totalSolutions: number;
    /**
     * 
     * @type {Array<SolverPreviewSolutionSummary>}
     * @memberof SolverPreviewResponse
     */
    solutions: Array<SolverPreviewSolutionSummary>;
}

/**
 * Check if a given object implements the SolverPreviewResponse interface.
 */
export function instanceOfSolverPreviewResponse(value: object): value is SolverPreviewResponse {
    if (!('totalSolutions' in value) || value['totalSolutions'] === undefined) return false;
    if (!('solutions' in value) || value['solutions'] === undefined) return false;
    return true;
}

export function SolverPreviewResponseFromJSON(json: any): SolverPreviewResponse {
    return SolverPreviewResponseFromJSONTyped(json, false);
}

export function SolverPreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolverPreviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSolutions': json['total_solutions'],
        'solutions': ((json['solutions'] as Array<any>).map(SolverPreviewSolutionSummaryFromJSON)),
    };
}

  export function SolverPreviewResponseToJSON(json: any): SolverPreviewResponse {
      return SolverPreviewResponseToJSONTyped(json, false);
  }

  export function SolverPreviewResponseToJSONTyped(value?: SolverPreviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_solutions': value['totalSolutions'],
        'solutions': ((value['solutions'] as Array<any>).map(SolverPreviewSolutionSummaryToJSON)),
    };
}

