/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolverPreviewDetailDistribution
 */
export interface SolverPreviewDetailDistribution {
    /**
     * 
     * @type {string}
     * @memberof SolverPreviewDetailDistribution
     */
    breadId: string;
    /**
     * 
     * @type {string}
     * @memberof SolverPreviewDetailDistribution
     */
    breadName: string;
    /**
     * 
     * @type {string}
     * @memberof SolverPreviewDetailDistribution
     */
    pickupLocationId: string;
    /**
     * 
     * @type {string}
     * @memberof SolverPreviewDetailDistribution
     */
    pickupLocationName: string;
    /**
     * 
     * @type {number}
     * @memberof SolverPreviewDetailDistribution
     */
    count: number;
}

/**
 * Check if a given object implements the SolverPreviewDetailDistribution interface.
 */
export function instanceOfSolverPreviewDetailDistribution(value: object): value is SolverPreviewDetailDistribution {
    if (!('breadId' in value) || value['breadId'] === undefined) return false;
    if (!('breadName' in value) || value['breadName'] === undefined) return false;
    if (!('pickupLocationId' in value) || value['pickupLocationId'] === undefined) return false;
    if (!('pickupLocationName' in value) || value['pickupLocationName'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function SolverPreviewDetailDistributionFromJSON(json: any): SolverPreviewDetailDistribution {
    return SolverPreviewDetailDistributionFromJSONTyped(json, false);
}

export function SolverPreviewDetailDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolverPreviewDetailDistribution {
    if (json == null) {
        return json;
    }
    return {
        
        'breadId': json['bread_id'],
        'breadName': json['bread_name'],
        'pickupLocationId': json['pickup_location_id'],
        'pickupLocationName': json['pickup_location_name'],
        'count': json['count'],
    };
}

  export function SolverPreviewDetailDistributionToJSON(json: any): SolverPreviewDetailDistribution {
      return SolverPreviewDetailDistributionToJSONTyped(json, false);
  }

  export function SolverPreviewDetailDistributionToJSONTyped(value?: SolverPreviewDetailDistribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bread_id': value['breadId'],
        'bread_name': value['breadName'],
        'pickup_location_id': value['pickupLocationId'],
        'pickup_location_name': value['pickupLocationName'],
        'count': value['count'],
    };
}

