/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolverPreviewDetailStoveLayer
 */
export interface SolverPreviewDetailStoveLayer {
    /**
     * 
     * @type {number}
     * @memberof SolverPreviewDetailStoveLayer
     */
    layer: number;
    /**
     * 
     * @type {string}
     * @memberof SolverPreviewDetailStoveLayer
     */
    breadId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SolverPreviewDetailStoveLayer
     */
    breadName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SolverPreviewDetailStoveLayer
     */
    quantity: number;
}

/**
 * Check if a given object implements the SolverPreviewDetailStoveLayer interface.
 */
export function instanceOfSolverPreviewDetailStoveLayer(value: object): value is SolverPreviewDetailStoveLayer {
    if (!('layer' in value) || value['layer'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function SolverPreviewDetailStoveLayerFromJSON(json: any): SolverPreviewDetailStoveLayer {
    return SolverPreviewDetailStoveLayerFromJSONTyped(json, false);
}

export function SolverPreviewDetailStoveLayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolverPreviewDetailStoveLayer {
    if (json == null) {
        return json;
    }
    return {
        
        'layer': json['layer'],
        'breadId': json['bread_id'] == null ? undefined : json['bread_id'],
        'breadName': json['bread_name'] == null ? undefined : json['bread_name'],
        'quantity': json['quantity'],
    };
}

  export function SolverPreviewDetailStoveLayerToJSON(json: any): SolverPreviewDetailStoveLayer {
      return SolverPreviewDetailStoveLayerToJSONTyped(json, false);
  }

  export function SolverPreviewDetailStoveLayerToJSONTyped(value?: SolverPreviewDetailStoveLayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layer': value['layer'],
        'bread_id': value['breadId'],
        'bread_name': value['breadName'],
        'quantity': value['quantity'],
    };
}

