/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StaticSegmentRecipient } from "./StaticSegmentRecipient";
import { StaticSegmentRecipientFromJSON } from "./StaticSegmentRecipient";

/**
 *
 * @export
 * @interface StaticSegment
 */
export interface StaticSegment {
  /**
   *
   * @type {string}
   * @memberof StaticSegment
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof StaticSegment
   */
  name: string;
  /**
   *
   * @type {Array<StaticSegmentRecipient>}
   * @memberof StaticSegment
   */
  readonly recipients: Array<StaticSegmentRecipient>;
  /**
   *
   * @type {boolean}
   * @memberof StaticSegment
   */
  readonly belongsToACategory: boolean;
}

/**
 * Check if a given object implements the StaticSegment interface.
 */
export function instanceOfStaticSegment(value: object): value is StaticSegment {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("recipients" in value) || value["recipients"] === undefined)
    return false;
  if (
    !("belongsToACategory" in value) ||
    value["belongsToACategory"] === undefined
  )
    return false;
  return true;
}

export function StaticSegmentFromJSON(json: any): StaticSegment {
  return StaticSegmentFromJSONTyped(json, false);
}

export function StaticSegmentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StaticSegment {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"],
    recipients: (json["recipients"] as Array<any>).map(
      StaticSegmentRecipientFromJSON,
    ),
    belongsToACategory: json["belongs_to_a_category"],
  };
}

export function StaticSegmentToJSON(json: any): StaticSegment {
  return StaticSegmentToJSONTyped(json, false);
}

export function StaticSegmentToJSONTyped(
  value?: Omit<StaticSegment, "recipients" | "belongs_to_a_category"> | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
  };
}
