/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoveLayer
 */
export interface StoveLayer {
    /**
     * 
     * @type {number}
     * @memberof StoveLayer
     */
    layer: number;
    /**
     * 
     * @type {string}
     * @memberof StoveLayer
     */
    breadId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoveLayer
     */
    breadName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoveLayer
     */
    bread?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StoveLayer
     */
    quantity: number;
}

/**
 * Check if a given object implements the StoveLayer interface.
 */
export function instanceOfStoveLayer(value: object): value is StoveLayer {
    if (!('layer' in value) || value['layer'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function StoveLayerFromJSON(json: any): StoveLayer {
    return StoveLayerFromJSONTyped(json, false);
}

export function StoveLayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoveLayer {
    if (json == null) {
        return json;
    }
    return {
        
        'layer': json['layer'],
        'breadId': json['bread_id'] == null ? undefined : json['bread_id'],
        'breadName': json['bread_name'] == null ? undefined : json['bread_name'],
        'bread': json['bread'] == null ? undefined : json['bread'],
        'quantity': json['quantity'],
    };
}

  export function StoveLayerToJSON(json: any): StoveLayer {
      return StoveLayerToJSONTyped(json, false);
  }

  export function StoveLayerToJSONTyped(value?: StoveLayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layer': value['layer'],
        'bread_id': value['breadId'],
        'bread_name': value['breadName'],
        'bread': value['bread'],
        'quantity': value['quantity'],
    };
}

