/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubscriptionDateChangeRequestRequest
 */
export interface SubscriptionDateChangeRequestRequest {
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDateChangeRequestRequest
   */
  startDateIsOnPeriodStart: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDateChangeRequestRequest
   */
  endDateIsOnPeriodEnd: boolean;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDateChangeRequestRequest
   */
  startWeek: number;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDateChangeRequestRequest
   */
  endWeek: number;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDateChangeRequestRequest
   */
  subscriptionId: string;
}

/**
 * Check if a given object implements the SubscriptionDateChangeRequestRequest interface.
 */
export function instanceOfSubscriptionDateChangeRequestRequest(
  value: object,
): value is SubscriptionDateChangeRequestRequest {
  if (
    !("startDateIsOnPeriodStart" in value) ||
    value["startDateIsOnPeriodStart"] === undefined
  )
    return false;
  if (
    !("endDateIsOnPeriodEnd" in value) ||
    value["endDateIsOnPeriodEnd"] === undefined
  )
    return false;
  if (!("startWeek" in value) || value["startWeek"] === undefined) return false;
  if (!("endWeek" in value) || value["endWeek"] === undefined) return false;
  if (!("subscriptionId" in value) || value["subscriptionId"] === undefined)
    return false;
  return true;
}

export function SubscriptionDateChangeRequestRequestFromJSON(
  json: any,
): SubscriptionDateChangeRequestRequest {
  return SubscriptionDateChangeRequestRequestFromJSONTyped(json, false);
}

export function SubscriptionDateChangeRequestRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubscriptionDateChangeRequestRequest {
  if (json == null) {
    return json;
  }
  return {
    startDateIsOnPeriodStart: json["start_date_is_on_period_start"],
    endDateIsOnPeriodEnd: json["end_date_is_on_period_end"],
    startWeek: json["start_week"],
    endWeek: json["end_week"],
    subscriptionId: json["subscription_id"],
  };
}

export function SubscriptionDateChangeRequestRequestToJSON(
  json: any,
): SubscriptionDateChangeRequestRequest {
  return SubscriptionDateChangeRequestRequestToJSONTyped(json, false);
}

export function SubscriptionDateChangeRequestRequestToJSONTyped(
  value?: SubscriptionDateChangeRequestRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    start_date_is_on_period_start: value["startDateIsOnPeriodStart"],
    end_date_is_on_period_end: value["endDateIsOnPeriodEnd"],
    start_week: value["startWeek"],
    end_week: value["endWeek"],
    subscription_id: value["subscriptionId"],
  };
}
