/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TapirmailApiSegmentCombineCreate200ResponseRecipientsInner
 */
export interface TapirmailApiSegmentCombineCreate200ResponseRecipientsInner {
  /**
   *
   * @type {string}
   * @memberof TapirmailApiSegmentCombineCreate200ResponseRecipientsInner
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof TapirmailApiSegmentCombineCreate200ResponseRecipientsInner
   */
  email?: string;
}

/**
 * Check if a given object implements the TapirmailApiSegmentCombineCreate200ResponseRecipientsInner interface.
 */
export function instanceOfTapirmailApiSegmentCombineCreate200ResponseRecipientsInner(
  value: object,
): value is TapirmailApiSegmentCombineCreate200ResponseRecipientsInner {
  return true;
}

export function TapirmailApiSegmentCombineCreate200ResponseRecipientsInnerFromJSON(
  json: any,
): TapirmailApiSegmentCombineCreate200ResponseRecipientsInner {
  return TapirmailApiSegmentCombineCreate200ResponseRecipientsInnerFromJSONTyped(
    json,
    false,
  );
}

export function TapirmailApiSegmentCombineCreate200ResponseRecipientsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TapirmailApiSegmentCombineCreate200ResponseRecipientsInner {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    email: json["email"] == null ? undefined : json["email"],
  };
}

export function TapirmailApiSegmentCombineCreate200ResponseRecipientsInnerToJSON(
  json: any,
): TapirmailApiSegmentCombineCreate200ResponseRecipientsInner {
  return TapirmailApiSegmentCombineCreate200ResponseRecipientsInnerToJSONTyped(
    json,
    false,
  );
}

export function TapirmailApiSegmentCombineCreate200ResponseRecipientsInnerToJSONTyped(
  value?: TapirmailApiSegmentCombineCreate200ResponseRecipientsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    email: value["email"],
  };
}
