/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateMemberBankDataRequestRequest
 */
export interface UpdateMemberBankDataRequestRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMemberBankDataRequestRequest
   */
  memberId: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMemberBankDataRequestRequest
   */
  iban: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMemberBankDataRequestRequest
   */
  accountOwner: string;
  /**
   *
   * @type {boolean}
   * @memberof UpdateMemberBankDataRequestRequest
   */
  sepaConsent: boolean;
}

/**
 * Check if a given object implements the UpdateMemberBankDataRequestRequest interface.
 */
export function instanceOfUpdateMemberBankDataRequestRequest(
  value: object,
): value is UpdateMemberBankDataRequestRequest {
  if (!("memberId" in value) || value["memberId"] === undefined) return false;
  if (!("iban" in value) || value["iban"] === undefined) return false;
  if (!("accountOwner" in value) || value["accountOwner"] === undefined)
    return false;
  if (!("sepaConsent" in value) || value["sepaConsent"] === undefined)
    return false;
  return true;
}

export function UpdateMemberBankDataRequestRequestFromJSON(
  json: any,
): UpdateMemberBankDataRequestRequest {
  return UpdateMemberBankDataRequestRequestFromJSONTyped(json, false);
}

export function UpdateMemberBankDataRequestRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateMemberBankDataRequestRequest {
  if (json == null) {
    return json;
  }
  return {
    memberId: json["member_id"],
    iban: json["iban"],
    accountOwner: json["account_owner"],
    sepaConsent: json["sepa_consent"],
  };
}

export function UpdateMemberBankDataRequestRequestToJSON(
  json: any,
): UpdateMemberBankDataRequestRequest {
  return UpdateMemberBankDataRequestRequestToJSONTyped(json, false);
}

export function UpdateMemberBankDataRequestRequestToJSONTyped(
  value?: UpdateMemberBankDataRequestRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    member_id: value["memberId"],
    iban: value["iban"],
    account_owner: value["accountOwner"],
    sepa_consent: value["sepaConsent"],
  };
}
