/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberCountry } from './MemberCountry';
import {
    MemberCountryFromJSON,
    MemberCountryFromJSONTyped,
    MemberCountryToJSON,
    MemberCountryToJSONTyped,
} from './MemberCountry';

/**
 * 
 * @export
 * @interface WaitingListEntryRequest
 */
export interface WaitingListEntryRequest {
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    street2?: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    city?: string;
    /**
     * 
     * @type {MemberCountry}
     * @memberof WaitingListEntryRequest
     */
    country?: MemberCountry;
    /**
     * 
     * @type {Date}
     * @memberof WaitingListEntryRequest
     */
    privacyConsent: Date;
    /**
     * 
     * @type {number}
     * @memberof WaitingListEntryRequest
     */
    numberOfCoopShares: number;
    /**
     * 
     * @type {Date}
     * @memberof WaitingListEntryRequest
     */
    desiredStartDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    confirmationLinkKey?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WaitingListEntryRequest
     */
    linkSentDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WaitingListEntryRequest
     */
    member?: string | null;
}

/**
 * Check if a given object implements the WaitingListEntryRequest interface.
 */
export function instanceOfWaitingListEntryRequest(value: object): value is WaitingListEntryRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('privacyConsent' in value) || value['privacyConsent'] === undefined) return false;
    if (!('numberOfCoopShares' in value) || value['numberOfCoopShares'] === undefined) return false;
    return true;
}

export function WaitingListEntryRequestFromJSON(json: any): WaitingListEntryRequest {
    return WaitingListEntryRequestFromJSONTyped(json, false);
}

export function WaitingListEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitingListEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'phoneNumber': json['phone_number'],
        'email': json['email'],
        'street': json['street'] == null ? undefined : json['street'],
        'street2': json['street_2'] == null ? undefined : json['street_2'],
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : MemberCountryFromJSON(json['country']),
        'privacyConsent': (new Date(json['privacy_consent'])),
        'numberOfCoopShares': json['number_of_coop_shares'],
        'desiredStartDate': json['desired_start_date'] == null ? undefined : (new Date(json['desired_start_date'])),
        'comment': json['comment'] == null ? undefined : json['comment'],
        'category': json['category'] == null ? undefined : json['category'],
        'confirmationLinkKey': json['confirmation_link_key'] == null ? undefined : json['confirmation_link_key'],
        'linkSentDate': json['link_sent_date'] == null ? undefined : (new Date(json['link_sent_date'])),
        'member': json['member'] == null ? undefined : json['member'],
    };
}

  export function WaitingListEntryRequestToJSON(json: any): WaitingListEntryRequest {
      return WaitingListEntryRequestToJSONTyped(json, false);
  }

  export function WaitingListEntryRequestToJSONTyped(value?: WaitingListEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'phone_number': value['phoneNumber'],
        'email': value['email'],
        'street': value['street'],
        'street_2': value['street2'],
        'postcode': value['postcode'],
        'city': value['city'],
        'country': MemberCountryToJSON(value['country']),
        'privacy_consent': ((value['privacyConsent']).toISOString()),
        'number_of_coop_shares': value['numberOfCoopShares'],
        'desired_start_date': value['desiredStartDate'] == null ? undefined : ((value['desiredStartDate'] as any).toISOString().substring(0,10)),
        'comment': value['comment'],
        'category': value['category'],
        'confirmation_link_key': value['confirmationLinkKey'],
        'link_sent_date': value['linkSentDate'] == null ? undefined : ((value['linkSentDate'] as any).toISOString()),
        'member': value['member'],
    };
}

