/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PickupLocationRequest } from './PickupLocationRequest';
import {
    PickupLocationRequestFromJSON,
    PickupLocationRequestFromJSONTyped,
    PickupLocationRequestToJSON,
    PickupLocationRequestToJSONTyped,
} from './PickupLocationRequest';

/**
 * 
 * @export
 * @interface WaitingListPickupLocationWishRequest
 */
export interface WaitingListPickupLocationWishRequest {
    /**
     * 
     * @type {string}
     * @memberof WaitingListPickupLocationWishRequest
     */
    id?: string;
    /**
     * 
     * @type {PickupLocationRequest}
     * @memberof WaitingListPickupLocationWishRequest
     */
    pickupLocation: PickupLocationRequest;
    /**
     * 
     * @type {number}
     * @memberof WaitingListPickupLocationWishRequest
     */
    priority: number;
    /**
     * 
     * @type {string}
     * @memberof WaitingListPickupLocationWishRequest
     */
    waitingListEntry: string;
}

/**
 * Check if a given object implements the WaitingListPickupLocationWishRequest interface.
 */
export function instanceOfWaitingListPickupLocationWishRequest(value: object): value is WaitingListPickupLocationWishRequest {
    if (!('pickupLocation' in value) || value['pickupLocation'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('waitingListEntry' in value) || value['waitingListEntry'] === undefined) return false;
    return true;
}

export function WaitingListPickupLocationWishRequestFromJSON(json: any): WaitingListPickupLocationWishRequest {
    return WaitingListPickupLocationWishRequestFromJSONTyped(json, false);
}

export function WaitingListPickupLocationWishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitingListPickupLocationWishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'pickupLocation': PickupLocationRequestFromJSON(json['pickup_location']),
        'priority': json['priority'],
        'waitingListEntry': json['waiting_list_entry'],
    };
}

  export function WaitingListPickupLocationWishRequestToJSON(json: any): WaitingListPickupLocationWishRequest {
      return WaitingListPickupLocationWishRequestToJSONTyped(json, false);
  }

  export function WaitingListPickupLocationWishRequestToJSONTyped(value?: WaitingListPickupLocationWishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pickup_location': PickupLocationRequestToJSON(value['pickupLocation']),
        'priority': value['priority'],
        'waiting_list_entry': value['waitingListEntry'],
    };
}

