BESTELL_WIZARD_SOLIDARITY_STEP_POSITION_BEFORE_PICKUP_LOCATION = (
    "before_pickup_location"
)
BESTELL_WIZARD_SOLIDARITY_STEP_POSITION_BEFORE_PERSONAL_DATA = "before_personal_data"

OPTIONS_BESTELL_WIZARD_SOLIDARITY_STEP_POSITION = [
    (
        BESTELL_WIZARD_SOLIDARITY_STEP_POSITION_BEFORE_PICKUP_LOCATION,
        "Vor der Verteilstation-Seite",
    ),
    (
        BESTELL_WIZARD_SOLIDARITY_STEP_POSITION_BEFORE_PERSONAL_DATA,
        "Vor der persönliche Daten-Seite",
    ),
]
