import { BestellWizardSettings } from "../types/BestellWizardSettings.ts";

export function buildEmptySettings(): BestellWizardSettings {
  return {
    theme: "biotop",
    pickupLocations: [],
    productTypes: [],
    priceOfAShare: 0,
    allowInvestingMembership: false,
    forceWaitingList: false,
    showCoopContent: false,
    introStepText: "",
    labelCheckboxSepaMandat: "",
    labelCheckboxContractPolicy: "",
    revocationRightsExplanation: "",
    trialPeriodLengthInWeeks: 0,
    paymentRhythmChoices: {},
    studentStatusAllowed: false,
    introEnabled: false,
    productTypeIdsThatAreAlreadyAtCapacity: [],
    productIdsThatAreAlreadyAtCapacity: [],
    organizationName: "",
    coopStatuteLink: "",
    logoUrl: "",
    contactMailAddress: "",
    distributionChannels: [],
    strings: {
      step1aTitle: "",
      step1aText: "",
      step1bTitle: "",
      step1bText: "",
      step2Title: "",
      step2Text: "",
      step3Title: "",
      step3Text: "",
      step5aTitle: "",
      step5aText: "",
      step6aTitle: "",
      step6aText: "",
      step6bTitle: "",
      step6bText: "",
      step6cCheckboxStatute: "",
      step6cTextStatute: "",
      step6cCheckboxCommitment: "",
      step8Title: "",
      step9Title: "",
      step10Title: "",
      step11Title: "",
      step12Title: "",
      step13Title: "",
      step13Text: "",
      step14Title: "",
      step14Text: "",
      privacyPolicyUrl: "",
    },
  };
}
