# Generated by Django 3.2.25 on 2025-03-04 11:33

from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wirgarten", "0044_alter_productcapacity_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Joker",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="joker",
            index=models.Index(fields=["date"], name="deliveries__date_43072a_idx"),
        ),
    ]
