# Generated by Django 3.2.25 on 2025-03-25 08:06

import functools

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0048_alter_growingperiod_weeks_without_delivery"),
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDayAdjustment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar_week",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ]
                    ),
                ),
                (
                    "adjusted_weekday",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "growing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.growingperiod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
