# Generated by Django 3.2.25 on 2025-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_deliverydayadjustment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deliverydayadjustment",
            constraint=models.UniqueConstraint(
                fields=("growing_period", "calendar_week"),
                name="no_duplicate_week_by_growing_period",
            ),
        ),
    ]
