# Generated by Django 5.2.1 on 2026-01-13 14:11

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_alter_deliverydayadjustment_adjusted_weekday"),
        ("wirgarten", "0088_alter_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDonation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="deliveries__date_55f39c_idx")
                ],
            },
        ),
    ]
