# Generated by Django 5.2.1 on 2026-01-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_deliverydonation"),
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDonationCancelledLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("date", models.DateField()),
            ],
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="JokerCancelledLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("date", models.DateField()),
            ],
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="DeliveryDonationUsedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "delivery_donation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deliveries.deliverydonation",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
        migrations.CreateModel(
            name="JokerUsedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "joker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deliveries.joker",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
    ]
