# Generated by Django 6.0.1 on 2026-03-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0008_customcycledeliveryweeks"),
        ("wirgarten", "0103_alter_producttype_delivery_cycle"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomCycleDeliveryWeeks",
            new_name="CustomCycleScheduledDeliveryWeek",
        ),
    ]
