# Generated by Django 3.2.25 on 2025-03-26 11:14

import functools

import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wirgarten", "0048_alter_growingperiod_weeks_without_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTypeBasketSizeEquivalence",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("basket_size_name", models.CharField(max_length=128)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PickupLocationBasketCapacity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("basket_size_name", models.CharField(max_length=128)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.pickuplocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
