# Generated by Django 3.2.25 on 2025-03-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0048_alter_growingperiod_weeks_without_delivery"),
        ("pickup_locations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductTypeBasketSizeEquivalence",
            new_name="ProductBasketSizeEquivalence",
        ),
    ]
