# Generated by Django 3.2.25 on 2025-03-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pickup_locations",
            "0002_rename_producttypebasketsizeequivalence_productbasketsizeequivalence",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickuplocationbasketcapacity",
            name="capacity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
