# Generated by Django 5.2.1 on 2025-07-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("pickup_locations", "0003_alter_pickuplocationbasketcapacity_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupLocationChangedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("pickup_location_name", models.CharField(max_length=150)),
                ("valid_from", models.DateField()),
            ],
            bases=("log.logentry",),
        ),
    ]
