# Generated by Django 5.2.1 on 2025-07-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickup_locations", "0004_pickuplocationchangedlogentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pickuplocationchangedlogentry",
            old_name="pickup_location_name",
            new_name="new_pickup_location_name",
        ),
        migrations.AddField(
            model_name="pickuplocationchangedlogentry",
            name="old_pickup_location_name",
            field=models.CharField(default="???", max_length=150),
            preserve_default=False,
        ),
    ]
