# Generated by Django 6.0.1 on 2026-03-09 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pickup_locations",
            "0005_rename_pickup_location_name_pickuplocationchangedlogentry_new_pickup_location_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuplocationbasketcapacity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pickuplocationbasketcapacity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productbasketsizeequivalence",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productbasketsizeequivalence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
