# Generated by Django 6.0.4 on 2026-05-18 15:00

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickup_locations", "0006_pickuplocationbasketcapacity_created_at_and_more"),
        ("wirgarten", "0110_alter_memberpickuplocation_pickup_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupLocationDeliveryCharge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("valid_from", models.DateField()),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.pickuplocation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pickup_location", "valid_from"),
                        name="unique_pickup_location_delivery_charge_date",
                    )
                ],
            },
        ),
    ]
