# Generated by Django 5.2.1 on 2025-07-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListChangeConfirmedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
    ]
