# Generated by Django 5.2.1 on 2025-10-20 11:14

import functools

import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wirgarten", "0081_auto_20250815_1118"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTypeAccordionInBestellWizard",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.producttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
