# Generated by Django 6.0.1 on 2026-02-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BakeryUserProfile",
        ),
    ]
