# Generated by Django 6.0.1 on 2026-02-21 21:58

import functools

import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("bakery", "0002_delete_bakeryuserprofile"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferredLabels",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        related_name="preferred_by_members", to="bakery.breadlabel"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_labels",
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
