# Generated by Django 6.0.1 on 2026-02-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0003_preferredlabels"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PreferredLabels",
            new_name="PreferredLabel",
        ),
    ]
