# Generated by Django 6.0.1 on 2026-02-21 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0004_rename_preferredlabels_preferredlabel"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breaddelivery",
            unique_together={("subscription", "year", "delivery_week")},
        ),
        migrations.AddField(
            model_name="breaddelivery",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_pickup_locations",
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.AddField(
            model_name="breaddelivery",
            name="slot_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="breaddelivery",
            name="bread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bread_delivery_slots",
                to="bakery.bread",
            ),
        ),
        migrations.AlterField(
            model_name="breaddelivery",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_locations",
                to="wirgarten.subscription",
            ),
        ),
        migrations.RemoveField(
            model_name="breaddelivery",
            name="delivery_day",
        ),
    ]
