# Generated by Django 6.0.1 on 2026-02-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0005_alter_breaddelivery_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breaddelivery",
            unique_together=set(),
        ),
    ]
