# Generated by Django 6.0.1 on 2026-02-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0006_alter_breaddelivery_unique_together"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaddelivery",
            name="bread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bakery.bread",
            ),
        ),
        migrations.AlterField(
            model_name="breaddelivery",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.AlterField(
            model_name="breaddelivery",
            name="slot_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="breaddelivery",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wirgarten.subscription"
            ),
        ),
    ]
