# Generated by Django 6.0.1 on 2026-02-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0007_alter_breaddelivery_bread_and_more"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breaddelivery",
            options={"ordering": ["year", "delivery_week", "slot_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="breaddelivery",
            unique_together={("subscription", "year", "delivery_week", "slot_number")},
        ),
    ]
