# Generated by Django 6.0.1 on 2026-02-22 21:51

import django.core.validators
import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0008_alter_breaddelivery_options_and_more"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreadCapacityPickupLocation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Year for which this capacity applies"
                    ),
                ),
                (
                    "delivery_week",
                    models.PositiveIntegerField(
                        help_text="Delivery week number (1-53)"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of breads of this label that can be delivered to this pickup location on this delivery day",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_entries",
                        to="bakery.bread",
                    ),
                ),
                (
                    "pickup_location_day",
                    models.ForeignKey(
                        help_text="The pickup location and day this capacity applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bread_capacities",
                        to="wirgarten.pickuplocationopeningtime",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("pickup_location_day", "year", "delivery_week", "bread")
                },
            },
        ),
        migrations.DeleteModel(
            name="BreadCapacityPickupStation",
        ),
    ]
