# Generated by Django 6.0.1 on 2026-02-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0009_breadcapacitypickuplocation_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breaddelivery",
            unique_together=set(),
        ),
    ]
