# Generated by Django 6.0.1 on 2026-02-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0010_alter_breaddelivery_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bread",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="bread",
            name="updated_at",
        ),
    ]
