# Generated by Django 6.0.1 on 2026-02-26 23:00

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0011_remove_bread_created_at_remove_bread_updated_at"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaddelivery",
            name="pickup_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.CreateModel(
            name="PreferredBread",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("delivery_week", models.PositiveIntegerField()),
                (
                    "breads",
                    models.ManyToManyField(
                        related_name="preferred_by_members", to="bakery.bread"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_breads",
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
