# Generated by Django 6.0.1 on 2026-02-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0012_alter_breaddelivery_pickup_location_preferredbread"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bakeryconfiguration",
            old_name="pickup_stations_can_be_chosen_per_share_not_just_per_member",
            new_name="pickup_locations_can_be_chosen_per_share_not_just_per_member",
        ),
    ]
