# Generated by Django 6.0.1 on 2026-02-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bakery",
            "0013_rename_pickup_stations_can_be_chosen_per_share_not_just_per_member_bakeryconfiguration_pickup_locati",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="BakeryConfiguration",
        ),
    ]
