# Generated by Django 6.0.1 on 2026-02-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0014_delete_bakeryconfiguration"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AddField(
            model_name="breadcapacitypickuplocation",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The pickup location this capacity applies to (redundant but useful for queries)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bread_capacities",
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
