# Generated by Django 6.0.1 on 2026-02-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0015_breadcapacitypickuplocation_pickup_location"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breadcapacitypickuplocation",
            unique_together={("pickup_location", "year", "delivery_week", "bread")},
        ),
        migrations.RemoveField(
            model_name="breadcapacitypickuplocation",
            name="pickup_location_day",
        ),
    ]
