# Generated by Django 6.0.1 on 2026-02-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0016_alter_breadcapacitypickuplocation_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferredbread",
            name="delivery_week",
        ),
        migrations.RemoveField(
            model_name="preferredbread",
            name="year",
        ),
    ]
