# Generated by Django 6.0.1 on 2026-02-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0017_remove_preferredbread_delivery_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bread",
            name="one_batch_can_be_baked_in_more_than_one_stove",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bread",
            name="pieces_per_stove_layer",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of possible pieces per stove layer (e.g., [10, 11, 12] or [22, 24])",
                null=True,
            ),
        ),
    ]
