# Generated by Django 6.0.1 on 2026-02-27 22:28

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0018_bread_one_batch_can_be_baked_in_more_than_one_stove_and_more"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AddField(
            model_name="bread",
            name="max_pieces",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of pieces that should be baked for this bread on a baking day (e.g., to limit the amount of bread that can be ordered for this bread)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bread",
            name="min_pieces",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum number of pieces that should be baked for this bread on a baking day (e.g., to ensure that there are enough pieces for walk-in customers)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bread",
            name="min_remaining_pieces",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum amount of breads that should remain available for this bread on a baking day (e.g., for walk-in customers)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BreadsPerPickupLocationPerWeek",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("delivery_week", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "bread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_location_counts",
                        to="bakery.bread",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bread_counts",
                        to="wirgarten.pickuplocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
