# Generated by Django 6.0.1 on 2026-02-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0019_bread_max_pieces_bread_min_pieces_and_more"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaddelivery",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
