# Generated by Django 6.0.1 on 2026-02-28 18:09

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0020_alter_breaddelivery_pickup_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoveSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("delivery_week", models.PositiveIntegerField()),
                ("delivery_day", models.PositiveIntegerField()),
                ("session_number", models.PositiveIntegerField()),
                ("layer_number", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "bread",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stove_sessions",
                        to="bakery.bread",
                    ),
                ),
            ],
            options={
                "ordering": ["session_number", "layer_number"],
                "unique_together": {
                    (
                        "year",
                        "delivery_week",
                        "delivery_day",
                        "session_number",
                        "layer_number",
                    )
                },
            },
        ),
    ]
