# Generated by Django 6.0.1 on 2026-03-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0022_maxnumberbreadsperdeliverday_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaxNumberBreadsPerDeliverDay",
        ),
    ]
