# Generated by Django 6.0.1 on 2026-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0023_delete_maxnumberbreadsperdeliverday"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="availablebreadsfordeliveryday",
            index=models.Index(
                fields=["year", "delivery_week", "delivery_day"],
                name="bakery_avai_year_31666b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breadcapacitypickuplocation",
            index=models.Index(
                fields=["pickup_location", "year", "delivery_week"],
                name="bakery_brea_pickup__cac3ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breaddelivery",
            index=models.Index(
                fields=["year", "delivery_week"], name="bakery_brea_year_74dd52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breaddelivery",
            index=models.Index(
                fields=["subscription", "year", "delivery_week"],
                name="bakery_brea_subscri_4bf9b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breaddelivery",
            index=models.Index(
                fields=["pickup_location", "year", "delivery_week"],
                name="bakery_brea_pickup__b57bb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breaddelivery",
            index=models.Index(
                fields=["year", "delivery_week", "bread"],
                name="bakery_brea_year_348b02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breadspecificsperdeliveryday",
            index=models.Index(
                fields=["year", "delivery_week", "delivery_day"],
                name="bakery_brea_year_d31e0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breadsperpickuplocationperweek",
            index=models.Index(
                fields=["pickup_location", "year", "delivery_week"],
                name="bakery_brea_pickup__ba208a_idx",
            ),
        ),
    ]
