# Generated by Django 6.0.1 on 2026-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bakery",
            "0024_availablebreadsfordeliveryday_bakery_avai_year_31666b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaddelivery",
            name="slot_number",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
