# Generated by Django 6.0.1 on 2026-03-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0026_breaddelivery_joker_taken_alter_breaddelivery_bread_and_more"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breadspecificsperdeliveryday",
            unique_together={("year", "delivery_week", "delivery_day", "bread")},
        ),
        migrations.AlterUniqueTogether(
            name="breadsperpickuplocationperweek",
            unique_together={("pickup_location", "year", "delivery_week", "bread")},
        ),
        migrations.AlterUniqueTogether(
            name="preferencesatisfactionlogging",
            unique_together={
                ("year", "delivery_week", "delivery_day", "pickup_location")
            },
        ),
    ]
