# Generated by Django 6.0.1 on 2026-04-17 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0027_alter_breadspecificsperdeliveryday_unique_together_and_more"),
        ("wirgarten", "0099_member_pseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bread",
            name="weight",
            field=models.FloatField(
                help_text="Weight in grams",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="breadcapacitypickuplocation",
            name="capacity",
            field=models.PositiveIntegerField(
                help_text="Maximum number of breads of this type that can be delivered to this pickup location on this delivery day",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="breadcapacitypickuplocation",
            name="pickup_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bread_capacities",
                to="wirgarten.pickuplocation",
            ),
        ),
        migrations.AlterField(
            model_name="breadcontent",
            name="amount",
            field=models.FloatField(
                help_text="Amount in grams or percentage",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.DeleteModel(
            name="PreferredLabel",
        ),
    ]
