# Generated by Django 6.0.1 on 2026-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0028_alter_bread_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bread",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
