# Generated by Django 6.0.1 on 2026-09-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0029_alter_bread_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaddelivery",
            name="bread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bakery.bread",
            ),
        ),
    ]
