# Generated by Django 6.0.1 on 2026-09-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0030_alter_breaddelivery_bread"),
        ("wirgarten", "0100_producttype_is_bread"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="breaddelivery",
            unique_together={("subscription", "year", "delivery_week", "slot_number")},
        ),
    ]
