# Generated by Django 6.0.1 on 2026-09-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0031_alter_breaddelivery_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="breaddelivery",
            name="bakery_brea_pickup__b57bb1_idx",
        ),
        migrations.RemoveField(
            model_name="breaddelivery",
            name="joker_taken",
        ),
        migrations.RemoveField(
            model_name="breaddelivery",
            name="pickup_location",
        ),
    ]
