# Generated by Django 6.0.1 on 2026-09-03 15:40

import django.db.models.deletion
import functools
import tapir.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0032_remove_breaddelivery_bakery_brea_pickup__b57bb1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stovesession",
            name="delivery_day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BreadsToBakePerWeek",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(tapir.core.models.generate_id),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("delivery_week", models.PositiveIntegerField()),
                ("delivery_day", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Total pieces to bake"),
                ),
                (
                    "remaining",
                    models.PositiveIntegerField(
                        default=0, help_text="Pieces beyond what the deliveries need"
                    ),
                ),
                (
                    "bread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantities_to_bake",
                        to="bakery.bread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["year", "delivery_week", "delivery_day"],
                        name="bakery_brea_year_f9af7b_idx",
                    )
                ],
                "unique_together": {("year", "delivery_week", "delivery_day", "bread")},
            },
        ),
    ]
