# Generated by Django 6.0.1 on 2026-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0033_alter_stovesession_delivery_day_breadstobakeperweek"),
        ("wirgarten", "0100_producttype_is_bread"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="availablebreadsfordeliveryday",
            name="bakery_avai_year_31666b_idx",
        ),
        migrations.RemoveIndex(
            model_name="breadcapacitypickuplocation",
            name="bakery_brea_pickup__cac3ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="breaddelivery",
            name="bakery_brea_year_74dd52_idx",
        ),
        migrations.RemoveIndex(
            model_name="breaddelivery",
            name="bakery_brea_subscri_4bf9b8_idx",
        ),
        migrations.AlterField(
            model_name="breaddelivery",
            name="slot_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="breadcapacitypickuplocation",
            index=models.Index(
                fields=["year", "delivery_week"], name="bakery_brea_year_630151_idx"
            ),
        ),
    ]
