# Generated by Django 6.0.1 on 2026-09-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bakery",
            "0034_remove_availablebreadsfordeliveryday_bakery_avai_year_31666b_idx_and_more",
        ),
        ("wirgarten", "0100_producttype_is_bread"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="breadsperpickuplocationperweek",
            name="bakery_brea_pickup__ba208a_idx",
        ),
        migrations.AddIndex(
            model_name="breadsperpickuplocationperweek",
            index=models.Index(
                fields=["year", "delivery_week"], name="bakery_brea_year_60db13_idx"
            ),
        ),
    ]
