# Generated by Django 5.2 on 2025-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_merge_20221026_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapirparameter",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
