# Generated by Django 5.2 on 2025-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0005_tapirparameter_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapirparameter",
            name="debug",
            field=models.BooleanField(default=False),
        ),
    ]
