# Generated by Django 5.2.1 on 2025-11-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0006_tapirparameter_debug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapirparameter",
            name="required",
            field=models.BooleanField(default=True),
        ),
    ]
