# Generated by Django 5.2 on 2025-04-08 09:46

from django.db import migrations, connection


def delete_field(apps, schema):
    # The old production instances (LNP, GKH, MM, ... from the tapir2.0 branch)
    # all have a column called "required" on the table the for TapirParameter model
    # I can't find a trace of that field anywhere in the git history.
    # Since that column can't be null, it causes error when trying to create parameters without that field
    # The new instances (demo2, huw, euo... from the biotop-dev branch) don't have that field.
    # So we must use custom SQL to remove it if it exists.

    with connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE configuration_tapirparameter DROP COLUMN IF EXISTS required;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0006_tapirparameter_debug"),
    ]

    operations = [
        migrations.RunPython(delete_field),
    ]
