/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";

export interface ConfigMemberNumberPreviewRetrieveRequest {
  length?: number;
  prefix?: string;
}

/**
 *
 */
export class ConfigApi extends runtime.BaseAPI {
  /**
   */
  async configMemberNumberPreviewRetrieveRaw(
    requestParameters: ConfigMemberNumberPreviewRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: Array<string> }>> {
    const queryParameters: any = {};

    if (requestParameters["length"] != null) {
      queryParameters["length"] = requestParameters["length"];
    }

    if (requestParameters["prefix"] != null) {
      queryParameters["prefix"] = requestParameters["prefix"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/config/member-number-preview`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async configMemberNumberPreviewRetrieve(
    requestParameters: ConfigMemberNumberPreviewRetrieveRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: Array<string> }> {
    const response = await this.configMemberNumberPreviewRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
