/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { MinimumNumberOfSharesResponse } from "../models/index";
import { MinimumNumberOfSharesResponseFromJSON } from "../models/index";

export interface CoopApiMinimumNumberOfSharesRetrieveRequest {
  productIds?: Array<string>;
  quantities?: Array<number>;
}

/**
 *
 */
export class CoopApi extends runtime.BaseAPI {
  /**
   */
  async coopApiMinimumNumberOfSharesRetrieveRaw(
    requestParameters: CoopApiMinimumNumberOfSharesRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MinimumNumberOfSharesResponse>> {
    const queryParameters: any = {};

    if (requestParameters["productIds"] != null) {
      queryParameters["product_ids"] = requestParameters["productIds"];
    }

    if (requestParameters["quantities"] != null) {
      queryParameters["quantities"] = requestParameters["quantities"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/coop/api/minimum_number_of_shares`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MinimumNumberOfSharesResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async coopApiMinimumNumberOfSharesRetrieve(
    requestParameters: CoopApiMinimumNumberOfSharesRetrieveRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MinimumNumberOfSharesResponse> {
    const response = await this.coopApiMinimumNumberOfSharesRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
