/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Joker,
} from '../models/index';
import {
    JokerFromJSON,
    JokerToJSON,
} from '../models/index';

export interface JokersApiMemberJokersListRequest {
    memberId?: string;
}

/**
 * 
 */
export class JokersApi extends runtime.BaseAPI {

    /**
     */
    async jokersApiMemberJokersListRaw(requestParameters: JokersApiMemberJokersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Joker>>> {
        const queryParameters: any = {};

        if (requestParameters['memberId'] != null) {
            queryParameters['member_id'] = requestParameters['memberId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/jokers/api/member_jokers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JokerFromJSON));
    }

    /**
     */
    async jokersApiMemberJokersList(requestParameters: JokersApiMemberJokersListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Joker>> {
        const response = await this.jokersApiMemberJokersListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
