/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ExtendedPayment } from "../models/index";
import { ExtendedPaymentFromJSON } from "../models/index";

export interface PaymentsApiMemberFuturePaymentsListRequest {
  memberId?: string;
}

/**
 *
 */
export class PaymentsApi extends runtime.BaseAPI {
  /**
   */
  async paymentsApiMemberFuturePaymentsListRaw(
    requestParameters: PaymentsApiMemberFuturePaymentsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ExtendedPayment>>> {
    const queryParameters: any = {};

    if (requestParameters["memberId"] != null) {
      queryParameters["member_id"] = requestParameters["memberId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/payments/api/member_future_payments`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ExtendedPaymentFromJSON),
    );
  }

  /**
   */
  async paymentsApiMemberFuturePaymentsList(
    requestParameters: PaymentsApiMemberFuturePaymentsListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ExtendedPayment>> {
    const response = await this.paymentsApiMemberFuturePaymentsListRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
