/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  BestellWizardCapacityCheckResponse,
  CancelSubscriptionsRequestRequest,
  CancelSubscriptionsViewResponse,
  CancellationData,
  ConfirmSubscriptionChangesRequestRequest,
  ConvertWeekToDateForSubscriptionChangesResponse,
  ExtendedProduct,
  MemberDataToConfirm,
  MemberProfileCapacityCheckRequestRequest,
  MemberSubscriptionData,
  OrderConfirmationResponse,
  PatchedExtendedProductRequest,
  Product,
  PublicProductType,
  Subscription,
  SubscriptionDateChangeRequestRequest,
  UpdateSubscriptionsRequestRequest,
} from "../models/index";
import {
  BestellWizardCapacityCheckResponseFromJSON,
  CancelSubscriptionsRequestRequestToJSON,
  CancelSubscriptionsViewResponseFromJSON,
  CancellationDataFromJSON,
  ConfirmSubscriptionChangesRequestRequestToJSON,
  ConvertWeekToDateForSubscriptionChangesResponseFromJSON,
  ExtendedProductFromJSON,
  MemberDataToConfirmFromJSON,
  MemberProfileCapacityCheckRequestRequestToJSON,
  MemberSubscriptionDataFromJSON,
  OrderConfirmationResponseFromJSON,
  PatchedExtendedProductRequestToJSON,
  ProductFromJSON,
  PublicProductTypeFromJSON,
  SubscriptionDateChangeRequestRequestToJSON,
  SubscriptionFromJSON,
  UpdateSubscriptionsRequestRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface SubscriptionsApiConfirmSubscriptionChangesCreateRequest {
  confirmSubscriptionChangesRequestRequest: ConfirmSubscriptionChangesRequestRequest;
}

export interface SubscriptionsApiConvertWeeksToDateForSubscriptionChangeRetrieveRequest {
  endWeek?: number;
  startWeek?: number;
  subscriptionId?: string;
}

export interface SubscriptionsApiDatesChangeCreateRequest {
  subscriptionDateChangeRequestRequest: SubscriptionDateChangeRequestRequest;
}

export interface SubscriptionsApiExtendedProductPartialUpdateRequest {
  patchedExtendedProductRequest?: PatchedExtendedProductRequest;
}

export interface SubscriptionsApiExtendedProductRetrieveRequest {
  productId?: string;
}

export interface SubscriptionsApiMemberProfileCapacityCheckCreateRequest {
  memberProfileCapacityCheckRequestRequest: MemberProfileCapacityCheckRequestRequest;
}

export interface SubscriptionsApiMemberSubscriptionDataRetrieveRequest {
  memberId?: string;
}

export interface SubscriptionsApiRevokeChangesCreateRequest {
  coopSharePurchaseIds: Array<string>;
  putOnWaitingList: boolean;
  subscriptionCreationIds: Array<string>;
}

export interface SubscriptionsApiUpdateSubscriptionCreateRequest {
  updateSubscriptionsRequestRequest: UpdateSubscriptionsRequestRequest;
}

export interface SubscriptionsCancelSubscriptionsCreateRequest {
  cancelSubscriptionsRequestRequest: CancelSubscriptionsRequestRequest;
}

export interface SubscriptionsCancellationDataRetrieveRequest {
  memberId?: string;
}

export interface SubscriptionsProductsRetrieveRequest {
  id: string;
}

export interface SubscriptionsPublicProductTypesRetrieveRequest {
  id: string;
}

export interface SubscriptionsSubscriptionsRetrieveRequest {
  id: string;
}

/**
 *
 */
export class SubscriptionsApi extends runtime.BaseAPI {
  /**
   */
  async subscriptionsApiConfirmSubscriptionChangesCreateRaw(
    requestParameters: SubscriptionsApiConfirmSubscriptionChangesCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["confirmSubscriptionChangesRequestRequest"] == null) {
      throw new runtime.RequiredError(
        "confirmSubscriptionChangesRequestRequest",
        'Required parameter "confirmSubscriptionChangesRequestRequest" was null or undefined when calling subscriptionsApiConfirmSubscriptionChangesCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/confirm_subscription_changes`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ConfirmSubscriptionChangesRequestRequestToJSON(
          requestParameters["confirmSubscriptionChangesRequestRequest"],
        ),
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async subscriptionsApiConfirmSubscriptionChangesCreate(
    requestParameters: SubscriptionsApiConfirmSubscriptionChangesCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<string> {
    const response =
      await this.subscriptionsApiConfirmSubscriptionChangesCreateRaw(
        requestParameters,
        initOverrides,
      );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiConvertWeeksToDateForSubscriptionChangeRetrieveRaw(
    requestParameters: SubscriptionsApiConvertWeeksToDateForSubscriptionChangeRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<
    runtime.ApiResponse<ConvertWeekToDateForSubscriptionChangesResponse>
  > {
    const queryParameters: any = {};

    if (requestParameters["endWeek"] != null) {
      queryParameters["end_week"] = requestParameters["endWeek"];
    }

    if (requestParameters["startWeek"] != null) {
      queryParameters["start_week"] = requestParameters["startWeek"];
    }

    if (requestParameters["subscriptionId"] != null) {
      queryParameters["subscription_id"] = requestParameters["subscriptionId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api(/convert_weeks_to_date_for_subscription_change`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ConvertWeekToDateForSubscriptionChangesResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsApiConvertWeeksToDateForSubscriptionChangeRetrieve(
    requestParameters: SubscriptionsApiConvertWeeksToDateForSubscriptionChangeRetrieveRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ConvertWeekToDateForSubscriptionChangesResponse> {
    const response =
      await this.subscriptionsApiConvertWeeksToDateForSubscriptionChangeRetrieveRaw(
        requestParameters,
        initOverrides,
      );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiDatesChangeCreateRaw(
    requestParameters: SubscriptionsApiDatesChangeCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OrderConfirmationResponse>> {
    if (requestParameters["subscriptionDateChangeRequestRequest"] == null) {
      throw new runtime.RequiredError(
        "subscriptionDateChangeRequestRequest",
        'Required parameter "subscriptionDateChangeRequestRequest" was null or undefined when calling subscriptionsApiDatesChangeCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/dates_change`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: SubscriptionDateChangeRequestRequestToJSON(
          requestParameters["subscriptionDateChangeRequestRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OrderConfirmationResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsApiDatesChangeCreate(
    requestParameters: SubscriptionsApiDatesChangeCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OrderConfirmationResponse> {
    const response = await this.subscriptionsApiDatesChangeCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiExtendedProductPartialUpdateRaw(
    requestParameters: SubscriptionsApiExtendedProductPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/extended_product`,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: PatchedExtendedProductRequestToJSON(
          requestParameters["patchedExtendedProductRequest"],
        ),
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async subscriptionsApiExtendedProductPartialUpdate(
    requestParameters: SubscriptionsApiExtendedProductPartialUpdateRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<string> {
    const response = await this.subscriptionsApiExtendedProductPartialUpdateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiExtendedProductRetrieveRaw(
    requestParameters: SubscriptionsApiExtendedProductRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ExtendedProduct>> {
    const queryParameters: any = {};

    if (requestParameters["productId"] != null) {
      queryParameters["product_id"] = requestParameters["productId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/extended_product`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ExtendedProductFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsApiExtendedProductRetrieve(
    requestParameters: SubscriptionsApiExtendedProductRetrieveRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ExtendedProduct> {
    const response = await this.subscriptionsApiExtendedProductRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiMemberDataToConfirmListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<MemberDataToConfirm>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/member_data_to_confirm`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MemberDataToConfirmFromJSON),
    );
  }

  /**
   */
  async subscriptionsApiMemberDataToConfirmList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<MemberDataToConfirm>> {
    const response =
      await this.subscriptionsApiMemberDataToConfirmListRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async subscriptionsApiMemberProfileCapacityCheckCreateRaw(
    requestParameters: SubscriptionsApiMemberProfileCapacityCheckCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BestellWizardCapacityCheckResponse>> {
    if (requestParameters["memberProfileCapacityCheckRequestRequest"] == null) {
      throw new runtime.RequiredError(
        "memberProfileCapacityCheckRequestRequest",
        'Required parameter "memberProfileCapacityCheckRequestRequest" was null or undefined when calling subscriptionsApiMemberProfileCapacityCheckCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/member_profile_capacity_check`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: MemberProfileCapacityCheckRequestRequestToJSON(
          requestParameters["memberProfileCapacityCheckRequestRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BestellWizardCapacityCheckResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsApiMemberProfileCapacityCheckCreate(
    requestParameters: SubscriptionsApiMemberProfileCapacityCheckCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BestellWizardCapacityCheckResponse> {
    const response =
      await this.subscriptionsApiMemberProfileCapacityCheckCreateRaw(
        requestParameters,
        initOverrides,
      );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiMemberSubscriptionDataRetrieveRaw(
    requestParameters: SubscriptionsApiMemberSubscriptionDataRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MemberSubscriptionData>> {
    const queryParameters: any = {};

    if (requestParameters["memberId"] != null) {
      queryParameters["member_id"] = requestParameters["memberId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/member_subscription_data`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MemberSubscriptionDataFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsApiMemberSubscriptionDataRetrieve(
    requestParameters: SubscriptionsApiMemberSubscriptionDataRetrieveRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MemberSubscriptionData> {
    const response =
      await this.subscriptionsApiMemberSubscriptionDataRetrieveRaw(
        requestParameters,
        initOverrides,
      );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiRevokeChangesCreateRaw(
    requestParameters: SubscriptionsApiRevokeChangesCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["coopSharePurchaseIds"] == null) {
      throw new runtime.RequiredError(
        "coopSharePurchaseIds",
        'Required parameter "coopSharePurchaseIds" was null or undefined when calling subscriptionsApiRevokeChangesCreate().',
      );
    }

    if (requestParameters["putOnWaitingList"] == null) {
      throw new runtime.RequiredError(
        "putOnWaitingList",
        'Required parameter "putOnWaitingList" was null or undefined when calling subscriptionsApiRevokeChangesCreate().',
      );
    }

    if (requestParameters["subscriptionCreationIds"] == null) {
      throw new runtime.RequiredError(
        "subscriptionCreationIds",
        'Required parameter "subscriptionCreationIds" was null or undefined when calling subscriptionsApiRevokeChangesCreate().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["coopSharePurchaseIds"] != null) {
      queryParameters["coop_share_purchase_ids"] =
        requestParameters["coopSharePurchaseIds"];
    }

    if (requestParameters["putOnWaitingList"] != null) {
      queryParameters["put_on_waiting_list"] =
        requestParameters["putOnWaitingList"];
    }

    if (requestParameters["subscriptionCreationIds"] != null) {
      queryParameters["subscription_creation_ids"] =
        requestParameters["subscriptionCreationIds"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/revoke_changes`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async subscriptionsApiRevokeChangesCreate(
    requestParameters: SubscriptionsApiRevokeChangesCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<string> {
    const response = await this.subscriptionsApiRevokeChangesCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsApiUpdateSubscriptionCreateRaw(
    requestParameters: SubscriptionsApiUpdateSubscriptionCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OrderConfirmationResponse>> {
    if (requestParameters["updateSubscriptionsRequestRequest"] == null) {
      throw new runtime.RequiredError(
        "updateSubscriptionsRequestRequest",
        'Required parameter "updateSubscriptionsRequestRequest" was null or undefined when calling subscriptionsApiUpdateSubscriptionCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/api/update_subscription`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateSubscriptionsRequestRequestToJSON(
          requestParameters["updateSubscriptionsRequestRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OrderConfirmationResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsApiUpdateSubscriptionCreate(
    requestParameters: SubscriptionsApiUpdateSubscriptionCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OrderConfirmationResponse> {
    const response = await this.subscriptionsApiUpdateSubscriptionCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsCancelSubscriptionsCreateRaw(
    requestParameters: SubscriptionsCancelSubscriptionsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CancelSubscriptionsViewResponse>> {
    if (requestParameters["cancelSubscriptionsRequestRequest"] == null) {
      throw new runtime.RequiredError(
        "cancelSubscriptionsRequestRequest",
        'Required parameter "cancelSubscriptionsRequestRequest" was null or undefined when calling subscriptionsCancelSubscriptionsCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/cancel_subscriptions`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CancelSubscriptionsRequestRequestToJSON(
          requestParameters["cancelSubscriptionsRequestRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CancelSubscriptionsViewResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsCancelSubscriptionsCreate(
    requestParameters: SubscriptionsCancelSubscriptionsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CancelSubscriptionsViewResponse> {
    const response = await this.subscriptionsCancelSubscriptionsCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsCancellationDataRetrieveRaw(
    requestParameters: SubscriptionsCancellationDataRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CancellationData>> {
    const queryParameters: any = {};

    if (requestParameters["memberId"] != null) {
      queryParameters["member_id"] = requestParameters["memberId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/cancellation_data`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CancellationDataFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsCancellationDataRetrieve(
    requestParameters: SubscriptionsCancellationDataRetrieveRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CancellationData> {
    const response = await this.subscriptionsCancellationDataRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsProductsListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Product>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/products/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ProductFromJSON),
    );
  }

  /**
   */
  async subscriptionsProductsList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Product>> {
    const response = await this.subscriptionsProductsListRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async subscriptionsProductsRetrieveRaw(
    requestParameters: SubscriptionsProductsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Product>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling subscriptionsProductsRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/products/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProductFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsProductsRetrieve(
    requestParameters: SubscriptionsProductsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Product> {
    const response = await this.subscriptionsProductsRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsPublicProductTypesListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PublicProductType>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/public_product_types/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PublicProductTypeFromJSON),
    );
  }

  /**
   */
  async subscriptionsPublicProductTypesList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PublicProductType>> {
    const response =
      await this.subscriptionsPublicProductTypesListRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async subscriptionsPublicProductTypesRetrieveRaw(
    requestParameters: SubscriptionsPublicProductTypesRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PublicProductType>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling subscriptionsPublicProductTypesRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/public_product_types/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PublicProductTypeFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsPublicProductTypesRetrieve(
    requestParameters: SubscriptionsPublicProductTypesRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PublicProductType> {
    const response = await this.subscriptionsPublicProductTypesRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async subscriptionsSubscriptionsListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Subscription>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/subscriptions/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SubscriptionFromJSON),
    );
  }

  /**
   */
  async subscriptionsSubscriptionsList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Subscription>> {
    const response =
      await this.subscriptionsSubscriptionsListRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async subscriptionsSubscriptionsRetrieveRaw(
    requestParameters: SubscriptionsSubscriptionsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Subscription>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling subscriptionsSubscriptionsRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        await this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    const response = await this.request(
      {
        path: `/subscriptions/subscriptions/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SubscriptionFromJSON(jsonValue),
    );
  }

  /**
   */
  async subscriptionsSubscriptionsRetrieve(
    requestParameters: SubscriptionsSubscriptionsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Subscription> {
    const response = await this.subscriptionsSubscriptionsRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
