# Generated by Django 3.2.25 on 2025-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CsvExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_id", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField()),
                ("separator", models.CharField(max_length=1)),
                ("file_name", models.CharField(max_length=512)),
            ],
        ),
    ]
