# Generated by Django 3.2.25 on 2025-03-10 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_exports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvexport",
            name="columns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="csvexport",
            name="email_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=list, size=None
            ),
        ),
    ]
