# Generated by Django 3.2.25 on 2025-03-11 13:51

import functools

from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_exports", "0004_auto_20250311_1237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvexport",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
