# Generated by Django 3.2.25 on 2025-03-11 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_exports", "0005_alter_csvexport_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvexport",
            name="automated_export_cycle",
            field=models.CharField(
                choices=[
                    ("yearly", "Jährlich"),
                    ("monthly", "Monatlich"),
                    ("weekly", "Wöchentlich"),
                    ("daily", "Täglich"),
                    ("never", "Nie"),
                ],
                default="never",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvexport",
            name="automated_export_day",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csvexport",
            name="automated_export_hour",
            field=models.TimeField(default=datetime.time(12, 30)),
            preserve_default=False,
        ),
    ]
