# Generated by Django 3.2.25 on 2025-03-11 15:49

import functools

import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("wirgarten", "0044_alter_productcapacity_capacity"),
        ("generic_exports", "0006_auto_20250311_1532"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomatedExportResult",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "export_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generic_exports.csvexport",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.exportedfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
