# Generated by Django 3.2.25 on 2025-03-12 12:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_exports", "0007_automatedexportresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvexport",
            name="custom_column_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
