# Generated by Django 5.2 on 2025-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_exports", "0010_alter_csvexport_column_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvexport",
            name="locale",
            field=models.CharField(
                choices=[
                    ("de_DE.utf-8", "Deutsch (DE)"),
                    ("en_US.utf-8", "English (US)"),
                ],
                default="de_DE.utf-8",
                max_length=512,
            ),
        ),
    ]
