# Generated by Django 6.0.5 on 2026-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_exports", "0012_automatedcsvexportresult_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfexport",
            name="renderer",
            field=models.IntegerField(
                choices=[(1, "Weasyprint"), (2, "Typst")], default=1
            ),
        ),
    ]
