# Generated by Django 5.2.1 on 2025-07-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wirgarten", "0075_coopsharetransaction_auto_confirmed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberPaymentRhythm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rhythm",
                    models.CharField(
                        choices=[
                            ("monthly", "Monatlich"),
                            ("quarterly", "Vierteljährlich"),
                            ("semiannually", "Halbjährlich"),
                            ("yearly", "Jährlich"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
            ],
        ),
    ]
