# Generated by Django 5.2.1 on 2025-08-15 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberpaymentrhythm",
            name="valid_from",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
