# Generated by Django 5.2.1 on 2025-09-01 16:23

import functools

from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_memberpaymentrhythm_valid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberpaymentrhythm",
            name="id",
            field=models.CharField(
                default=functools.partial(tapir.core.models.generate_id, *(), **{}),
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
