# Generated by Django 5.2.1 on 2025-09-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("payments", "0003_alter_memberpaymentrhythm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberPaymentRhythmChangeLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                ("old_rhythm", models.CharField()),
                ("new_rhythm", models.CharField()),
                ("valid_from", models.DateField()),
            ],
            bases=("log.logentry",),
        ),
    ]
