# Generated by Django 5.2.1 on 2025-10-10 11:49

import functools

import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_memberpaymentrhythmchangelogentry"),
        ("wirgarten", "0081_auto_20250815_1118"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCredit",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purpose", models.CharField(max_length=1024)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
