# Generated by Django 5.2.1 on 2025-10-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("payments", "0005_membercredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercredit",
            name="comment",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MemberCreditCreatedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                (
                    "member_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.membercredit",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
    ]
