# Generated by Django 5.2.1 on 2025-10-10 12:54

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_membercredit_comment_membercreditcreatedlogentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membercreditcreatedlogentry",
            name="member_credit",
        ),
        migrations.AddField(
            model_name="membercreditcreatedlogentry",
            name="values",
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
    ]
