# Generated by Django 6.0.1 on 2026-03-09 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_remove_membercreditcreatedlogentry_member_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercredit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="memberpaymentrhythm",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberpaymentrhythm",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
