# Generated by Django 6.0.4 on 2026-04-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_membercredit_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercredit",
            name="accounted_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="MemberCreditAccountedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                (
                    "member_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.membercredit",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
    ]
