# Generated by Django 6.0.5 on 2026-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_membercredit_accounted_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercredit",
            name="source",
            field=models.CharField(default="unkown (pre-migration)", max_length=1024),
            preserve_default=False,
        ),
    ]
