# Generated by Django 6.0.5 on 2026-07-22 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_membercredit_source"),
        ("wirgarten", "0125_payment_pickup_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercredit",
            name="pickup_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
