# Generated by Django 6.0.7 on 2026-08-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deliveries",
            "0009_rename_customcycledeliveryweeks_customcyclescheduleddeliveryweek",
        ),
        ("payments", "0011_membercredit_pickup_location"),
        ("wirgarten", "0129_product_hidden_in_bestell_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercredit",
            name="joker",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="deliveries.joker",
            ),
        ),
        migrations.AlterField(
            model_name="membercredit",
            name="pickup_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wirgarten.pickuplocation",
            ),
        ),
    ]
