# Generated by Django 3.2.17 on 2023-02-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import tapir.accounts.models
import tapir.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_email",
                    models.CharField(max_length=150, verbose_name="New Email"),
                ),
                (
                    "secret",
                    models.CharField(
                        default=functools.partial(
                            tapir.accounts.models.generate_random_secret, *(), **{}
                        ),
                        max_length=36,
                        verbose_name="Secret",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
