# Generated by Django 5.2.1 on 2025-12-04 14:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20230329_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapiruser",
            name="form_of_address",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Liebe/Lieber"
            ),
        ),
        migrations.AddField(
            model_name="tapiruser",
            name="phone_number_landline",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone number (landline)",
            ),
        ),
    ]
