# Generated by Django 6.0.1 on 2026-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_tapiruser_form_of_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailchangerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
