# Generated by Django 5.2.1 on 2025-12-09 17:32

import functools

import django.db.models.deletion
from django.db import migrations, models

import tapir.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wirgarten", "0086_remove_subscription_solidarity_price_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolidarityContribution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            tapir.core.models.generate_id, *(), **{}
                        ),
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wirgarten.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
