# Generated by Django 5.2.1 on 2025-12-12 09:36
from decimal import Decimal

from django.db import migrations

from tapir.utils.services.tapir_cache import TapirCache


def migrate_solidarity_from_subscriptions_to_dedicated_model(apps, schema):
    Subscription = apps.get_model("wirgarten", "Subscription")
    SolidarityContribution = apps.get_model(
        "solidarity_contribution", "SolidarityContribution"
    )
    cache = {}

    subscriptions = list(
        Subscription.objects.filter(solidarity_price_absolute__isnull=False)
    )
    contributions_by_member_id_and_growing_period = {}

    for subscription in subscriptions:
        if (
            subscription.member_id
            not in contributions_by_member_id_and_growing_period.keys()
        ):
            contributions_by_member_id_and_growing_period[subscription.member_id] = {}

        contributions_by_growing_period = contributions_by_member_id_and_growing_period[
            subscription.member_id
        ]
        growing_period = TapirCache.get_growing_period_at_date(
            reference_date=subscription.start_date, cache=cache
        )
        if growing_period not in contributions_by_growing_period.keys():
            contributions_by_growing_period[growing_period] = SolidarityContribution(
                member_id=subscription.member_id,
                amount=Decimal(0),
                start_date=subscription.start_date,
                end_date=subscription.end_date,
            )

        contribution = contributions_by_growing_period[growing_period]
        contribution.amount += subscription.solidarity_price_absolute

        subscription.solidarity_price_absolute = Decimal(0)

    Subscription.objects.bulk_update(subscriptions, ["solidarity_price_absolute"])

    all_contributions = []
    for (
        contributions_by_growing_period
    ) in contributions_by_member_id_and_growing_period.values():
        all_contributions.extend(contributions_by_growing_period.values())
    SolidarityContribution.objects.bulk_create(all_contributions)


class Migration(migrations.Migration):

    dependencies = [
        ("solidarity_contribution", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_solidarity_from_subscriptions_to_dedicated_model),
    ]
