# Generated by Django 5.2.1 on 2025-12-12 09:36
import datetime
from decimal import Decimal
from typing import Callable

from django.db import migrations


def get_from_cache_or_compute[T](
    cache: dict | None, key, compute_function: Callable[[], T]
) -> T:
    if cache is None:
        return compute_function()
    return dict_get_or_set(cache, key, compute_function)


def dict_get_or_set(dictionary: dict, key, call_if_not_set: Callable):
    if key not in dictionary:
        dictionary[key] = call_if_not_set()
    return dictionary[key]


def get_all_growing_periods_ascending(cache: dict, apps):
    GrowingPeriod = apps.get_model("wirgarten", "GrowingPeriod")
    return get_from_cache_or_compute(
        cache,
        "all_growing_periods",
        lambda: list(GrowingPeriod.objects.order_by("start_date")),
    )


def get_growing_period_at_date(reference_date: datetime.date, cache: dict, apps):
    def compute():
        growing_periods = get_all_growing_periods_ascending(cache=cache, apps=apps)
        for growing_period in growing_periods:
            if growing_period.start_date <= reference_date <= growing_period.end_date:
                return growing_period
        return None

    growing_periods_by_date_cache = get_from_cache_or_compute(
        cache, "growing_periods_by_date", lambda: {}
    )
    return get_from_cache_or_compute(
        growing_periods_by_date_cache, reference_date, compute
    )


def migrate_solidarity_from_subscriptions_to_dedicated_model(apps, schema):
    Subscription = apps.get_model("wirgarten", "Subscription")
    SolidarityContribution = apps.get_model(
        "solidarity_contribution", "SolidarityContribution"
    )
    cache = {}

    subscriptions = list(
        Subscription.objects.filter(solidarity_price_absolute__isnull=False)
    )
    contributions_by_member_id_and_growing_period = {}

    for subscription in subscriptions:
        if subscription.member_id not in contributions_by_member_id_and_growing_period:
            contributions_by_member_id_and_growing_period[subscription.member_id] = {}

        contributions_by_growing_period = contributions_by_member_id_and_growing_period[
            subscription.member_id
        ]
        growing_period = get_growing_period_at_date(
            reference_date=subscription.start_date,
            cache=cache,
            apps=apps,
        )
        if growing_period not in contributions_by_growing_period:
            contributions_by_growing_period[growing_period] = SolidarityContribution(
                member_id=subscription.member_id,
                amount=Decimal(0),
                start_date=subscription.start_date,
                end_date=subscription.end_date,
            )

        contribution = contributions_by_growing_period[growing_period]
        contribution.amount += subscription.solidarity_price_absolute

        subscription.solidarity_price_absolute = Decimal(0)

    Subscription.objects.bulk_update(subscriptions, ["solidarity_price_absolute"])

    all_contributions = []
    for (
        contributions_by_growing_period
    ) in contributions_by_member_id_and_growing_period.values():
        all_contributions.extend(contributions_by_growing_period.values())
    SolidarityContribution.objects.bulk_create(all_contributions)


class Migration(migrations.Migration):

    dependencies = [
        ("solidarity_contribution", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_solidarity_from_subscriptions_to_dedicated_model),
    ]
