# Generated by Django 5.2.1 on 2025-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solidarity_contribution", "0002_auto_20251212_1036"),
    ]

    operations = [
        migrations.AddField(
            model_name="solidaritycontribution",
            name="trial_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solidaritycontribution",
            name="trial_end_date_override",
            field=models.DateField(null=True),
        ),
    ]
