# Generated by Django 5.2.1 on 2025-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solidarity_contribution",
            "0003_solidaritycontribution_trial_disabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solidaritycontribution",
            name="cancellation_ts",
            field=models.DateField(null=True),
        ),
    ]
