# Generated by Django 6.0.1 on 2026-02-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        ("solidarity_contribution", "0004_solidaritycontribution_cancellation_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolidarityContributionChangedLogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="log.logentry",
                    ),
                ),
                (
                    "old_contribution_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "new_contribution_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("new_contribution_start_date", models.DateField()),
                (
                    "new_contribution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_logs_new_contribution",
                        to="solidarity_contribution.solidaritycontribution",
                    ),
                ),
                (
                    "old_contribution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_logs_old_contribution",
                        to="solidarity_contribution.solidaritycontribution",
                    ),
                ),
            ],
            bases=("log.logentry",),
        ),
    ]
