# Generated by Django 6.0.1 on 2026-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solidarity_contribution", "0005_solidaritycontributionchangedlogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="solidaritycontributionchangedlogentry",
            name="old_contribution_end_date",
            field=models.DateField(null=True),
        ),
    ]
