# Generated by Django 6.0.1 on 2026-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solidarity_contribution",
            "0006_solidaritycontributionchangedlogentry_old_contribution_end_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="solidaritycontributionchangedlogentry",
            name="new_contribution_start_date",
            field=models.DateField(null=True),
        ),
    ]
