# Generated by Django 6.0.1 on 2026-03-09 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solidarity_contribution",
            "0007_alter_solidaritycontributionchangedlogentry_new_contribution_start_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solidaritycontribution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solidaritycontribution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
