# Generated by Django 6.0.5 on 2026-07-09 15:15

from django.db import migrations
from django.utils import timezone


def set_solidarity_contribution_cancellation_ts(apps, schema):
    # in 0002_auto_20251212_1036, we create SolidarityContribution objects from the old Subscription objects.
    # Some of the old subscriptions where canceled, but we created SolidarityContributions not canceled, leading to them
    # being renewed or being considered by renewed by the MonthlyPaymentBuilder.
    # This migration attempts to fix that.

    solidarity_contribution_model = apps.get_model(
        "solidarity_contribution", "SolidarityContribution"
    )
    now = timezone.now()
    solidarity_contribution_model.objects.filter(
        end_date__lte=now, cancellation_ts__isnull=True
    ).update(cancellation_ts=now)


class Migration(migrations.Migration):

    dependencies = [
        ("solidarity_contribution", "0008_solidaritycontribution_created_at_and_more"),
    ]

    operations = [migrations.RunPython(set_solidarity_contribution_cancellation_ts)]
